"""The parameter dict the validated builders take.

`system.py`, `solvation.py` and `implicit.py` were written against this shape and read dozens of
keys from it. `sysgen.py` maps the user's two YAML files onto it -- see `sysgen._legacy_cfg` -- so
the chemistry is driven by the user's configuration without rewriting the builders' signatures,
which would risk the science for a cosmetic gain.

This is the BASE only. Every value a user can set is overwritten from their YAML before a build.
Extracted verbatim from the previous configuration module; the rest of that module -- resolution,
schema migration, manifest writing -- is gone.
"""

DEFAULTS = {'run': {'name': None, 'root': None, 'seed': 20260814},
 'system': {'slug': None, 'solute_kind': 'auto', 'require_input_route': None},
 'structure': {'etkdg': {'version': 'ETKDGv3',
                         'n_conformers': 10,
                         'seed': None,
                         'use_random_coords': False,
                         'prune_rms_thresh': 0.5,
                         'num_threads': 0},
               'mmff': {'variant': 'MMFF94s',
                        'max_iterations': 1000,
                        'energy_tolerance': 1e-06,
                        'force_tolerance': 0.0001}},
 'protonation': {'ph': 7.0,
                 'delete_existing_hydrogens': True,
                 'variants': None,
                 'skip_for_ligand': True},
 'forcefield': {'protein': 'amber19/protein.ff19SB.xml',
                'water': 'amber19/opc.xml',
                'ligand': 'openff-2.2.0',
                'ligand_charge_method': 'am1bcc',
                'extra_xml': []},
 'solvation': {'water_model': 'opc',
               'box_shape': 'dodecahedron',
               'padding_nm': 2.0,
               'padding_semantics': 'openmm',
               'cutoff_fit_policy': 'grow',
               'ionic_strength_molar': 0.15,
               'positive_ion': 'Na+',
               'negative_ion': 'Cl-',
               'neutralize': True},
 'system_build': {'nonbonded_method': 'PME',
                  'nonbonded_cutoff_nm': 1.0,
                  'minimum_image_margin_nm': 0.1,
                  'switch_distance_nm': None,
                  'use_dispersion_correction': True,
                  'ewald_error_tolerance': 0.0005,
                  'constraints': 'HBonds',
                  'rigid_water': True,
                  'hydrogen_mass_amu': None,
                  'hmr_scope': 'none',
                  'remove_cm_motion': True},
 'integrator': {'kind': 'langevin-middle',
                'timestep_fs': 2.0,
                'friction_per_ps': 1.0,
                'temperature_k': 300.0},
 'equilibration': {'protocol': 'staged',
                   'minimize_max_iterations': 0,
                   'minimize_tolerance_kj_mol_nm': 10.0,
                   'restraint_k_kj_mol_nm2': 4184.0,
                   'restraint_selection': 'solute-heavy',
                   'heat_from_k': 50.0,
                   'heat_to_k': None,
                   'heat_ps': 200.0,
                   'heat_timestep_fs': 1.0,
                   'heat_n_windows': 25,
                   'npt_restrained_ps': 200.0,
                   'release_schedule_kj_mol_nm2': [1046.0, 418.0, 0.0],
                   'release_ps_each': 200.0,
                   'npt_free_ps': 1000.0,
                   'timestep_fs': 2.0,
                   'nvt_ps': 250.0,
                   'npt_ps': 250.0,
                   'pressure_bar': 1.0,
                   'barostat_interval': 50,
                   'box_average_last_ps': 500.0,
                   'seed': None},
 'production': {'ensemble': None,
                'platform': 'CUDA',
                'precision': 'mixed',
                'device_index': None,
                'report': {'all_atom_ps': 10.0,
                           'solute_ps': 2.0,
                           'state_ps': 10.0,
                           'checkpoint_ps': 100.0},
                'md': {'scale_factor': 1.0,
                       'n_chunks': 10,
                       'chunk_ns': 100.0,
                       'seed': None,
                       'label': 'cold'},
                'remd': {'n_chunks': 10,
                         'chunk_ns': 100.0,
                         'scale_factors': None,
                         'exchange_interval_ps': 10.0,
                         'equilibration_ps': 10.0,
                         'seed': None}},
 'rest2': {'omega_exclusion': True,
           'proline_like_residues': ['PRO'],
           'max_proline_ring_size': 7,
           'ladder': {'s_cold': 1.0, 's_hot': 0.25, 'n_rungs': 6, 'interp': 'sqrt'}}}
