#!/usr/bin/env python
"""Rebuild every TYK2 System this fixture describes, from the inputs beside this script.

The built Systems are NOT committed: three complexes are 56 MB of generated bytes that this
reproduces in about two minutes each. What IS committed is everything they are built from --
the upstream inputs, the prepared structures, the three parameter packages, the build
configurations -- and the build RECORDS of the builds that were run, so the provenance is in git
even though the Systems are not.

    python build_tyk2_fixture.py --out <dir> [--ligand ejm_31] [--kind complex|solvated|vacuum]
    python build_tyk2_fixture.py --check-prepared      # no builds: only the preparation step

`$MD_DATA` is set to an empty directory inside --out for every build: this fixture never reads or
writes the machine's catalog, and the packages beside this script are the only ones used.

THE PREPARATION STEP, stated because it is an edit to someone else's structure. Upstream renamed
the capping residues UNK -> ACE/NME but left their ATOM names as Maestro wrote them, and the
force-field templates match on names, so `build-top` refuses the protein with "2 residue(s) are
missing heavy atoms (A:889 ACE lacks C CH3; A:1178 NME lacks C N)". The atoms are all present.
`input.missing_atoms: add` would have had PDBFixer ADD a second copy of each. The twelve renames
below are the fix, applied here rather than by hand, and no other atom is touched.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent


class FixtureError(SystemExit):
    """A refusal a person can act on, rather than a traceback."""

    def __init__(self, message: str) -> None:
        super().__init__(f"build_tyk2_fixture: {message}")


def _require(path: Path, what: str) -> Path:
    if not path.exists():
        raise FixtureError(
            f"{what} is missing: {path}. This fixture is `tests/data/alchemy/tyk2-v1/` and every "
            f"file it needs is committed beside this script; a partial copy cannot rebuild it. "
            f"Restore it from the repository (see README.md, 'Source and licence').")
    return path


def check_inputs() -> int:
    """The upstream files, by sha256: this fixture was prepared from THESE bytes.

    Upstream is a moving repository. A newer `protein.pdb` may be a better structure and is still
    not the one the committed packages, records and prepared structures were made from, so it is
    named as a difference rather than silently rebuilt into something else.
    """
    import hashlib

    listing = _require(HERE / "inputs" / "SHA256SUMS", "the input checksum list")
    bad = 0
    for line in listing.read_text().splitlines():
        digest, name = line.split()
        path = _require(HERE / "inputs" / name.lstrip("*"), f"the upstream input {name}")
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        if actual != digest:
            print(f"{name}: sha256 {actual}, not the {digest} this fixture was prepared from. "
                  f"README.md names the upstream commit these came from.", file=sys.stderr)
            bad += 1
    return bad

#: Maestro cap atom names -> the names the Amber ff14SB templates use. The whole edit.
CAP_RENAMES = {
    "ACE": {"C1": "C", "O1": "O", "C2": "CH3", "H2_1": "HH31", "H2_2": "HH32", "H2_3": "HH33"},
    "NME": {"N1": "N", "HN1": "H", "C1": "CH3", "H1_1": "HH31", "H1_2": "HH32", "H1_3": "HH33"},
}

def reference_of(ligand: str) -> str:
    return LIGANDS[ligand][1]


#: ligand -> (residue name, catalog reference). The packages are committed, so nothing is
#: charged again.
LIGANDS = {
    "ejm_31": ("L31", "LOCAL-DKNAYSZNMZIMIZ/param_bd1388e5fe3e"),
    "ejm_42": ("L42", "LOCAL-CEJFWHOOEUEYOE/param_c1d8d1147233"),
    "ejm_43": ("L43", "LOCAL-HKQHWWQCRDXFGC/param_c66a3e91a5dd"),
}
KINDS = ("complex", "solvated", "vacuum")


def rename_caps(source: Path) -> str:
    """The protein with its cap atoms renamed.

    Byte-identical to `prepared/protein_caps_renamed.pdb`.
    """
    out, renamed = [], 0
    for line in source.read_text().splitlines(keepends=True):
        if line.startswith(("ATOM", "HETATM")):
            table = CAP_RENAMES.get(line[17:20].strip())
            name = line[12:16].strip()
            if table and name in table:
                line = line[:12] + f"{table[name]:<4}"[:4] + line[16:]
                renamed += 1
        out.append(line)
    if renamed != 12:
        raise SystemExit(f"expected 12 cap atoms to rename, renamed {renamed}")
    return "".join(out)


def complex_pdb(protein: str, ligand_sdf: Path, residue_name: str) -> str:
    """The protein plus the ligand's HEAVY atoms as one HETATM residue, chain B, resid 1.

    Hydrogens are the package's, placed by `ligands.mapping` onto these coordinates; the ligand's
    pose is the deposited one, in the protein's frame, and no atom of it is moved.
    """
    from rdkit import Chem

    mol = Chem.SDMolSupplier(str(ligand_sdf), removeHs=False)[0]
    conformer = mol.GetConformer()
    lines = [l.rstrip("\n") for l in protein.splitlines() if l.startswith(("ATOM", "TER"))]
    serial = max(int(l[6:11]) for l in lines if l.startswith("ATOM"))
    counts: dict[str, int] = {}
    for atom in mol.GetAtoms():
        if atom.GetAtomicNum() == 1:
            continue
        symbol = atom.GetSymbol()
        counts[symbol] = counts.get(symbol, 0) + 1
        point = conformer.GetAtomPosition(atom.GetIdx())
        serial += 1
        lines.append(f"HETATM{serial:5d} {symbol + str(counts[symbol]):<4} {residue_name} B   1    "
                     f"{point.x:8.3f}{point.y:8.3f}{point.z:8.3f}  1.00  0.00          {symbol:>2}")
    return "\n".join(lines + ["TER", "END"]) + "\n"


def prepared_files() -> dict[str, str]:
    """Every prepared structure, derived from `inputs/` here and now."""
    protein = rename_caps(_require(HERE / "inputs" / "protein.pdb", "the upstream protein"))
    files = {"protein_caps_renamed.pdb": protein}
    for ligand, (residue_name, _) in LIGANDS.items():
        sdf = _require(HERE / "prepared" / f"{ligand}.sdf", f"the extracted ligand {ligand}")
        files[f"complex_{ligand}.pdb"] = complex_pdb(protein, sdf, residue_name)
    return files


def check_prepared() -> int:
    """Refuse if the upstream inputs, or the prepared files derived from them, have moved."""
    bad = check_inputs()
    for name, text in prepared_files().items():
        committed = _require(HERE / "prepared" / name, f"the prepared structure {name}").read_text()
        if committed != text:
            print(f"{name}: the committed file is not what this script derives from inputs/. "
                  f"Either an input changed (see above) or the preparation did; nothing is "
                  f"rebuilt from a file that does not reproduce.", file=sys.stderr)
            bad += 1
    print("inputs and prepared files reproduce" if not bad
          else f"{bad} file(s) differ; nothing was built")
    return bad


def build(out: Path, ligand: str, kind: str) -> Path:
    """One `md-openmm build-top`, with MD_DATA pointed at an empty directory inside *out*."""
    residue_name, _ = LIGANDS[ligand]
    work = out / ligand / kind
    (work / "input").mkdir(parents=True, exist_ok=True)
    (work / "build").mkdir(parents=True, exist_ok=True)
    if kind == "complex":
        name = "complex.pdb"
        (work / "input" / name).write_text(prepared_files()[f"complex_{ligand}.pdb"])
    else:
        name = f"{ligand}.sdf"
        shutil.copy(HERE / "prepared" / name, work / "input" / name)
    config = work / "build" / "build.config"
    text = _require(HERE / "builds" / ligand / kind / "build.config",
                    f"the {kind} build configuration for {ligand}").read_text()
    for reference in (reference_of(ligand),):
        _require(HERE / "packages" / reference, f"the parameter package {reference}")
    config.write_text(text.replace("../../../packages", str(HERE / "packages")))
    md_data = out / "md_data_root"
    md_data.mkdir(parents=True, exist_ok=True)
    done = subprocess.run(
        [sys.executable, "-m", "md_tools.cli.md_openmm", "build-top", "-i", f"input/{name}",
         "--config", "build/build.config", "-os", "build/built.xml", "-op", "build/built.pdb",
         "-log", "build/built.log"],
        cwd=work, env={**os.environ, "MD_DATA": str(md_data), "PYTHONPATH": _md_tools_path()})
    if done.returncode != 0:
        # build-top has already said why, above, and says it better than a traceback would.
        raise FixtureError(
            f"`md-openmm build-top` refused the {kind} build of {ligand} (exit "
            f"{done.returncode}); its own message is above. Nothing further was built, and "
            f"{work} holds what it wrote.")
    return work / "build"


def _md_tools_path() -> str:
    """The md_tools THIS script imports, as an absolute entry for the subprocess's PYTHONPATH.

    build-top runs with `cwd` inside the build directory, so a relative `PYTHONPATH=src` stops
    resolving and the subprocess silently imports whatever md_tools is installed in the
    environment -- which is how this script first built against 0.5.4 while the caller believed it
    was testing the checkout. The same rule the suite's conftest applies, applied here.
    """
    import md_tools

    root = str(Path(md_tools.__file__).resolve().parents[1])
    existing = os.environ.get("PYTHONPATH", "")
    return os.pathsep.join([root, existing]) if existing else root


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=None,
                        help="where the builds go; a temporary directory when omitted")
    parser.add_argument("--ligand", choices=sorted(LIGANDS), action="append")
    parser.add_argument("--kind", choices=KINDS, action="append")
    parser.add_argument("--check-prepared", action="store_true",
                        help="only check that prepared/ is what this script derives")
    args = parser.parse_args()
    if args.check_prepared:
        return check_prepared()
    if check_prepared():
        return 1
    out = args.out or Path(tempfile.mkdtemp(prefix="tyk2-"))
    out.mkdir(parents=True, exist_ok=True)
    for ligand in args.ligand or sorted(LIGANDS):
        for kind in args.kind or KINDS:
            print(f"--- {ligand} {kind}", flush=True)
            print("   ", build(out, ligand, kind))
    print(f"built into {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
