#!/usr/bin/env python
"""Rebuild every TYK2 System this fixture describes, from the inputs beside this script.

The built Systems are NOT committed: three complexes are 56 MB of generated bytes that this
reproduces in about two minutes each. What IS committed is everything they are built from --
the upstream inputs, the prepared structures, the three parameter packages, the build
configurations -- and the build RECORDS of the builds that were run, so the provenance is in git
even though the Systems are not.

    python build_tyk2_fixture.py --out <dir> [--ligand ejm_31] [--kind complex|solvated|vacuum]
    python build_tyk2_fixture.py --check-prepared      # no builds: only the preparation step

`$MD_DATA` is set to an empty directory inside --out for every build: this fixture never reads or
writes the machine's catalog, and the packages beside this script are the only ones used.

THE PREPARATION STEP, stated because it is an edit to someone else's structure. Upstream renamed
the capping residues UNK -> ACE/NME but left their ATOM names as Maestro wrote them, and the
force-field templates match on names, so `build-top` refuses the protein with "2 residue(s) are
missing heavy atoms (A:889 ACE lacks C CH3; A:1178 NME lacks C N)". The atoms are all present.
`input.missing_atoms: add` would have had PDBFixer ADD a second copy of each. The twelve renames
below are the fix, applied here rather than by hand, and no other atom is touched.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent

#: Maestro cap atom names -> the names the Amber ff14SB templates use. The whole edit.
CAP_RENAMES = {
    "ACE": {"C1": "C", "O1": "O", "C2": "CH3", "H2_1": "HH31", "H2_2": "HH32", "H2_3": "HH33"},
    "NME": {"N1": "N", "HN1": "H", "C1": "CH3", "H1_1": "HH31", "H1_2": "HH32", "H1_3": "HH33"},
}

#: ligand -> (residue name, catalog reference). The packages are committed; nothing is charged again.
LIGANDS = {
    "ejm_31": ("L31", "LOCAL-DKNAYSZNMZIMIZ/param_bd1388e5fe3e"),
    "ejm_42": ("L42", "LOCAL-CEJFWHOOEUEYOE/param_c1d8d1147233"),
    "ejm_43": ("L43", "LOCAL-HKQHWWQCRDXFGC/param_c66a3e91a5dd"),
}
KINDS = ("complex", "solvated", "vacuum")


def rename_caps(source: Path) -> str:
    """The protein with its cap atoms renamed. Byte-identical to `prepared/protein_caps_renamed.pdb`."""
    out, renamed = [], 0
    for line in source.read_text().splitlines(keepends=True):
        if line.startswith(("ATOM", "HETATM")):
            table = CAP_RENAMES.get(line[17:20].strip())
            name = line[12:16].strip()
            if table and name in table:
                line = line[:12] + f"{table[name]:<4}"[:4] + line[16:]
                renamed += 1
        out.append(line)
    if renamed != 12:
        raise SystemExit(f"expected 12 cap atoms to rename, renamed {renamed}")
    return "".join(out)


def complex_pdb(protein: str, ligand_sdf: Path, residue_name: str) -> str:
    """The protein plus the ligand's HEAVY atoms as one HETATM residue, chain B, resid 1.

    Hydrogens are the package's, placed by `ligands.mapping` onto these coordinates; the ligand's
    pose is the deposited one, in the protein's frame, and no atom of it is moved.
    """
    from rdkit import Chem

    mol = Chem.SDMolSupplier(str(ligand_sdf), removeHs=False)[0]
    conformer = mol.GetConformer()
    lines = [l.rstrip("\n") for l in protein.splitlines() if l.startswith(("ATOM", "TER"))]
    serial = max(int(l[6:11]) for l in lines if l.startswith("ATOM"))
    counts: dict[str, int] = {}
    for atom in mol.GetAtoms():
        if atom.GetAtomicNum() == 1:
            continue
        symbol = atom.GetSymbol()
        counts[symbol] = counts.get(symbol, 0) + 1
        point = conformer.GetAtomPosition(atom.GetIdx())
        serial += 1
        lines.append(f"HETATM{serial:5d} {symbol + str(counts[symbol]):<4} {residue_name} B   1    "
                     f"{point.x:8.3f}{point.y:8.3f}{point.z:8.3f}  1.00  0.00          {symbol:>2}")
    return "\n".join(lines + ["TER", "END"]) + "\n"


def prepared_files() -> dict[str, str]:
    """Every prepared structure, derived from `inputs/` here and now."""
    protein = rename_caps(HERE / "inputs" / "protein.pdb")
    files = {"protein_caps_renamed.pdb": protein}
    for ligand, (residue_name, _) in LIGANDS.items():
        files[f"complex_{ligand}.pdb"] = complex_pdb(protein, HERE / "prepared" / f"{ligand}.sdf",
                                                     residue_name)
    return files


def check_prepared() -> int:
    """Refuse if what the committed prepared/ files say differs from what this script derives."""
    bad = 0
    for name, text in prepared_files().items():
        committed = (HERE / "prepared" / name).read_text()
        if committed != text:
            print(f"{name}: the committed file is not what this script derives", file=sys.stderr)
            bad += 1
    print("prepared files reproduce" if not bad else f"{bad} prepared file(s) differ")
    return bad


def build(out: Path, ligand: str, kind: str) -> Path:
    """One `md-openmm build-top`, with MD_DATA pointed at an empty directory inside *out*."""
    residue_name, _ = LIGANDS[ligand]
    work = out / ligand / kind
    (work / "input").mkdir(parents=True, exist_ok=True)
    (work / "build").mkdir(parents=True, exist_ok=True)
    if kind == "complex":
        name = "complex.pdb"
        (work / "input" / name).write_text(prepared_files()[f"complex_{ligand}.pdb"])
    else:
        name = f"{ligand}.sdf"
        shutil.copy(HERE / "prepared" / name, work / "input" / name)
    config = work / "build" / "build.config"
    text = (HERE / "builds" / ligand / kind / "build.config").read_text()
    config.write_text(text.replace("../../../packages", str(HERE / "packages")))
    md_data = out / "md_data_root"
    md_data.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [sys.executable, "-m", "md_tools.cli.md_openmm", "build-top", "-i", f"input/{name}",
         "--config", "build/build.config", "-os", "build/built.xml", "-op", "build/built.pdb",
         "-log", "build/built.log"],
        cwd=work, check=True,
        env={**os.environ, "MD_DATA": str(md_data), "PYTHONPATH": _md_tools_path()})
    return work / "build"


def _md_tools_path() -> str:
    """The md_tools THIS script imports, as an absolute entry for the subprocess's PYTHONPATH.

    build-top runs with `cwd` inside the build directory, so a relative `PYTHONPATH=src` stops
    resolving and the subprocess silently imports whatever md_tools is installed in the
    environment -- which is how this script first built against 0.5.4 while the caller believed it
    was testing the checkout. The same rule the suite's conftest applies, applied here.
    """
    import md_tools

    root = str(Path(md_tools.__file__).resolve().parents[1])
    existing = os.environ.get("PYTHONPATH", "")
    return os.pathsep.join([root, existing]) if existing else root


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=None,
                        help="where the builds go; a temporary directory when omitted")
    parser.add_argument("--ligand", choices=sorted(LIGANDS), action="append")
    parser.add_argument("--kind", choices=KINDS, action="append")
    parser.add_argument("--check-prepared", action="store_true",
                        help="only check that prepared/ is what this script derives")
    args = parser.parse_args()
    if args.check_prepared:
        return check_prepared()
    if check_prepared():
        return 1
    out = args.out or Path(tempfile.mkdtemp(prefix="tyk2-"))
    out.mkdir(parents=True, exist_ok=True)
    for ligand in args.ligand or sorted(LIGANDS):
        for kind in args.kind or KINDS:
            print(f"--- {ligand} {kind}", flush=True)
            print("   ", build(out, ligand, kind))
    print(f"built into {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
