"""Generate a cv.yaml naming every proper torsion of the solute.

`collective_variables.generate: all_solute_torsions` in a `build-md` configuration asks for this.
The output is an ORDINARY cv.yaml -- explicit atom selectors, one entry per torsion -- written and
copied in exactly as a hand-written one would be, so the runtime's rule that a CV names its atoms
explicitly and never infers them is kept: the inference happens once, at build time, into a file a
reader can open, and the run measures what that file says.

WHICH TORSIONS. Every chain i-j-k-l of four distinct solute atoms joined by three bonds, each
listed once (a chain and its reverse are the same dihedral). Hydrogens are included: "all" means
all, and a reader who wants fewer can delete lines from the generated file and pass it as
`collective_variables.file` instead.

WHERE THE BONDS COME FROM is the caller's business, deliberately. This module imports nothing from
OpenMM -- a test asserts it through the AST, because CV reporting is observation and must not be
able to reach the Hamiltonian -- so `build-md` reads the bond graph from the serialised System
(bonds and constraints) and hands it in as pairs.
"""
from __future__ import annotations

import re
from typing import Any, Iterable

__all__ = ["GENERATORS", "solute_torsions", "cv_document", "cv_yaml_text"]

#: The generators `collective_variables.generate` accepts. One today.
GENERATORS = ("all_solute_torsions",)


def _identifier(text: str) -> str:
    """A fragment safe inside a CV name: letters, digits and underscores only."""
    cleaned = re.sub(r"[^A-Za-z0-9]", "", str(text))
    return cleaned or "X"


def solute_torsions(atoms: list[dict[str, Any]], bonds: Iterable[tuple[int, int]],
                    solute: Iterable[int]) -> list[tuple[int, int, int, int]]:
    """Every proper torsion among `solute` atoms, as index quadruples, each dihedral once.

    `atoms` is indexed by atom index; `bonds` are unordered index pairs over the whole system.
    Ordered by the central bond, then by the outer atoms, so the file is deterministic.
    """
    members = {int(i) for i in solute}
    neighbours: dict[int, set[int]] = {i: set() for i in members}
    for a, b in bonds:
        a, b = int(a), int(b)
        if a in members and b in members and a != b:
            neighbours[a].add(b)
            neighbours[b].add(a)
    found: set[tuple[int, int, int, int]] = set()
    for j in sorted(members):
        for k in sorted(neighbours[j]):
            if k <= j:
                continue
            for i in sorted(neighbours[j] - {k}):
                for l in sorted(neighbours[k] - {j, i}):
                    found.add((i, j, k, l))
    return sorted(found, key=lambda q: (q[1], q[2], q[0], q[3]))


def cv_document(atoms: list[dict[str, Any]], torsions: list[tuple[int, int, int, int]],
                *, source: str) -> dict[str, Any]:
    """The cv.yaml document for these torsions, with selector-based entries.

    `atoms[i]` must carry `name`, `residue_name`, `residue_id` and `chain_id`. Names are
    `<RES><id>_<a>_<b>_<c>_<d>`, disambiguated with a numeric suffix if two torsions would still
    share one (atom names are not guaranteed unique within a residue).
    """
    entries = []
    used: dict[str, int] = {}
    for quad in torsions:
        first = atoms[quad[1]]
        stem = (f"{_identifier(first['residue_name'])}{_identifier(first['residue_id'])}_"
                + "_".join(_identifier(atoms[i]["name"]) for i in quad))
        if not stem[0].isalpha():
            stem = f"T{stem}"
        count = used.get(stem, 0)
        used[stem] = count + 1
        name = stem if count == 0 else f"{stem}_{count + 1}"
        entries.append({
            "name": name,
            "type": "torsion",
            "atoms": [{"chain": str(atoms[i]["chain_id"]), "residue": str(atoms[i]["residue_id"]),
                       "atom": str(atoms[i]["name"])} for i in quad],
        })
    return {"schema_version": 1, "generated_by": source, "collective_variables": entries}


def cv_yaml_text(document: dict[str, Any]) -> str:
    """The document as YAML, with a header saying it was generated and how to replace it."""
    import yaml

    header = (
        "# GENERATED by `md-openmm build-md` from `collective_variables.generate: "
        f"{document['generated_by']}`.\n"
        "# Every proper torsion of the solute, by explicit atom selector. To report fewer, copy\n"
        "# this file, delete entries, and name the copy in `collective_variables.file` instead.\n")
    body = {k: v for k, v in document.items() if k != "generated_by"}
    return header + yaml.safe_dump(body, sort_keys=False, default_flow_style=None, width=100)
