#!/usr/bin/env bash
# Run this stage. Generated by md-openmm.
#
#   ./run.sh                          # CUDA, which is the default and the only silent one
#   MD_PLATFORM=CPU ./run.sh          # anything but CUDA has to be asked for by name
#
# This stage reads its parent's final_state.xml and writes its own. Run the stages in order, or
# use ../run_all.sh.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

PYTHON="__PYTHON__"
if [ ! -x "$PYTHON" ]; then
    PYTHON="$(command -v python3 || command -v python)"
fi
export CUDA_DEVICE_ORDER="${CUDA_DEVICE_ORDER:-PCI_BUS_ID}"

echo "== __STAGE__ =="

# `--check` is a preflight and nothing else, so it does not append to this stage's run log: a
# check that leaves a trace in the record of what ran is not the non-destructive thing it claims
# to be. Everything else is teed as usual.
for argument in "$@"; do
    if [ "$argument" = "--check" ]; then
        exec "$PYTHON" __SCRIPT__ "$@"
    fi
done
"$PYTHON" __SCRIPT__ "$@" 2>&1 | tee -a __LOG__
