#!/usr/bin/env python3
"""Build, run, export and register the md-tools test datasets: ALA and phenol, 1 ns per method.

    python run_tests.py prepare  --root DIR
    python run_tests.py run      --root DIR --gpus 0,3,4,5,6,7,8 --no-ladder-gpus 0
    python run_tests.py export   --root DIR
    python run_tests.py register --root DIR --project-repo PATH [--dry-run]

Run in the activated `openmm-env`, with no PYTHONPATH: `importlib.metadata` reads the INSTALLED
distribution, so a run pointed at a source tree records one engine and runs another. The ALA
campaign lost 37 minutes of runs to exactly that.

Layout under DIR, one build per system and solvent, one `build-md` directory per method beside it
so every generated `run.sh` finds `../built.pdb` and `../built.xml`:

    DIR/ALA-test/implicit/{ALA.pdb, sys.config, built.*, cMD-cold/, cMD-hot/, REST2/}
    DIR/ALA-test/explicit/...
    DIR/phenol-test/{implicit,explicit}/...

Each method directory is registered as `$MD_DATA/2026/md-tools/<system>-test/<method>-<solvent>`.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
POLL = 30

#: system -> (structure file, build route)
SYSTEMS = {"ALA": (REPO / "tests" / "data" / "ALA.pdb", "peptide"),
           "phenol": (HERE / "phenol.smi", "ligand")}
SOLVENTS = ("implicit", "explicit")
#: method directory -> (config stem, exported stage)
METHODS = {"cMD-cold": ("cold", "cMD"), "cMD-hot": ("hot", "cMD"), "REST2": ("rest2", "REST2")}
LADDER_RANKS = {"implicit": 4, "explicit": 6}


def note(root: Path, message: str) -> None:
    line = f"{time.strftime('%Y-%m-%d %H:%M:%S')}  {message}"
    print(line, flush=True)
    with (root / "schedule.log").open("a", encoding="utf-8") as handle:
        handle.write(line + "\n")


def md_openmm(*args: str, cwd: Path) -> None:
    done = subprocess.run(["md-openmm", *args], cwd=cwd, capture_output=True, text=True)
    if done.returncode != 0:
        raise SystemExit(f"md-openmm {' '.join(args)} failed in {cwd}:\n{done.stderr[-3000:]}")


def builds(root: Path):
    for system in SYSTEMS:
        for solvent in SOLVENTS:
            yield system, solvent, root / f"{system}-test" / solvent


def prepare(root: Path) -> None:
    """build-top once per system and solvent, build-md once per method. Refuses to reuse a tree."""
    for system, solvent, build in builds(root):
        if build.exists():
            raise SystemExit(f"{build} exists; prepare writes a fresh tree and replaces nothing")
    for system, solvent, build in builds(root):
        structure, route = SYSTEMS[system]
        build.mkdir(parents=True)
        shutil.copy2(structure, build / structure.name)
        shutil.copy2(HERE / "configs" / f"sys.{route}-{solvent}.config", build / "sys.config")
        md_openmm("build-top", "-i", structure.name, "-os", "built.xml", "-op", "built.pdb",
                  "-log", "built.log", "--config", "sys.config", cwd=build)
        for method, (stem, _stage) in METHODS.items():
            config = f"{stem}_{solvent}.config"
            shutil.copy2(HERE / "configs" / config, build / config)
            md_openmm("build-md", "-odir", f"./{method}", "--config", config, cwd=build)
        note(root, f"prepared {build.relative_to(root)}")


def from_cold_script(build: Path) -> Path:
    """The hot explicit launcher: its own run.sh, minus minimisation, from the cold run's box.

    A scaled run is fixed-volume, so it cannot equilibrate its own box; build-top's box is below
    the equilibrium density. The cold run's last pressure-coupled state supplies the box, and every
    other flag of every stage is left exactly as build-md generated it.
    """
    cold = (build / "cMD-cold" / "run.sh").read_text(encoding="utf-8")
    block = cold.split('echo "== cMD =="', 1)[1]
    parent = re.search(r"-c (\S+)", block).group(1)
    hot = build / "cMD-hot"
    text = (hot / "run.sh").read_text(encoding="utf-8")
    head, *blocks = re.split(r'(?=^echo "== )', text, flags=re.M)
    kept = [b for b in blocks if not b.startswith('echo "== min ==')]
    body = "".join(kept).replace("-c min.xml", f"-c ../cMD-cold/{parent}", 1)
    header = ("# Generated by run_tests.py from build-md's run.sh: minimisation removed, and the\n"
              f"# first stage continues from the cold run's {parent} -- its pressure-equilibrated\n"
              "# box -- because a run at tau > 0 is fixed-volume and cannot equilibrate one.\n")
    script = hot / "run_from_cold.sh"
    script.write_text(head.replace("set -euo pipefail", header + "set -euo pipefail", 1) + body,
                      encoding="utf-8")
    script.chmod(0o755)
    return script


def cold_box_ready(build: Path) -> bool:
    """The cold run's pressure-equilibrated state exists and its stage says it completed."""
    cold =(build / "cMD-cold" / "run.sh").read_text(encoding="utf-8")
    parent = re.search(r"-c (\S+)", cold.split('echo "== cMD =="', 1)[1]).group(1)
    log = build / "cMD-cold" / (Path(parent).stem + ".log")
    if not (build / "cMD-cold" / parent).is_file() or not log.is_file():
        return False
    from md_tools.build.record import read_record

    try:
        return read_record(log).get("status") == "completed"
    except Exception:
        return False


def externally_busy() -> set[int]:
    """Devices with a compute process on them that this driver did not start."""
    apps = subprocess.run(["nvidia-smi", "--query-compute-apps=gpu_uuid", "--format=csv,noheader"],
                          capture_output=True, text=True)
    uuids = {u.strip() for u in apps.stdout.split() if u.strip()}
    index = subprocess.run(["nvidia-smi", "--query-gpu=index,uuid", "--format=csv,noheader"],
                           capture_output=True, text=True)
    busy = set()
    for line in index.stdout.splitlines():
        idx, _, uuid = (x.strip() for x in line.partition(","))
        if uuid in uuids:
            busy.add(int(idx))
    return busy


def run(root: Path, gpus: list[int], no_ladder: set[int]) -> None:
    jobs = []          # (name, directory, devices, ladder, launcher, wait-for)
    for system, solvent, build in builds(root):
        for method in METHODS:
            ladder = method == "REST2"
            devices = LADDER_RANKS[solvent] if ladder else 1
            wait = None
            launcher = ["./run.sh", "../built.pdb", "../built.xml"]
            if method == "cMD-hot" and solvent == "explicit":
                from_cold_script(build)
                launcher, wait = ["./run_from_cold.sh", "../built.pdb", "../built.xml"], build
            jobs.append((f"{system}-test/{solvent}/{method}", build / method, devices, ladder,
                         launcher, wait))
    pending = sorted(jobs, key=lambda job: -job[2])          # ladders first: they need the most
    running: dict[str, tuple] = {}
    failed: list[str] = []
    note(root, f"start: {len(pending)} job(s) on GPU {','.join(map(str, gpus))}")
    while pending or running:
        for name, (process, devices) in list(running.items()):
            if process.poll() is not None:
                status = "DONE " if process.returncode == 0 else f"FAILED ({process.returncode})"
                note(root, f"{status} {name}, released GPU {','.join(map(str, devices))}")
                if process.returncode:
                    failed.append(name)
                del running[name]
        busy = {d for _, ds in running.values() for d in ds} | externally_busy()
        free = [g for g in gpus if g not in busy]
        for job in list(pending):
            name, directory, count, ladder, launcher, wait = job
            if wait is not None:
                cold = f"{name.rsplit('/', 1)[0]}/cMD-cold"
                if cold in failed:
                    note(root, f"SKIP {name}: {cold} failed")
                    pending.remove(job)
                    failed.append(name)
                    continue
                if not cold_box_ready(wait):
                    continue
            usable = [g for g in free if not (ladder and g in no_ladder)]
            if len(usable) < count:
                continue
            devices = usable[:count]
            env = {**os.environ, "CUDA_VISIBLE_DEVICES": ",".join(map(str, devices))}
            with (directory / "campaign.log").open("a", encoding="utf-8") as log:
                process = subprocess.Popen(launcher, cwd=directory, env=env, stdout=log,
                                           stderr=subprocess.STDOUT, start_new_session=True)
            running[name] = (process, devices)
            free = [g for g in free if g not in devices]
            pending.remove(job)
            note(root, f"START {name} on GPU {','.join(map(str, devices))} (pid {process.pid})")
        if pending or running:
            time.sleep(POLL)
    note(root, f"finished; {len(failed)} failed: {failed}" if failed else "finished; all passed")
    if failed:
        raise SystemExit(1)


def export(root: Path) -> None:
    for system, solvent, build in builds(root):
        for method, (_stem, stage) in METHODS.items():
            directory = build / method
            if (directory / "bundle").exists():
                raise SystemExit(f"{directory / 'bundle'} exists; export replaces nothing")
            # Absolute: 0.5.2's exporter looks for the built System "beside or above" -idata, and
            # a bare `.` has no parents to look in. See docs/backlog.md.
            md_openmm("export-reference", "-idata", str(directory), "-odir",
                      str(directory / "bundle"), "--stage", stage, cwd=directory)
            note(root, f"exported {directory.relative_to(root)}/bundle")


def register(root: Path, project_repo: Path, dry_run: bool) -> None:
    from md_tools.build.record import read_record

    for system, solvent, build in builds(root):
        for method, (_stem, stage) in METHODS.items():
            directory = build / method
            environment = read_record(directory / f"{stage}.log").get("environment") or {}
            # The version is a PACKAGE the record lists, beside openmm and the rest; there is no
            # top-level `md_tools_version`, and reading one wrote "md-tools None" into the first
            # registration of these datasets.
            version = (environment.get("packages") or {}).get("md-tools")
            notes = (f"md-tools test data: {system}, {solvent} solvent, {method}, 1 ns per "
                     f"state. Engine as the run records it: md-tools "
                     f"{version}, commit "
                     f"{environment.get('md_tools_commit')}, from the wheel installed in "
                     f"openmm-env. Built and run by docs/campaigns/test-systems-2026-09/"
                     f"run_tests.py; see that directory's README.")
            argv = ["data-register", "-idata", str(directory), "-project_name", "md-tools",
                    "-data_name", f"{system}-test/{method}-{solvent}", "-year", "2026",
                    "--project-repo", str(project_repo), "--notes", notes]
            if dry_run:
                argv.append("--dry-run")
            md_openmm(*argv, cwd=root)
            note(root, f"{'checked' if dry_run else 'registered'} {system}-test/{method}-{solvent}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("step", choices=("prepare", "run", "export", "register"))
    parser.add_argument("--root", required=True, type=Path)
    parser.add_argument("--gpus", default="", help="comma-separated devices this run may use")
    parser.add_argument("--no-ladder-gpus", default="",
                        help="devices a ladder must not span (a different card model)")
    parser.add_argument("--project-repo", type=Path)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if os.environ.get("PYTHONPATH"):
        raise SystemExit("PYTHONPATH is set; unset it so the installed md-tools is what runs")
    root = args.root.resolve()
    root.mkdir(parents=True, exist_ok=True)
    if args.step == "prepare":
        prepare(root)
    elif args.step == "run":
        gpus = [int(g) for g in args.gpus.split(",") if g.strip()]
        if not gpus:
            raise SystemExit("--gpus is required for run")
        run(root, gpus, {int(g) for g in args.no_ladder_gpus.split(",") if g.strip()})
    elif args.step == "export":
        export(root)
    else:
        if args.project_repo is None:
            raise SystemExit("--project-repo is required for register")
        register(root, args.project_repo.resolve(), args.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main())
