#!/usr/bin/env python
"""Annealed importance sampling along the REST2 tau path. Generated by md-openmm; edit freely.

Each AIS trajectory is one independent switching path: a configuration is drawn from an existing
equilibrium ensemble at `tau_start`, velocities are assigned fresh, and the Hamiltonian is then
annealed to `tau_end` while the coordinates propagate. The nonequilibrium work that switching costs
is accumulated and written beside the coordinates it belongs to.

    inputs  : the prepared system in inputs/, and a source trajectory you already ran
    outputs : trajectory_NNNN/{observations.dcd, observations.csv, final_state.xml, stdout.log}
              selected_initial_frames.csv, resolved_run.yaml, provenance.yaml

    ./run.sh                     run every path, spread over the visible CUDA devices
    python run.py --worker 3     run one path in this process (what run.py spawns internally)

WHAT THIS DOES, AND WHAT IT DOES NOT

The Hamiltonian actually changes: at each update the force parameters are rewritten through the
same REST2 decomposition a static rung is built with (`rest2_scaling.TauSwitcher`), not interpolated
between two endpoint energies. `s = (1 - tau)^2` scales solute-solute terms, `sqrt(s) = 1 - tau`
scales solute-environment terms, and torsions about an omega bond are left alone -- the same rules,
the same omega bond list from inputs/solute.yaml, that cMD and REST2 use.

Temperature and beta are constant along the path. This is Hamiltonian switching, not temperature
annealing.

Work uses the discrete nonequilibrium convention

    delta_W_j = U(tau_{j+1}, x_j) - U(tau_j, x_j)

-- the parameters change first, at frozen coordinates, and the configuration then propagates under
the new Hamiltonian. Physical work is kJ/mol; reduced work is beta*W.

Switching is at FIXED VOLUME. There is no barostat in the System and none is added, so an explicit
source frame keeps the box it came from. An NPT equilibrium ensemble may seed these paths, but the
pressure-volume contribution to the work is NOT part of this implementation.

This is forward-only, has no mid-path restart, and computes no free-energy estimator. The work
values it writes are the input a Hummer-Szabo or Jarzynski analysis would consume; producing that
estimate is somebody else's job and this file does not pretend to do it.

Every path is stored in its own directory with its own DCD. They are independent realisations and
concatenating them would produce a file that looks like one continuous trajectory and is not.

This script imports OpenMM, PyYAML, NumPy and MDTraj -- never `md_templates`.
"""
import argparse
import csv
import hashlib
import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import yaml
from openmm import LangevinMiddleIntegrator, Platform, XmlSerializer, unit
from openmm.app import DCDFile, PDBFile

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from rest2_scaling import TauSwitcher, scale_factor_for_tau           # noqa: E402

PROJECT = HERE.parent
CONFIG = yaml.safe_load((PROJECT / "md.config.yaml").read_text())
PATH_DEFINITION = yaml.safe_load((HERE / "path_definition.yaml").read_text())
INPUTS = (PROJECT / CONFIG["paths"]["inputs_folder"]).resolve()
SOLUTE = yaml.safe_load((INPUTS / "solute.yaml").read_text())

common = CONFIG["common"]
method = CONFIG["AIS"]
implicit = bool(PATH_DEFINITION["ensemble"]["implicit_solvent"])

TEMPERATURE_K = float(common["temperature_kelvin"])
TEMPERATURE = TEMPERATURE_K * unit.kelvin
TIMESTEP_FS = float(common["timestep_fs"])
FRICTION = float(common["friction_per_ps"]) / unit.picosecond
BASE_SEED = int(common["random_seed"]) if common.get("random_seed") is not None else 20260827
SOLUTE_INDICES = list(range(int(SOLUTE["n_solute_atoms"])))
#: kJ/mol/K. beta = 1/(k_B T), the single beta of the whole path.
KB_KJ = 0.008314462618
BETA = 1.0 / (KB_KJ * TEMPERATURE_K)

SCHEDULE = PATH_DEFINITION["schedule"]
OBSERVATIONS = SCHEDULE["observations"]
RECORD_FORMAT = "md-templates-runtime-record/v1"


def utc_now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def derive_seed(base, *purpose):
    """The same derivation every other generated script uses, so seeds are comparable across runs.

    Distinct per (base, purpose): two AIS paths must not share an integrator stream, or they are
    one realisation counted twice.
    """
    value = int(base)
    for part in purpose:
        for byte in str(part).encode("utf-8"):
            value = (value * 1000003 + byte) & 0xFFFFFFFF
    seed = value % (2 ** 31 - 1)
    return seed or 1


def sha256_file(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def trajectory_directory(index):
    return HERE / f"trajectory_{index:04d}"


def reduced_box_vectors(vectors):
    """Put box vectors into the reduced form OpenMM requires, without changing the lattice.

    A DCD stores a box as three lengths and three angles. MDTraj rebuilds vectors from those in the
    usual lower-triangular convention, which is a correct description of the same lattice but not
    necessarily the REDUCED one OpenMM insists on:

        openmm.OpenMMException: Periodic box vectors must be in reduced form.

    Reduction subtracts integer multiples of the earlier vectors from the later ones. That changes
    which vectors name the lattice, not the lattice itself -- the cell volume and every periodic
    image are unchanged -- so the box the path propagates in is the box the source frame had. This
    matters for a rhombic dodecahedron, which is exactly the shape this repository builds.
    """
    a, b, c = ([float(x) for x in row] for row in vectors)
    scale = round(c[1] / b[1]) if b[1] else 0.0
    c = [c[i] - scale * b[i] for i in range(3)]
    scale = round(c[0] / a[0]) if a[0] else 0.0
    c = [c[i] - scale * a[i] for i in range(3)]
    scale = round(b[0] / a[0]) if a[0] else 0.0
    b = [b[i] - scale * a[i] for i in range(3)]
    return [a, b, c]


# ---------------------------------------------------------------------------------------------
# The source ensemble
# ---------------------------------------------------------------------------------------------

def resolve_source_paths():
    """The source trajectory and topology, as an absolute path and as the configured one.

    Both are kept. The absolute path says what this execution actually read; the configured path is
    what stays true when the project is moved, which is the whole reason paths in this project are
    relative.
    """
    source = method["source"]
    configured = str(source["trajectory"])
    trajectory = Path(configured)
    if not trajectory.is_absolute():
        trajectory = (PROJECT / configured).resolve()
    if not trajectory.is_file():
        raise SystemExit(
            f"AIS.source.trajectory = {configured!r} does not resolve to a file.\n"
            f"  Looked for: {trajectory}\n"
            f"  Relative paths are resolved against the generated project, {PROJECT}.")

    configured_topology = source.get("topology")
    if configured_topology:
        topology = Path(configured_topology)
        if not topology.is_absolute():
            topology = (PROJECT / configured_topology).resolve()
        chosen = "AIS.source.topology"
    else:
        topology = INPUTS / "topology.pdb"
        chosen = "inputs/topology.pdb (AIS.source.topology was null)"
    if not topology.is_file():
        raise SystemExit(f"the source topology {topology} does not exist")
    return {"trajectory": trajectory, "trajectory_configured": configured,
            "topology": topology, "topology_choice": chosen}


def companion_record(trajectory):
    """The `resolved_run.yaml` that describes the run which wrote `trajectory`, if there is one.

    Searched in the trajectory's own directory and then upward: a cMD trajectory sits beside its
    record, a REST2 replica trajectory sits two levels below the record that covers every replica.
    Returns `(record, path)` or `(None, None)` -- absence is not an error here, it only means the
    user has to supply the frame timing and the source tau themselves.
    """
    directory = trajectory.parent
    for candidate in [directory, *list(directory.parents)[:4]]:
        record = candidate / "resolved_run.yaml"
        if record.is_file():
            try:
                return yaml.safe_load(record.read_text()), record
            except Exception:
                return None, None
    return None, None


def _replica_entry(record, trajectory):
    """The replica block of a REST2 record whose directory the trajectory lives under."""
    parts = set(trajectory.resolve().parts)
    for entry in record.get("replicas") or []:
        if str(entry.get("replica")) in parts:
            return entry
    return None


def source_frame_timing(trajectory, n_frames):
    """`(times_ps, evidence)` for every frame, or a refusal.

    A frame index is never treated as a time and a DCD header is never treated as the production
    clock. Two routes, in order:

      1. the companion `resolved_run.yaml`, which records the reporter interval and timestep the
         frames were written with -- the value recorded where it was decided;
      2. `AIS.source.first_frame_time_ps` and `frame_interval_ps`, supplied by the user.

    If neither is available the run stops and says which two fields would settle it.
    """
    source = method["source"]
    first = source.get("first_frame_time_ps")
    interval = source.get("frame_interval_ps")
    if first is not None and interval is not None:
        times = [float(first) + index * float(interval) for index in range(n_frames)]
        return times, {"route": "configured", "first_frame_time_ps": float(first),
                       "frame_interval_ps": float(interval),
                       "source": "AIS.source.first_frame_time_ps / frame_interval_ps"}

    record, record_path = companion_record(trajectory)
    if record is not None:
        block = record.get("trajectories") or {}
        entry = _replica_entry(record, trajectory)
        if entry is not None:
            block = entry.get("trajectories") or {}
        mapping = ((block.get("whole_system") or {}).get("frame_time_map")
                   if isinstance(block.get("whole_system"), dict) else None)
        if mapping:
            first = float(mapping["first_frame_time_ps"])
            interval = float(mapping["frame_interval_ps"])
            times = [first + index * interval for index in range(n_frames)]
            return times, {"route": "companion_record",
                           "record": str(record_path),
                           "first_frame_time_ps": first, "frame_interval_ps": interval,
                           "convention": mapping.get("convention"),
                           "source": f"{record_path.name} trajectories.whole_system.frame_time_map"}

    raise SystemExit(
        f"cannot establish a physical time for the frames of {trajectory.name}.\n"
        f"  No companion resolved_run.yaml with a frame_time_map was found beside or above it, "
        f"and AIS.source.first_frame_time_ps / frame_interval_ps are not set.\n"
        f"  A frame index is not a time, and this refuses to invent one. Either point "
        f"AIS.source.trajectory at a trajectory written by this repository's cMD or REST2 runtime "
        f"(which records the map), or set BOTH of:\n"
        f"      AIS.source.first_frame_time_ps   time of frame 0, in ps\n"
        f"      AIS.source.frame_interval_ps     spacing between frames, in ps")


def source_tau(trajectory):
    """The tau the source ensemble was generated at, and where that was established.

    Refused rather than assumed. A path that starts from an ensemble equilibrated at a different
    tau than `path.tau_start` is not an annealed importance sampling path at all -- the first
    "work" value would silently absorb the mismatch.
    """
    record, record_path = companion_record(trajectory)
    if record is not None:
        entry = _replica_entry(record, trajectory)
        if entry is not None and entry.get("tau") is not None:
            return float(entry["tau"]), f"{record_path} replicas[{entry.get('replica')}].tau"
        if record.get("tau") is not None:
            return float(record["tau"]), f"{record_path} tau"
    raise SystemExit(
        f"cannot establish the Hamiltonian tau of the source trajectory {trajectory.name}.\n"
        f"  No companion resolved_run.yaml recording `tau` was found beside or above it.\n"
        f"  This is refused rather than assumed to be "
        f"{PATH_DEFINITION['path']['tau_start']}: an ensemble equilibrated at a different tau "
        f"makes the first work value absorb the mismatch, silently.\n"
        f"  Point AIS.source.trajectory at a fixed-tau cMD run or a REST2 replica produced by this "
        f"repository, whose runtime record names its tau.")


def select_source_frames(times, evidence):
    """Which frames each path starts from -- deterministic, inclusive, and recorded before any run.

    Uniform over the eligible frames, without replacement by default. The window is INCLUSIVE at
    both ends, which is what `start_time_ps` and `end_time_ps` mean.
    """
    source = method["source"]
    start = float(source["start_time_ps"])
    end = float(source["end_time_ps"])
    # A tolerance of half a frame interval: a frame written at exactly `end_time_ps` must be
    # eligible, and floating-point time accumulation must not exclude it.
    tolerance = 0.5 * float(evidence.get("frame_interval_ps") or 0.0) * 1e-6
    eligible = [index for index, time in enumerate(times)
                if start - tolerance <= time <= end + tolerance]
    count = int(source["number_of_trajectories"])
    replace = bool(source["allow_sampling_with_replacement"])

    if not eligible:
        raise SystemExit(
            f"no frame of the source trajectory falls in [{start}, {end}] ps.\n"
            f"  The trajectory covers {times[0]:g} to {times[-1]:g} ps "
            f"({len(times)} frames, {evidence.get('frame_interval_ps')} ps apart, "
            f"from {evidence.get('source')}).\n"
            f"  Both bounds are inclusive; widen AIS.source.start_time_ps / end_time_ps.")
    if not replace and count > len(eligible):
        raise SystemExit(
            f"AIS.source.number_of_trajectories = {count}, but only {len(eligible)} frame(s) of "
            f"the source trajectory fall in [{start}, {end}] ps and "
            f"allow_sampling_with_replacement is false.\n"
            f"  Two independent paths starting from the same configuration are not two "
            f"independent realisations. Either widen the time window, ask for at most "
            f"{len(eligible)} trajectories, or set allow_sampling_with_replacement true and accept "
            f"that the paths share starting points.")

    # Seeded from the recorded master seed, so the same project selects the same frames on any
    # machine. numpy's Generator is used rather than `random` because its stream is versioned.
    generator = np.random.default_rng(derive_seed(BASE_SEED, "AIS", "source-selection"))
    chosen = generator.choice(len(eligible), size=count, replace=replace)
    return [int(eligible[int(i)]) for i in chosen], eligible


# ---------------------------------------------------------------------------------------------
# Devices
# ---------------------------------------------------------------------------------------------

def visible_cuda_devices():
    """The CUDA devices this process may use, honouring CUDA_VISIBLE_DEVICES."""
    raw = os.environ.get("CUDA_VISIBLE_DEVICES")
    if raw is not None:
        tokens = [t.strip() for t in raw.split(",") if t.strip()]
        return list(range(len(tokens)))
    try:
        out = subprocess.run(["nvidia-smi", "--query-gpu=index", "--format=csv,noheader"],
                             capture_output=True, text=True, timeout=15)
        if out.returncode == 0:
            return list(range(len([line for line in out.stdout.splitlines() if line.strip()])))
    except Exception:
        pass
    return []


def resolve_platform():
    """CUDA unless the configuration named something else. There is no silent CPU fallback.

    A path that quietly lands on the CPU still finishes and still writes work values -- two orders
    of magnitude later, on a machine whose GPU was simply not visible to this process.
    """
    requested = str(method["execution"]["platform"])
    forced = os.environ.get("MD_PLATFORM")
    wanted = forced or requested
    available = sorted(Platform.getPlatform(i).getName()
                       for i in range(Platform.getNumPlatforms()))
    if wanted not in available:
        raise SystemExit(
            f"platform {wanted!r} is not available in this OpenMM build (it has: "
            f"{', '.join(available)}).\n"
            f"  Set AIS.execution.platform, or ask for another platform by name for this run "
            f"only:\n      MD_PLATFORM=CPU ./run.sh")
    return wanted


def device_assignment(count):
    """Which GPU each path runs on: round-robin over the visible devices, deterministically.

    Paths sharing a device run in turn. There is no busy-device detection: if you want particular
    cards, name them in AIS.execution.gpu_devices or set CUDA_VISIBLE_DEVICES.
    """
    configured = method["execution"]["gpu_devices"]
    if configured != "auto":
        devices = [int(d) for d in configured]
    else:
        devices = visible_cuda_devices()
    if not devices:
        return {index: None for index in range(count)}, []
    return {index: devices[index % len(devices)] for index in range(count)}, devices


# ---------------------------------------------------------------------------------------------
# One switching path
# ---------------------------------------------------------------------------------------------

OBSERVATION_COLUMNS = (
    "ais_trajectory_index", "observation_index", "coordinate_frame_index",
    "source_frame_index", "source_time_ps", "protocol_step", "switching_time_ps",
    "tau", "s", "sqrt_s",
    "incremental_work_kj_mol", "cumulative_work_kj_mol", "cumulative_reduced_work",
    "temperature_kelvin", "integrator_seed", "velocity_seed", "gpu_device", "dcd_filename",
)

DCD_NAME = "observations.dcd"
CSV_NAME = "observations.csv"
COMPLETION_NAME = "completed.json"


def path_is_complete(directory):
    """A finished path, decided by its own completion record and its observation count.

    An incomplete path is never treated as complete: the record has to exist, say `completed`, and
    agree with the number of rows actually in the CSV.
    """
    marker = Path(directory) / COMPLETION_NAME
    table = Path(directory) / CSV_NAME
    if not marker.is_file() or not table.is_file():
        return False, "no completion record"
    try:
        record = json.loads(marker.read_text())
    except Exception as error:
        return False, f"{COMPLETION_NAME} is unreadable ({type(error).__name__})"
    if record.get("status") != "completed":
        return False, f"completion record says {record.get('status')!r}"
    rows = sum(1 for _ in csv.DictReader(table.open()))
    expected = int(SCHEDULE["number_of_observations"])
    if rows != expected:
        return False, f"{rows} observation row(s) on disk, {expected} expected"
    return True, f"{rows} observations recorded"


def run_one_path(index, plan):
    """Propagate one AIS path from its source frame to tau_end, writing coordinates and work."""
    directory = trajectory_directory(index)
    entry = plan["trajectories"][index]
    device = entry["gpu_device"]

    done, why = path_is_complete(directory)
    if done:
        print(f"[AIS {index:04d}] already complete: {why}. Nothing was run.", flush=True)
        return {"status": "skipped", "reason": why}
    if directory.exists() and any(directory.iterdir()):
        # Never append a second path to an existing DCD: the file would look like one continuous
        # trajectory and would not be. Replacing an INCOMPLETE directory is safe and is what
        # happens; a complete one was skipped above and never reaches here.
        print(f"[AIS {index:04d}] replacing an incomplete directory ({why})", flush=True)
        shutil.rmtree(directory)
    directory.mkdir(parents=True, exist_ok=True)

    log = []

    def say(message):
        line = f"[AIS {index:04d}] {message}"
        print(line, flush=True)
        log.append(line)

    platform_name = plan["platform"]
    say(f"platform {platform_name}" + (f", CUDA device {device}" if device is not None else ""))

    base = XmlSerializer.deserialize((INPUTS / "system.xml").read_text())
    barostats = [base.getForce(i).__class__.__name__ for i in range(base.getNumForces())
                 if "Barostat" in base.getForce(i).__class__.__name__]
    if barostats:
        raise SystemExit(
            f"the prepared System carries {barostats}, but AIS switches at FIXED VOLUME and adds "
            f"no barostat. Remove it, or rebuild the system with `md-openmm sys-gen`.")

    excluded = SOLUTE["rest2"]["omega_excluded_bonds"] if PATH_DEFINITION["path"][
        "omega_exclusion"] else []
    switcher = TauSwitcher(base, SOLUTE_INDICES, excluded)
    taus = SCHEDULE["taus"]
    system = switcher.prepared_system(taus[0])

    integrator = LangevinMiddleIntegrator(TEMPERATURE, FRICTION, TIMESTEP_FS * unit.femtoseconds)
    integrator.setRandomNumberSeed(int(entry["integrator_seed"]))
    properties = {}
    if platform_name == "CUDA":
        properties = {"Precision": "mixed"}
        if device is not None:
            properties["DeviceIndex"] = str(device)
    platform = Platform.getPlatformByName(platform_name)
    topology = PDBFile(str(plan["source"]["topology"])).topology
    from openmm.app import Simulation

    simulation = Simulation(topology, system, integrator, platform, properties)

    positions = np.array(entry["positions_nm"])
    if not implicit:
        # The source frame's own box, in the reduced form OpenMM requires. Fixed volume: nothing
        # changes it for the rest of the path.
        simulation.context.setPeriodicBoxVectors(*reduced_box_vectors(entry["box_vectors_nm"]))
    simulation.context.setPositions(positions * unit.nanometer)
    # DCD carries no velocities, so the source frame supplies coordinates only and the momenta are
    # drawn fresh from the Maxwell-Boltzmann distribution at the common temperature. The seed is
    # this path's own, recorded, and different from every other path's.
    simulation.context.setVelocitiesToTemperature(TEMPERATURE, int(entry["velocity_seed"]))
    say(f"source frame {entry['source_frame_index']} at {entry['source_time_ps']:g} ps, "
        f"tau {taus[0]:g}, seeds integrator={entry['integrator_seed']} "
        f"velocity={entry['velocity_seed']}")

    active = sum(1 for i in range(system.getNumForces())
                 if "Barostat" in system.getForce(i).__class__.__name__)
    say(f"{active} barostat(s) in the switching System (fixed volume; no pV work is included)")

    handle = (directory / DCD_NAME).open("wb")
    dcd = DCDFile(handle, topology, TIMESTEP_FS * unit.femtoseconds, firstStep=0,
                  interval=int(SCHEDULE["steps_per_observation"]))
    rows = []
    interval = int(SCHEDULE["parameter_update_interval_steps"])
    per_observation = int(SCHEDULE["updates_per_observation"])

    def energy():
        return simulation.context.getState(getEnergy=True).getPotentialEnergy().value_in_unit(
            unit.kilojoule_per_mole)

    def observe(observation, cumulative, incremental):
        state = simulation.context.getState(getPositions=True, enforcePeriodicBox=False)
        dcd.writeModel(state.getPositions(),
                       periodicBoxVectors=(None if implicit
                                           else state.getPeriodicBoxVectors()))
        rows.append({
            "ais_trajectory_index": index,
            "observation_index": observation["observation_index"],
            # Written in lockstep with the DCD, so the k-th row IS the k-th frame by construction.
            "coordinate_frame_index": len(rows),
            "source_frame_index": entry["source_frame_index"],
            "source_time_ps": entry["source_time_ps"],
            "protocol_step": observation["protocol_step"],
            "switching_time_ps": observation["switching_time_ps"],
            "tau": observation["tau"],
            "s": observation["s"],
            "sqrt_s": observation["sqrt_s"],
            "incremental_work_kj_mol": incremental,
            "cumulative_work_kj_mol": cumulative,
            "cumulative_reduced_work": BETA * cumulative,
            "temperature_kelvin": TEMPERATURE_K,
            "integrator_seed": entry["integrator_seed"],
            "velocity_seed": entry["velocity_seed"],
            "gpu_device": "" if device is None else device,
            "dcd_filename": DCD_NAME,
        })

    # Observation 0 is the SOURCE configuration under the source Hamiltonian, before any parameter
    # change and before any propagation. Its cumulative work is exactly zero by definition.
    cumulative = 0.0
    since_observation = 0.0
    observe(OBSERVATIONS[0], 0.0, 0.0)
    say(f"observation 0: tau {taus[0]:g}, work 0")

    for update in range(int(SCHEDULE["number_of_updates"])):
        # delta_W = U(tau_{j+1}, x_j) - U(tau_j, x_j): the parameters move at frozen coordinates.
        before = energy()
        switcher.set_tau(simulation.context, system, taus[update + 1])
        after = energy()
        increment = after - before
        cumulative += increment
        since_observation += increment
        # ...and only then does the configuration propagate under the new Hamiltonian.
        simulation.step(interval)
        if (update + 1) % per_observation == 0:
            observation = OBSERVATIONS[(update + 1) // per_observation]
            observe(observation, cumulative, since_observation)
            since_observation = 0.0

    state = simulation.context.getState(getPositions=True, getVelocities=True,
                                        getParameters=True, enforcePeriodicBox=False)
    (directory / "final_state.xml").write_text(XmlSerializer.serialize(state), encoding="utf-8")
    handle.close()

    with (directory / CSV_NAME).open("w", newline="") as table:
        writer = csv.DictWriter(table, fieldnames=list(OBSERVATION_COLUMNS))
        writer.writeheader()
        writer.writerows(rows)

    say(f"observation {rows[-1]['observation_index']}: tau {rows[-1]['tau']:g}, "
        f"cumulative work {cumulative:.6f} kJ/mol "
        f"(reduced {BETA * cumulative:.6f})")
    say(f"complete: {len(rows)} observations, {SCHEDULE['total_steps']} integration steps")
    (directory / "stdout.log").write_text("\n".join(log) + "\n", encoding="utf-8")

    completion = {
        "status": "completed",
        "ais_trajectory_index": index,
        "observations": len(rows),
        "total_work_kj_mol": cumulative,
        "total_reduced_work": BETA * cumulative,
        "finished_utc": utc_now(),
        "platform": platform_name,
        "gpu_device": device,
        "integrator_seed": entry["integrator_seed"],
        "velocity_seed": entry["velocity_seed"],
    }
    (directory / COMPLETION_NAME).write_text(json.dumps(completion, indent=2) + "\n",
                                             encoding="utf-8")
    return completion


# ---------------------------------------------------------------------------------------------
# The plan, shared by the parent and every worker
# ---------------------------------------------------------------------------------------------

PLAN_NAME = "_ais_plan.json"


def build_plan():
    """Everything decided before any dynamics: which frames, which seeds, which device.

    Written to disk so each worker process reads the SAME plan the parent recorded, rather than
    re-deriving it and possibly disagreeing.
    """
    import mdtraj

    paths = resolve_source_paths()
    platform_name = resolve_platform()

    reference = PDBFile(str(paths["topology"]))
    frames = mdtraj.load(str(paths["trajectory"]), top=str(paths["topology"]))
    if frames.n_atoms != reference.topology.getNumAtoms():
        raise SystemExit(
            f"the source trajectory has {frames.n_atoms} atoms but {paths['topology'].name} has "
            f"{reference.topology.getNumAtoms()}. AIS switches the System built from "
            f"inputs/topology.pdb, so the two must be the same system in the same order.")
    prepared = PDBFile(str(INPUTS / "topology.pdb"))
    if reference.topology.getNumAtoms() != prepared.topology.getNumAtoms():
        raise SystemExit(
            f"{paths['topology']} has {reference.topology.getNumAtoms()} atoms but the prepared "
            f"inputs/topology.pdb has {prepared.topology.getNumAtoms()}.")
    mismatched = [(a.name, b.name) for a, b in
                  zip(reference.topology.atoms(), prepared.topology.atoms()) if a.name != b.name]
    if mismatched:
        raise SystemExit(
            f"the source topology and inputs/topology.pdb disagree on atom order: "
            f"{len(mismatched)} atom name(s) differ, first {mismatched[0]}. The System's parameters "
            f"are per index, so a reordered trajectory would be scaled atom-by-atom wrongly.")

    times, timing = source_frame_timing(paths["trajectory"], frames.n_frames)
    tau_source, tau_evidence = source_tau(paths["trajectory"])
    tau_start = float(PATH_DEFINITION["path"]["tau_start"])
    if abs(tau_source - tau_start) > 1e-9:
        raise SystemExit(
            f"the source trajectory was produced at tau = {tau_source} ({tau_evidence}), but "
            f"AIS.path.tau_start is {tau_start}.\n"
            f"  The path must begin in the ensemble it anneals away from. Set tau_start to "
            f"{tau_source}, or point AIS.source.trajectory at an ensemble equilibrated at "
            f"{tau_start}.")

    if not implicit and frames.unitcell_vectors is None:
        raise SystemExit(
            f"{paths['trajectory'].name} carries no periodic box vectors, but this is an "
            f"explicit-solvent system and each path keeps the box of the frame it starts from. "
            f"A DCD written by this repository's cMD or REST2 runtime has them.")

    selected, eligible = select_source_frames(times, timing)
    devices, device_list = device_assignment(len(selected))

    trajectories = []
    for index, frame in enumerate(selected):
        trajectories.append({
            "ais_trajectory_index": index,
            "directory": trajectory_directory(index).name,
            "source_frame_index": int(frame),
            "source_time_ps": float(times[frame]),
            "integrator_seed": derive_seed(BASE_SEED, "AIS", index, "integrator"),
            "velocity_seed": derive_seed(BASE_SEED, "AIS", index, "velocities"),
            "gpu_device": devices[index],
            "positions_nm": frames.xyz[frame].astype(float).tolist(),
            "box_vectors_nm": (None if implicit
                               else frames.unitcell_vectors[frame].astype(float).tolist()),
        })
        if not implicit:
            source_box = frames.unitcell_vectors[frame].astype(float)
            reduced = np.array(reduced_box_vectors(source_box.tolist()))
            before = abs(float(np.linalg.det(source_box)))
            after = abs(float(np.linalg.det(reduced)))
            if abs(before - after) > 1e-9 * max(1.0, before):
                raise SystemExit(
                    f"reducing the box vectors of source frame {frame} changed the cell volume "
                    f"({before:.9f} -> {after:.9f} nm^3). Reduction renames the lattice vectors "
                    f"and must not change the lattice; refusing to propagate in a box that is not "
                    f"the one the source frame had.")
            trajectories[-1]["box_volume_nm3"] = after

    return {
        "platform": platform_name,
        "devices": device_list,
        "source": {
            "trajectory": str(paths["trajectory"]),
            "trajectory_configured": paths["trajectory_configured"],
            "trajectory_sha256": sha256_file(paths["trajectory"]),
            "topology": str(paths["topology"]),
            "topology_choice": paths["topology_choice"],
            "n_frames": int(frames.n_frames),
            "n_atoms": int(frames.n_atoms),
            "frame_timing": timing,
            "first_time_ps": float(times[0]),
            "last_time_ps": float(times[-1]),
            "window_ps": [float(method["source"]["start_time_ps"]),
                          float(method["source"]["end_time_ps"])],
            "window_is_inclusive": True,
            "eligible_frames": len(eligible),
            "eligible_frame_range": [int(eligible[0]), int(eligible[-1])],
            "selection": method["source"]["selection"],
            "with_replacement": bool(method["source"]["allow_sampling_with_replacement"]),
            "selection_seed": derive_seed(BASE_SEED, "AIS", "source-selection"),
            "tau": tau_source,
            "tau_evidence": tau_evidence,
        },
        "trajectories": trajectories,
    }


def write_selected_frames(plan):
    """The deterministic selection, on disk BEFORE any dynamics runs."""
    with (HERE / "selected_initial_frames.csv").open("w", newline="") as table:
        writer = csv.DictWriter(table, fieldnames=[
            "ais_trajectory_index", "source_frame_index", "source_time_ps", "source_tau",
            "integrator_seed", "velocity_seed", "gpu_device", "directory",
            "source_trajectory", "selection", "selection_seed"])
        writer.writeheader()
        for entry in plan["trajectories"]:
            writer.writerow({
                "ais_trajectory_index": entry["ais_trajectory_index"],
                "source_frame_index": entry["source_frame_index"],
                "source_time_ps": entry["source_time_ps"],
                "source_tau": plan["source"]["tau"],
                "integrator_seed": entry["integrator_seed"],
                "velocity_seed": entry["velocity_seed"],
                "gpu_device": "" if entry["gpu_device"] is None else entry["gpu_device"],
                "directory": entry["directory"],
                "source_trajectory": plan["source"]["trajectory_configured"],
                "selection": plan["source"]["selection"],
                "selection_seed": plan["source"]["selection_seed"],
            })


def environment_versions():
    versions = {"python": sys.version.split()[0]}
    for name in ("openmm", "mdtraj", "numpy", "yaml"):
        try:
            module = __import__(name)
            if name == "openmm":
                versions[name] = module.version.version
                versions["openmm_short_version"] = module.version.short_version
            else:
                versions[name] = str(getattr(module, "__version__", "unknown"))
        except Exception as error:
            versions[name] = f"unavailable ({type(error).__name__})"
    return versions


LIMITATIONS = [
    "forward path only: tau_start -> tau_end. The reverse path is not implemented.",
    "no mid-path restart. A path that is interrupted is rerun from its source frame; an "
    "incomplete trajectory directory is replaced, never appended to.",
    "fixed volume. No barostat is active during switching and no pressure-volume term is included "
    "in the work, even when the source ensemble was NPT.",
    "DCD carries no velocities, so each path draws fresh Maxwell-Boltzmann momenta at the common "
    "temperature using its own recorded seed.",
    "no free-energy estimator. The work columns are the input a Hummer-Szabo or Jarzynski analysis "
    "would consume; computing one is not part of this runtime.",
]


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--worker", type=int, default=None,
                        help="run exactly one AIS path in this process, by index")
    args = parser.parse_args(argv)

    if args.worker is not None:
        plan = json.loads((HERE / PLAN_NAME).read_text())
        run_one_path(args.worker, plan)
        return 0

    started = utc_now()
    plan = build_plan()
    (HERE / PLAN_NAME).write_text(json.dumps(plan), encoding="utf-8")
    write_selected_frames(plan)

    count = len(plan["trajectories"])
    devices = plan["devices"]
    concurrency = max(1, min(count, len(devices))) if devices else 1
    print(f"[AIS] {count} independent path(s), tau {PATH_DEFINITION['path']['tau_start']} -> "
          f"{PATH_DEFINITION['path']['tau_end']}, "
          f"{SCHEDULE['number_of_updates']} switching update(s) over "
          f"{SCHEDULE['total_steps']} steps, {SCHEDULE['number_of_observations']} observations",
          flush=True)
    print(f"[AIS] source {plan['source']['trajectory_configured']} at tau {plan['source']['tau']}, "
          f"{plan['source']['eligible_frames']} eligible frame(s) in "
          f"{plan['source']['window_ps']} ps (inclusive)", flush=True)
    print(f"[AIS] platform {plan['platform']}, device(s) {devices or 'none'}, "
          f"{concurrency} path(s) at a time; paths sharing a device run in turn", flush=True)

    # Isolated worker PROCESSES, not threads: one OpenMM Context per process, so a Context is never
    # shared across devices and a crash in one path cannot take the others with it.
    results, pending = {}, list(range(count))
    running = {}
    failures = []
    while pending or running:
        while pending and len(running) < concurrency:
            index = pending.pop(0)
            command = [sys.executable, str(HERE / "run.py"), "--worker", str(index)]
            running[index] = subprocess.Popen(command, cwd=str(HERE))
        finished = [index for index, process in running.items() if process.poll() is not None]
        if not finished:
            next(iter(running.values())).wait()
            continue
        for index in finished:
            code = running.pop(index).returncode
            directory = trajectory_directory(index)
            complete, why = path_is_complete(directory)
            if code == 0 and complete:
                results[index] = json.loads((directory / COMPLETION_NAME).read_text())
            else:
                failures.append({"ais_trajectory_index": index, "exit_code": code, "reason": why})

    completed = sorted(results)
    failed = sorted(entry["ais_trajectory_index"] for entry in failures)
    total_work = [results[i]["total_work_kj_mol"] for i in completed]

    record = {
        "format": RECORD_FORMAT,
        "record_kind": "ais_run",
        "started_utc": started,
        "finished_utc": utc_now(),
        "status": "completed" if not failed else "incomplete",
        "implementation": CONFIG.get("provenance"),
        "command": list(sys.argv),
        "environment": environment_versions(),
        "platform": plan["platform"],
        "gpu_devices": devices,
        "path": PATH_DEFINITION["path"],
        "schedule": {key: SCHEDULE[key] for key in
                     ("total_steps", "number_of_updates", "number_of_observations",
                      "updates_per_observation", "steps_per_observation",
                      "parameter_update_interval_steps", "timestep_fs")},
        "work_convention": PATH_DEFINITION["work_convention"],
        "ensemble": PATH_DEFINITION["ensemble"],
        "thermodynamics": {
            "temperature_kelvin": TEMPERATURE_K,
            "beta_kj_mol_inverse": BETA,
            "constant_along_path": True,
            "note": "Hamiltonian switching at constant temperature, not temperature annealing",
        },
        "source": plan["source"],
        "trajectories": [
            {**{key: entry[key] for key in
                ("ais_trajectory_index", "directory", "source_frame_index", "source_time_ps",
                 "integrator_seed", "velocity_seed", "gpu_device")},
             "status": ("completed" if entry["ais_trajectory_index"] in results else "failed"),
             "total_work_kj_mol": results.get(entry["ais_trajectory_index"], {}).get(
                 "total_work_kj_mol"),
             "total_reduced_work": results.get(entry["ais_trajectory_index"], {}).get(
                 "total_reduced_work")}
            for entry in plan["trajectories"]],
        "completed_trajectory_indices": completed,
        "failed_trajectory_indices": failed,
        "pending_trajectory_indices": [],
        "failures": failures,
        "limitations": LIMITATIONS,
    }
    (HERE / "resolved_run.yaml").write_text(
        yaml.safe_dump(record, sort_keys=False, default_flow_style=False), encoding="utf-8")

    provenance = {
        "format": "md-templates-ais-provenance/v1",
        "created_utc": utc_now(),
        "implementation": CONFIG.get("provenance"),
        "environment": environment_versions(),
        "parent_system": {
            "inputs_folder": CONFIG["paths"]["inputs_folder"],
            "input_hashes": {name: sha256_file(INPUTS / name)
                             for name in ("system.xml", "topology.pdb", "solute.yaml",
                                          "initial_state.xml", "resolved_sys.config.yaml")
                             if (INPUTS / name).is_file()},
            "forcefield": _forcefield_identity(),
        },
        "source_trajectory": plan["source"],
        "path": PATH_DEFINITION["path"],
        "schedule": SCHEDULE,
        "work_convention": PATH_DEFINITION["work_convention"],
        "ensemble": PATH_DEFINITION["ensemble"],
        "seeds": {"base": BASE_SEED,
                  "source_selection": plan["source"]["selection_seed"],
                  "per_trajectory": {entry["ais_trajectory_index"]:
                                     {"integrator": entry["integrator_seed"],
                                      "velocities": entry["velocity_seed"]}
                                     for entry in plan["trajectories"]}},
        "gpu_assignment": {entry["ais_trajectory_index"]: entry["gpu_device"]
                           for entry in plan["trajectories"]},
        "completed_trajectory_indices": completed,
        "failed_trajectory_indices": failed,
        "pending_trajectory_indices": [],
        "limitations": LIMITATIONS,
    }
    (HERE / "provenance.yaml").write_text(
        yaml.safe_dump(provenance, sort_keys=False, default_flow_style=False), encoding="utf-8")

    (HERE / PLAN_NAME).unlink(missing_ok=True)
    if total_work:
        print(f"[AIS] {len(completed)}/{count} path(s) complete; total work "
              f"{min(total_work):.3f} to {max(total_work):.3f} kJ/mol", flush=True)
    if failed:
        print(f"[AIS] FAILED path(s): {failed}. See resolved_run.yaml.", flush=True)
        return 1
    return 0


def _forcefield_identity():
    """What the System was parameterised with, copied from the prepared inputs."""
    record = INPUTS / "forcefield.json"
    if not record.is_file():
        return None
    try:
        data = json.loads(record.read_text())
    except Exception:
        return None
    return {key: data.get(key) for key in ("route", "solvation", "protein", "ligand", "water",
                                           "nonbonded", "constraints")}


if __name__ == "__main__":
    raise SystemExit(main())
