#!/usr/bin/env python
"""Annealed importance sampling along the REST2 tau path. Generated by md-openmm; edit freely.

Each AIS trajectory is one independent switching path: a configuration is drawn from an existing
equilibrium ensemble at `tau_start`, velocities are assigned fresh, and the Hamiltonian is then
annealed to `tau_end` while the coordinates propagate. The nonequilibrium work that switching costs
is accumulated and written beside the coordinates it belongs to.

    inputs  : the prepared system in inputs/, and a source trajectory you already ran
    outputs : trajectory_NNNN/{observations.dcd, observations.csv, final_state.xml, stdout.log}
              selected_initial_frames.csv, resolved_run.yaml, provenance.yaml

    ./run.sh                     run every path, spread over the visible CUDA devices
    python run.py --worker 3     run one path in this process (what run.py spawns internally)

WHAT THIS DOES, AND WHAT IT DOES NOT

The Hamiltonian actually changes: at each update the force parameters are rewritten through the
same REST2 decomposition a static rung is built with (`rest2_scaling.TauSwitcher`), not interpolated
between two endpoint energies. `s = (1 - tau)^2` scales solute-solute terms, `sqrt(s) = 1 - tau`
scales solute-environment terms, and torsions about an omega bond are left alone -- the same rules,
the same omega bond list from inputs/solute.yaml, that cMD and REST2 use.

Temperature and beta are constant along the path. This is Hamiltonian switching, not temperature
annealing.

Work uses the discrete nonequilibrium convention

    delta_W_j = U(tau_{j+1}, x_j) - U(tau_j, x_j)

-- the parameters change first, at frozen coordinates, and the configuration then propagates under
the new Hamiltonian. Physical work is kJ/mol; reduced work is beta*W.

Switching is at FIXED VOLUME. There is no barostat in the System and none is added, so an explicit
source frame keeps the box it came from. An NPT equilibrium ensemble may seed these paths, but the
pressure-volume contribution to the work is NOT part of this implementation.

This is forward-only, has no mid-path restart, and computes no free-energy estimator. The work
values it writes are the input a Hummer-Szabo or Jarzynski analysis would consume; producing that
estimate is somebody else's job and this file does not pretend to do it.

Every path is stored in its own directory with its own DCD. They are independent realisations and
concatenating them would produce a file that looks like one continuous trajectory and is not.

This script imports OpenMM, PyYAML, NumPy and MDTraj -- never `md_templates`.
"""
import argparse
import csv
import hashlib
import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import yaml
from openmm import LangevinMiddleIntegrator, Platform, XmlSerializer, unit
from openmm.app import DCDFile, PDBFile

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent))
import preflight                                                     # noqa: E402
from md_stages import stage_config_sha256, stage_invariant_sha256    # noqa: E402
from rest2_scaling import TauSwitcher, scaling_for_tau                # noqa: E402


def _ais_solute_solute_scale(tau):
    """AIS records `s` and `sqrt_s` in its own switching observations, and datasets
    written with those columns exist on disk. That schema is AIS's, not REST2's, and
    renaming it would break readers of data this repository already produced -- so it
    stays, taking its value from the one REST2 entry point."""
    return scaling_for_tau(tau)[0]


PROJECT = HERE.parent
CONFIG = yaml.safe_load((PROJECT / "md.config.yaml").read_text())
PATH_DEFINITION = yaml.safe_load((HERE / "path_definition.yaml").read_text())
#: The resolved production request, written by `md-gen`. The shared preflight recomputes it from
#: the current configuration and refuses a changed one before any Context exists. Absent in a
#: project generated before AIS carried a stage document, and the preflight skips rather than
#: guessing in that case.
STAGE = (yaml.safe_load((HERE / "stage.yaml").read_text())
         if (HERE / "stage.yaml").is_file() else None)
INPUTS = (PROJECT / CONFIG["paths"]["inputs_folder"]).resolve()
SOLUTE = yaml.safe_load((INPUTS / "solute.yaml").read_text())

common = CONFIG["common"]
method = CONFIG["AIS"]
implicit = bool(PATH_DEFINITION["ensemble"]["implicit_solvent"])

TEMPERATURE_K = float(common["temperature_kelvin"])
TEMPERATURE = TEMPERATURE_K * unit.kelvin
TIMESTEP_FS = float(common["timestep_fs"])
FRICTION = float(common["friction_per_ps"]) / unit.picosecond
BASE_SEED = int(common["random_seed"]) if common.get("random_seed") is not None else 20260827
SOLUTE_INDICES = list(range(int(SOLUTE["n_solute_atoms"])))
#: kJ/mol/K. beta = 1/(k_B T), the single beta of the whole path.
KB_KJ = 0.008314462618
BETA = 1.0 / (KB_KJ * TEMPERATURE_K)

SCHEDULE = PATH_DEFINITION["schedule"]
OBSERVATIONS = SCHEDULE["observations"]
RECORD_FORMAT = "md-templates-runtime-record/v1"


def utc_now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def relative_to_project(path):
    """A path as written into a record: relative to the generated project, never absolute."""
    path = Path(path).resolve()
    try:
        return str(path.relative_to(PROJECT))
    except ValueError:
        return str(path)


def derive_seed(base, *purpose):
    """The same derivation every other generated script uses, so seeds are comparable across runs.

    Distinct per (base, purpose): two AIS paths must not share an integrator stream, or they are
    one realisation counted twice.
    """
    value = int(base)
    for part in purpose:
        for byte in str(part).encode("utf-8"):
            value = (value * 1000003 + byte) & 0xFFFFFFFF
    seed = value % (2 ** 31 - 1)
    return seed or 1


def sha256_file(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def trajectory_directory(index):
    return HERE / f"trajectory_{index:04d}"


def reduced_box_vectors(vectors):
    """Delegates to the shared helper: reduced form for OpenMM, same lattice."""
    return source_ensemble.reduced_box_vectors(vectors)


# ---------------------------------------------------------------------------------------------
# The source ensemble
#
# The rules for reading configurations out of an equilibrium production run live in
# `source_ensemble.py`, which rREST2 uses too. They were established here and are not restated:
# a second implementation is a second thing that can be wrong, and its wrongness would be silent.
# The functions below build the request AIS's configuration describes and delegate.
#
# `source_ensemble.derive_seed` is deliberately this file's own multiplicative derivation, and the
# selection stream is still ("AIS", "source-selection"), so every existing AIS project selects the
# configurations it always did.
# ---------------------------------------------------------------------------------------------

import source_ensemble


def source_request(*, count=None):
    """AIS's configuration, expressed as the shared source-ensemble request."""
    source = method["source"]
    return source_ensemble.SourceRequest(
        project=PROJECT,
        prepared_topology=INPUTS / "topology.pdb",
        trajectory=source["trajectory"],
        topology=source.get("topology"),
        start_time_ps=source["start_time_ps"],
        end_time_ps=source["end_time_ps"],
        count=int(source["number_of_trajectories"] if count is None else count),
        allow_replacement=bool(source["allow_sampling_with_replacement"]),
        seed=BASE_SEED,
        implicit=implicit,
        required_tau=float(PATH_DEFINITION["path"]["tau_start"]),
        declared_tau=source.get("source_tau"),
        first_frame_time_ps=source.get("first_frame_time_ps"),
        frame_interval_ps=source.get("frame_interval_ps"),
        field_prefix="AIS.source",
        replacement_rationale=("Two independent paths starting from the same configuration are "
                               "not two independent realisations."),
        chunk_frames=SOURCE_CHUNK_FRAMES,
        purpose="AIS",
        selection_purpose=("AIS", "source-selection"),
    )


def resolve_source_paths():
    """Delegates to the shared source-ensemble helper. See `source_ensemble.py`."""
    try:
        return source_ensemble.resolve_source_paths(source_request())
    except source_ensemble.SourceError as failure:
        raise SystemExit(str(failure)) from None


def companion_record(trajectory):
    """Delegates to the shared helper: the `resolved_run.yaml` describing the writing run."""
    return source_ensemble.companion_record(trajectory)


def _replica_entry(record, trajectory):
    """Delegates to the shared helper."""
    return source_ensemble._replica_entry(record, trajectory)


def source_frame_timing(trajectory, n_frames):
    """Delegates to the shared helper. A frame index is never a time; a DCD header never a clock."""
    try:
        return source_ensemble.source_frame_timing(source_request(), trajectory, n_frames)
    except source_ensemble.SourceError as failure:
        raise SystemExit(str(failure)) from None


def source_tau(trajectory):
    """Delegates to the shared helper. NEVER inferred from a directory name such as cMD_tau0p5."""
    try:
        return source_ensemble.source_tau(source_request(), trajectory)
    except source_ensemble.SourceError as failure:
        raise SystemExit(str(failure)) from None


def select_source_frames(times, evidence):
    """Delegates to the shared helper, on a request rebuilt from the CURRENT configuration.

    Rebuilt each call rather than cached: the window and the trajectory count are configuration,
    and a caller that changes them expects the next selection to honour the change.
    """
    try:
        return source_ensemble.select_source_frames(source_request(), times, evidence)
    except source_ensemble.SourceError as failure:
        raise SystemExit(str(failure)) from None


# ---------------------------------------------------------------------------------------------
# Devices
# ---------------------------------------------------------------------------------------------

def visible_cuda_devices():
    """The CUDA devices this process may use, honouring CUDA_VISIBLE_DEVICES."""
    raw = os.environ.get("CUDA_VISIBLE_DEVICES")
    if raw is not None:
        tokens = [t.strip() for t in raw.split(",") if t.strip()]
        return list(range(len(tokens)))
    try:
        out = subprocess.run(["nvidia-smi", "--query-gpu=index", "--format=csv,noheader"],
                             capture_output=True, text=True, timeout=15)
        if out.returncode == 0:
            return list(range(len([line for line in out.stdout.splitlines() if line.strip()])))
    except Exception:
        pass
    return []


def resolve_platform():
    """CUDA unless the configuration named something else. There is no silent CPU fallback.

    A path that quietly lands on the CPU still finishes and still writes work values -- two orders
    of magnitude later, on a machine whose GPU was simply not visible to this process.
    """
    requested = str(method["execution"]["platform"])
    forced = os.environ.get("MD_PLATFORM")
    wanted = forced or requested
    available = sorted(Platform.getPlatform(i).getName()
                       for i in range(Platform.getNumPlatforms()))
    if wanted not in available:
        raise SystemExit(
            f"platform {wanted!r} is not available in this OpenMM build (it has: "
            f"{', '.join(available)}).\n"
            f"  Set AIS.execution.platform, or ask for another platform by name for this run "
            f"only:\n      MD_PLATFORM=CPU ./run.sh")
    return wanted


def device_assignment(count):
    """Which GPU each path runs on: round-robin over the visible devices, deterministically.

    Paths sharing a device run in turn. There is no busy-device detection: if you want particular
    cards, name them in AIS.execution.gpu_devices or set CUDA_VISIBLE_DEVICES.
    """
    configured = method["execution"]["gpu_devices"]
    if configured != "auto":
        devices = [int(d) for d in configured]
    else:
        devices = visible_cuda_devices()
    if not devices:
        return {index: None for index in range(count)}, []
    return {index: devices[index % len(devices)] for index in range(count)}, devices


# ---------------------------------------------------------------------------------------------
# One switching path
# ---------------------------------------------------------------------------------------------

OBSERVATION_COLUMNS = (
    "ais_trajectory_index", "observation_index", "coordinate_frame_index",
    "source_frame_index", "source_time_ps", "protocol_step", "switching_time_ps",
    "tau", "s", "sqrt_s",
    "incremental_work_kj_mol", "cumulative_work_kj_mol", "cumulative_reduced_work",
    "temperature_kelvin", "integrator_seed", "velocity_seed", "gpu_device", "dcd_filename",
)

DCD_NAME = "observations.dcd"
CSV_NAME = "observations.csv"
COMPLETION_NAME = "completed.json"


def dcd_header_frames(path):
    """What a DCD's header CLAIMS. Bounded: 100 bytes, never the coordinate blocks.

    A first signal only. The header survives an interrupted write intact, so a file can claim the
    right count while its last coordinate record is short or missing. Never treat this as proof of
    completeness -- `validate_generated_dcd` is what establishes that.
    """
    import struct

    with open(path, "rb") as handle:
        if struct.unpack("<i", handle.read(4))[0] != 84:
            raise ValueError(f"{path}: not a little-endian DCD")
        control = handle.read(84)
    return struct.unpack("<i", control[4:8])[0]


def validate_generated_dcd(path, expected, *, topology, need_box, what):
    """Physically validate a SMALL GENERATED DCD by reading every frame out of it.

    Returns `(True, detail)` or `(False, reason)`.

    The header is not evidence. An interrupted write leaves `NSET` at the value the writer intended
    and the final coordinate record short, so a file that claims 21 frames can hold 20 and a bit.
    The only way to know is to read them, which is affordable here and ONLY here: these files hold
    one frame per path, or the configured observations. Never point this at a production
    trajectory -- that is what the bounded `iterload` survey is for.
    """
    import mdtraj

    path = Path(path)
    if not path.is_file():
        return False, f"{what} is missing"
    try:
        claimed = dcd_header_frames(path)
    except Exception as error:
        return False, f"{what} is not a readable DCD ({type(error).__name__}: {error})"

    frames = 0
    last = None
    try:
        for piece in mdtraj.iterload(str(path), top=str(topology), chunk=SOURCE_CHUNK_FRAMES):
            if not np.all(np.isfinite(piece.xyz)):
                return False, f"{what} frame {frames} holds non-finite coordinates"
            if need_box:
                boxes = piece.unitcell_vectors
                if boxes is None:
                    return False, (f"{what} carries no periodic box vectors, and this is an "
                                   f"explicit-solvent system")
                if not np.all(np.isfinite(boxes)):
                    return False, f"{what} frame {frames} holds non-finite box vectors"
                volumes = np.abs(np.linalg.det(boxes))
                if not np.all(volumes > 0):
                    return False, f"{what} frame {frames} has a degenerate periodic box"
            frames += int(piece.n_frames)
            last = piece
    except Exception as error:
        # The characteristic signature of a physically truncated file: the header promised more
        # than the bytes deliver, and the reader runs off the end of the last record.
        return False, (f"{what} claims {claimed} frame(s) but only {frames} could be read "
                       f"before {type(error).__name__}: {error} -- truncated, not short")

    if frames != expected:
        kind = ("truncated, not short" if frames < expected else "longer than the schedule")
        return False, (f"{what} holds {frames} readable frame(s), {expected} expected "
                       f"(header claims {claimed}) -- {kind}")
    if claimed != expected:
        return False, (f"{what} reads {frames} frame(s) but its header claims {claimed}")
    if last is None or int(last.n_frames) == 0:
        return False, f"{what} ended before its final frame could be read"
    return True, f"{frames} frame(s), every one read"


def path_is_complete(directory, index=None):
    """A finished path, or the exact reason it is not one.

    EVERY artifact required to skip the run has to agree, because each of them alone is a way for
    an unfinished path to look finished:

      * `completed.json` says completed -- but a JSON file survives a killed worker;
      * `observations.csv` has the expected rows -- but the CSV is written before the DCD is
        closed on some failure paths;
      * `observations.dcd` EXISTS -- a missing DCD with a healthy JSON and CSV is exactly the
        case this must not skip;
      * the DCD holds exactly the expected frames AND THEY CAN BE READ -- a truncated file is not
        a short one, and its header still claims the count the writer intended;
      * every CSV coordinate index maps one-to-one onto a DCD frame;
      * the recorded schedule and trajectory index are the ones being asked for now -- a path
        completed against a different switching duration is not this path.

    Bounded, but no longer header-only: `validate_generated_dcd` READS every frame of this path's
    `observations.dcd` with `mdtraj.iterload` in bounded chunks, checking the exact count, a
    readable final frame, finite coordinates and a non-degenerate periodic box under explicit
    solvent. That is affordable because the file holds the configured observations -- 21 frames by
    default -- and it is the only way to tell a complete file from one whose header survived an
    interrupted write. Nothing is hashed, and no production trajectory is read this way.
    """
    directory = Path(directory)
    marker = directory / COMPLETION_NAME
    table = directory / CSV_NAME
    dcd = directory / DCD_NAME
    expected = int(SCHEDULE["number_of_observations"])

    if not marker.is_file():
        return False, "no completion record"
    try:
        record = json.loads(marker.read_text())
    except Exception as error:
        return False, f"{COMPLETION_NAME} is unreadable ({type(error).__name__})"
    if record.get("status") != "completed":
        return False, f"completion record says {record.get('status')!r}"
    if index is not None and record.get("ais_trajectory_index") not in (None, index):
        return False, (f"completion record is for trajectory "
                       f"{record.get('ais_trajectory_index')}, not {index}")
    if record.get("observations") not in (None, expected):
        return False, (f"completion record claims {record.get('observations')} observation(s), "
                       f"{expected} expected")

    if not table.is_file():
        return False, f"{CSV_NAME} is missing"
    rows = list(csv.DictReader(table.open()))
    if len(rows) != expected:
        return False, f"{len(rows)} observation row(s) on disk, {expected} expected"

    # The DCD is the artifact most likely to be missing or short after an interrupted run, and the
    # one whose absence a healthy JSON and CSV would otherwise hide completely. Every frame is
    # READ, not counted from the header: an interrupted write leaves the header claiming the count
    # the writer intended and the last coordinate record short.
    if not dcd.is_file():
        return False, f"{DCD_NAME} is missing, so the coordinates this record describes are gone"
    intact, detail = validate_generated_dcd(
        dcd, expected, topology=INPUTS / "topology.pdb", need_box=not implicit, what=DCD_NAME)
    if not intact:
        return False, detail
    frames = expected

    mapping = [int(row["coordinate_frame_index"]) for row in rows]
    if mapping != list(range(expected)):
        return False, (f"{CSV_NAME} coordinate frame indices are not 0..{expected - 1}; the rows "
                       f"do not map one-to-one onto the DCD")
    if float(rows[0]["cumulative_work_kj_mol"]) != 0.0:
        return False, "the first observation does not have zero cumulative work"
    if abs(float(rows[0]["tau"]) - float(SCHEDULE["taus"][0])) > 1e-9:
        return False, (f"the first observation is at tau {rows[0]['tau']}, but this path starts "
                       f"at {SCHEDULE['taus'][0]}")
    if abs(float(rows[-1]["tau"]) - float(SCHEDULE["taus"][-1])) > 1e-9:
        return False, (f"the last observation is at tau {rows[-1]['tau']}, but this path ends at "
                       f"{SCHEDULE['taus'][-1]}")
    return True, (f"{len(rows)} observations, {frames} DCD frame(s), endpoints "
                  f"{rows[0]['tau']} -> {rows[-1]['tau']}")


def run_one_path(index, plan):
    """Propagate one AIS path from its source frame to tau_end, writing coordinates and work."""
    directory = trajectory_directory(index)
    entry = plan["trajectories"][index]
    device = entry["gpu_device"]

    done, why = path_is_complete(directory, index)
    if done:
        print(f"[AIS {index:04d}] already complete: {why}. Nothing was run.", flush=True)
        return {"status": "skipped", "reason": why}
    if directory.exists() and any(directory.iterdir()):
        # Never append a second path to an existing DCD: the file would look like one continuous
        # trajectory and would not be. Replacing an INCOMPLETE directory is safe and is what
        # happens; a complete one was skipped above and never reaches here.
        print(f"[AIS {index:04d}] replacing an incomplete directory ({why})", flush=True)
        shutil.rmtree(directory)
    directory.mkdir(parents=True, exist_ok=True)

    log = []

    def say(message):
        line = f"[AIS {index:04d}] {message}"
        print(line, flush=True)
        log.append(line)

    platform_name = plan["platform"]
    say(f"platform {platform_name}" + (f", CUDA device {device}" if device is not None else ""))

    base = XmlSerializer.deserialize((INPUTS / "system.xml").read_text())
    barostats = [base.getForce(i).__class__.__name__ for i in range(base.getNumForces())
                 if "Barostat" in base.getForce(i).__class__.__name__]
    if barostats:
        raise SystemExit(
            f"the prepared System carries {barostats}, but AIS switches at FIXED VOLUME and adds "
            f"no barostat. Remove it, or rebuild the system with `md-openmm sys-gen`.")

    excluded = SOLUTE["rest2"]["omega_excluded_bonds"] if PATH_DEFINITION["path"][
        "omega_exclusion"] else []
    switcher = TauSwitcher(base, SOLUTE_INDICES, excluded)
    taus = SCHEDULE["taus"]
    system = switcher.prepared_system(taus[0])

    integrator = LangevinMiddleIntegrator(TEMPERATURE, FRICTION, TIMESTEP_FS * unit.femtoseconds)
    integrator.setRandomNumberSeed(int(entry["integrator_seed"]))
    properties = {}
    if platform_name == "CUDA":
        properties = {"Precision": "mixed"}
        if device is not None:
            properties["DeviceIndex"] = str(device)
    platform = Platform.getPlatformByName(platform_name)
    topology = PDBFile(str(plan["source"]["topology"])).topology
    from openmm.app import Simulation

    simulation = Simulation(topology, system, integrator, platform, properties)

    # The starting configuration, from the prepared inputs. The plan JSON carries only the frame
    # index: a JSON array of a solvated system's coordinates is enormous and every worker reads
    # the plan. The source trajectory is not opened here and does not need to still exist.
    record = read_prepared_sources()
    if record is None:
        raise SystemExit(
            f"{SOURCES_DIR}/{SOURCES_RECORD} is missing; the starting configurations are prepared "
            f"before any path runs and must be present.")
    positions = load_prepared_frame(record, entry)
    if not implicit:
        # Already in the reduced form OpenMM requires, and stored as exact numbers rather than
        # recovered from the DCD's cell lengths and angles. Fixed volume: nothing changes it for
        # the rest of the path.
        box = [[float(v) for v in row] for row in entry["box_vectors_nm"]]
        simulation.context.setPeriodicBoxVectors(*reduced_box_vectors(box))
    simulation.context.setPositions(positions * unit.nanometer)
    # The prepared inputs hold positions and box vectors only, so the momenta are drawn fresh from
    # the Maxwell-Boltzmann distribution at the one common temperature -- which is what AIS wants,
    # and which also gives constraint-satisfying velocities. The seed is this path's own,
    # recorded, and different from every other path's.
    simulation.context.setVelocitiesToTemperature(TEMPERATURE, int(entry["velocity_seed"]))
    say(f"source frame {entry['source_frame_index']} at {entry['source_time_ps']:g} ps, "
        f"tau {taus[0]:g}, seeds integrator={entry['integrator_seed']} "
        f"velocity={entry['velocity_seed']}")

    active = sum(1 for i in range(system.getNumForces())
                 if "Barostat" in system.getForce(i).__class__.__name__)
    say(f"{active} barostat(s) in the switching System (fixed volume; no pV work is included)")

    handle = (directory / DCD_NAME).open("wb")
    dcd = DCDFile(handle, topology, TIMESTEP_FS * unit.femtoseconds, firstStep=0,
                  interval=int(SCHEDULE["steps_per_observation"]))
    rows = []
    interval = int(SCHEDULE["parameter_update_interval_steps"])
    per_observation = int(SCHEDULE["updates_per_observation"])

    def energy():
        return simulation.context.getState(getEnergy=True).getPotentialEnergy().value_in_unit(
            unit.kilojoule_per_mole)

    def observe(observation, cumulative, incremental):
        state = simulation.context.getState(getPositions=True, enforcePeriodicBox=False)
        dcd.writeModel(state.getPositions(),
                       periodicBoxVectors=(None if implicit
                                           else state.getPeriodicBoxVectors()))
        rows.append({
            "ais_trajectory_index": index,
            "observation_index": observation["observation_index"],
            # Written in lockstep with the DCD, so the k-th row IS the k-th frame by construction.
            "coordinate_frame_index": len(rows),
            "source_frame_index": entry["source_frame_index"],
            "source_time_ps": entry["source_time_ps"],
            "protocol_step": observation["protocol_step"],
            "switching_time_ps": observation["switching_time_ps"],
            "tau": observation["tau"],
            "s": observation["s"],
            "sqrt_s": observation["sqrt_s"],
            "incremental_work_kj_mol": incremental,
            "cumulative_work_kj_mol": cumulative,
            "cumulative_reduced_work": BETA * cumulative,
            "temperature_kelvin": TEMPERATURE_K,
            "integrator_seed": entry["integrator_seed"],
            "velocity_seed": entry["velocity_seed"],
            "gpu_device": "" if device is None else device,
            "dcd_filename": DCD_NAME,
        })

    # Observation 0 is the SOURCE configuration under the source Hamiltonian, before any parameter
    # change and before any propagation. Its cumulative work is exactly zero by definition.
    cumulative = 0.0
    since_observation = 0.0
    observe(OBSERVATIONS[0], 0.0, 0.0)
    say(f"observation 0: tau {taus[0]:g}, work 0")

    for update in range(int(SCHEDULE["number_of_updates"])):
        # delta_W = U(tau_{j+1}, x_j) - U(tau_j, x_j): the parameters move at frozen coordinates.
        before = energy()
        switcher.set_tau(simulation.context, system, taus[update + 1])
        after = energy()
        increment = after - before
        cumulative += increment
        since_observation += increment
        # ...and only then does the configuration propagate under the new Hamiltonian.
        simulation.step(interval)
        if (update + 1) % per_observation == 0:
            observation = OBSERVATIONS[(update + 1) // per_observation]
            observe(observation, cumulative, since_observation)
            since_observation = 0.0

    state = simulation.context.getState(getPositions=True, getVelocities=True,
                                        getParameters=True, enforcePeriodicBox=False)
    (directory / "final_state.xml").write_text(XmlSerializer.serialize(state), encoding="utf-8")
    handle.close()

    with (directory / CSV_NAME).open("w", newline="") as table:
        writer = csv.DictWriter(table, fieldnames=list(OBSERVATION_COLUMNS))
        writer.writeheader()
        writer.writerows(rows)

    say(f"observation {rows[-1]['observation_index']}: tau {rows[-1]['tau']:g}, "
        f"cumulative work {cumulative:.6f} kJ/mol "
        f"(reduced {BETA * cumulative:.6f})")
    say(f"complete: {len(rows)} observations, {SCHEDULE['total_steps']} integration steps")
    (directory / "stdout.log").write_text("\n".join(log) + "\n", encoding="utf-8")

    completion = {
        "status": "completed",
        "ais_trajectory_index": index,
        "observations": len(rows),
        "total_work_kj_mol": cumulative,
        "total_reduced_work": BETA * cumulative,
        "finished_utc": utc_now(),
        "platform": platform_name,
        "gpu_device": device,
        "integrator_seed": entry["integrator_seed"],
        "velocity_seed": entry["velocity_seed"],
    }
    (directory / COMPLETION_NAME).write_text(json.dumps(completion, indent=2) + "\n",
                                             encoding="utf-8")
    return completion


# ---------------------------------------------------------------------------------------------
# The plan, shared by the parent and every worker
# ---------------------------------------------------------------------------------------------

PLAN_NAME = "_ais_plan.json"


#: How many frames MDTraj holds in memory at a time while streaming the source trajectory.
#: A source DCD can be far larger than memory, so it is never loaded whole -- peak usage is one
#: chunk plus the handful of frames actually selected, not the length of the trajectory.
SOURCE_CHUNK_FRAMES = 50
#: The prepared starting configurations, and the record that describes them. Durable, archived
#: with the results, and NOT deleted at the end of a run: they are the AIS equivalent of
#: `common/original_inputs/`. Coordinates never go into `_ais_plan.json` -- a JSON array of a
#: solvated system's coordinates is enormous, and every worker reads the plan.
SOURCES_DIR = "inputs"
SOURCES_DCD = "sources.dcd"
SOURCES_RECORD = "sources.yaml"
SOURCES_FORMAT = "md-templates-ais-sources/v1"

#: Why the prepared inputs hold coordinates and no momenta. Recorded in `sources.yaml`, because a
#: directory of starting configurations is exactly where someone would expect to find velocities
#: and be quietly wrong about what they got.
VELOCITY_NOTE = (
    "Positions and box vectors only. DCD carries no velocities, and AIS does not want them: each "
    "path draws fresh Maxwell-Boltzmann momenta at the one common temperature from its own "
    "recorded velocity_seed. The canonical distribution factorises into configurational and "
    "momentum parts, so an equilibrium configuration plus an independent momentum draw is a "
    "proper sample of the full ensemble -- and OpenMM's setVelocitiesToTemperature applies the "
    "velocity constraints, which momenta restored from a file would not satisfy unless "
    "constrained again. These are starting configurations, NOT restart states: a restart in this "
    "repository is a final_state.xml and does carry velocities."
)


def sources_dir():
    return HERE / SOURCES_DIR


def selection_identity():
    """What the prepared inputs must still agree with for a rerun to reuse them.

    Everything here changes WHICH frames a run would start from. If any of it has moved, the
    prepared inputs describe a different calculation and reusing them silently would produce work
    values labelled with a configuration that did not produce them.
    """
    source = method["source"]
    return {
        "trajectory_configured": str(source["trajectory"]),
        "number_of_trajectories": int(source["number_of_trajectories"]),
        "window_ps": [float(source["start_time_ps"]), float(source["end_time_ps"])],
        "selection": source["selection"],
        "with_replacement": bool(source["allow_sampling_with_replacement"]),
        "selection_seed": derive_seed(BASE_SEED, "AIS", "source-selection"),
        "tau_start": float(PATH_DEFINITION["path"]["tau_start"]),
        "implicit_solvent": bool(implicit),
    }


def write_prepared_sources(ensemble, kept, chunks):
    """Materialise the selected frames as a durable input, before any dynamics.

    One DCD holding one frame per path, plus a YAML record that says where each frame came from.
    After this, the source trajectory is no longer needed: it can be archived or deleted and the
    paths still rerun. That is the point -- an AIS result archived without the configurations it
    started from cannot say what it annealed away from.
    """
    import mdtraj

    directory = sources_dir()
    directory.mkdir(parents=True, exist_ok=True)
    times, selected = ensemble["times"], ensemble["selected"]

    xyz = np.empty((len(selected), ensemble["survey"]["n_atoms"], 3), dtype=np.float32)
    entries, boxes = [], []
    for index, frame in enumerate(selected):
        coordinates, box = kept[frame]
        xyz[index] = coordinates
        entry = {
            "ais_trajectory_index": index,
            # Written in path order, so this is the index into sources.dcd. With replacement two
            # paths may share a source frame; the frame is written twice so the mapping stays 1:1.
            "dcd_frame_index": index,
            "source_frame_index": int(frame),
            "source_time_ps": float(times[frame]),
            "integrator_seed": derive_seed(BASE_SEED, "AIS", index, "integrator"),
            # Recorded here, in the inputs, because the momenta are GENERATED from it rather than
            # restored from a file. The seed IS the momentum record.
            "velocity_seed": derive_seed(BASE_SEED, "AIS", index, "velocities"),
        }
        if implicit:
            entry["box_vectors_nm"] = None
            entry["box_volume_nm3"] = None
            boxes.append(None)
        else:
            if box is None:
                raise SystemExit(
                    f"source frame {frame} carries no periodic box vectors, but this is an "
                    f"explicit-solvent system and the path keeps the box it starts from.")
            reduced = np.array(reduced_box_vectors(box.tolist()))
            before = abs(float(np.linalg.det(box)))
            after = abs(float(np.linalg.det(reduced)))
            if abs(before - after) > 1e-9 * max(1.0, before):
                raise SystemExit(
                    f"reducing the box vectors of source frame {frame} changed the cell volume "
                    f"({before:.9f} -> {after:.9f} nm^3). Reduction renames the lattice vectors "
                    f"and must not change the lattice; refusing to propagate in a box that is not "
                    f"the one the source frame had.")
            # The AUTHORITATIVE box vectors, as exact numbers. The DCD also carries a cell, but
            # DCD stores lengths and angles, and round-tripping a reduced triclinic cell through
            # them is a precision question this does not need to have.
            entry["box_vectors_nm"] = [[float(v) for v in row] for row in reduced]
            entry["box_volume_nm3"] = after
            boxes.append(reduced)
        entries.append(entry)

    # DCDTrajectoryFile writes coordinates without needing an mdtraj topology, in Angstroms.
    with mdtraj.formats.DCDTrajectoryFile(str(directory / SOURCES_DCD), "w") as handle:
        if implicit:
            handle.write(xyz * 10.0)
        else:
            lengths, angles = [], []
            for reduced in boxes:
                a, b, c, alpha, beta, gamma = (
                    mdtraj.utils.box_vectors_to_lengths_and_angles(*reduced))
                lengths.append([a, b, c])
                angles.append([alpha, beta, gamma])
            handle.write(xyz * 10.0,
                         cell_lengths=np.array(lengths, dtype=np.float32) * 10.0,
                         cell_angles=np.array(angles, dtype=np.float32))

    pairs = [(int(a), int(b)) for i, a in enumerate(selected) for b in selected[i + 1:]]
    frame_gaps = sorted(abs(a - b) for a, b in pairs)
    time_gaps = sorted(abs(float(times[a]) - float(times[b])) for a, b in pairs)
    survey = ensemble["survey"]
    record = {
        "format": SOURCES_FORMAT,
        "description": "AIS starting configurations, prepared from an equilibrium trajectory.",
        "trajectory_file": SOURCES_DCD,
        "topology": relative_to_project(ensemble["paths"]["topology"]),
        "n_paths": len(selected),
        "n_atoms": int(survey["n_atoms"]),
        "velocities": {"stored": False, "drawn_at_run_time": True, "note": VELOCITY_NOTE},
        "source": {
            "trajectory": relative_to_project(ensemble["paths"]["trajectory"]),
            "trajectory_configured": str(method["source"]["trajectory"]),
            # DELIBERATELY NOT HASHED. A production source can be hundreds of gigabytes, and a
            # full-file digest at generation, preflight or run time costs more than it proves --
            # the whole point of the bounded iterload survey is that cost must not scale with the
            # length of the source. These are bounded, non-authoritative observations instead.
            "trajectory_sha256": None,
            "trajectory_not_hashed": (
                "the production source is never hashed at runtime; MD-data hashes it once at "
                "archival"),
            "trajectory_bytes": int(Path(ensemble["paths"]["trajectory"]).stat().st_size),
            "n_frames": int(survey["n_frames"]),
            "loader": survey["loader"],
            "chunk_frames": int(survey["chunk_frames"]),
            "chunks_read_survey": int(survey["chunks_read"]),
            "chunks_read_selection": int(chunks),
            "frame_timing": ensemble["timing"],
            "first_time_ps": float(times[0]),
            "last_time_ps": float(times[-1]),
            "eligible_frames": len(ensemble["eligible"]),
            "eligible_frame_range": [int(ensemble["eligible"][0]),
                                     int(ensemble["eligible"][-1])],
            "tau": ensemble["tau"],
            "tau_evidence": ensemble["tau_evidence"],
            "tau_route": ensemble["tau_route"],
        },
        "selection": dict(selection_identity(),
                          window_is_inclusive=True,
                          # Visible on purpose: two paths starting from frames a few femtoseconds
                          # apart are two nearly identical configurations, and their work values
                          # are not the independent samples the CSV makes them look like.
                          minimum_frame_gap=(frame_gaps[0] if frame_gaps else None),
                          minimum_time_gap_ps=(time_gaps[0] if time_gaps else None)),
        "paths": entries,
    }
    (directory / SOURCES_RECORD).write_text(
        yaml.safe_dump(record, sort_keys=False, default_flow_style=False), encoding="utf-8")
    return record


def read_prepared_sources():
    """The prepared inputs, if they are present AND still describe this configuration.

    Returns None when there are none. Raises when there are some and they disagree: silently
    re-preparing would delete the very artifact a finished path was started from, and silently
    reusing them would mislabel the result.
    """
    directory = sources_dir()
    record_path = directory / SOURCES_RECORD
    if not record_path.is_file():
        return None
    record = yaml.safe_load(record_path.read_text(encoding="utf-8")) or {}
    where = f"{SOURCES_DIR}/{SOURCES_RECORD}"

    if record.get("format") != SOURCES_FORMAT:
        raise SystemExit(f"{where} is {record.get('format')!r}, not {SOURCES_FORMAT!r}.")
    trajectory = directory / record.get("trajectory_file", SOURCES_DCD)
    if not trajectory.is_file():
        raise SystemExit(
            f"{where} describes {record.get('n_paths')} prepared configuration(s) but "
            f"{SOURCES_DIR}/{trajectory.name} is missing. Remove {SOURCES_DIR}/ to prepare them "
            f"again from the source trajectory.")
    # Physically validated: every prepared configuration is read back. These are the coordinates
    # the paths start from, so "the header says three" is not good enough.
    intact, detail = validate_generated_dcd(
        trajectory, int(record.get("n_paths", -1)),
        topology=(PROJECT / record["topology"]).resolve(), need_box=not implicit,
        what=f"{SOURCES_DIR}/{trajectory.name}")
    if not intact:
        raise SystemExit(
            f"{detail}, against the {record.get('n_paths')} path(s) {where} describes. The "
            f"prepared inputs are incomplete; remove {SOURCES_DIR}/ to prepare them again from "
            f"the source trajectory.")

    wanted, have = selection_identity(), record.get("selection") or {}
    differing = {key: (have.get(key), value) for key, value in wanted.items()
                 if have.get(key) != value}
    if differing:
        lines = "\n".join(f"    {key}: prepared with {was!r}, configured {now!r}"
                           for key, (was, now) in sorted(differing.items()))
        # The first line names the fields, because a preflight row shows only the first line and
        # "a different calculation" without saying which field moved is not a usable message.
        raise SystemExit(
            f"{where} was prepared for a different calculation: "
            f"{', '.join(sorted(differing))} changed\n{lines}\n"
            f"  These decide WHICH frames each path starts from, so reusing the prepared inputs "
            f"would label this run with a configuration that did not produce it.\n"
            f"  Restore the configuration, or remove {SOURCES_DIR}/ (and any finished path "
            f"directories) to prepare fresh starting configurations.")
    return record


def load_prepared_frame(record, entry):
    """One starting configuration, read from the prepared inputs by frame index.

    Streamed, like everything else that reads a trajectory here -- the file is small by
    construction, but there is one rule about how trajectories are read and it has no exceptions.
    """
    directory = sources_dir()
    wanted = int(entry["dcd_frame_index"])
    paths = {"trajectory": directory / record.get("trajectory_file", SOURCES_DCD),
             "topology": (PROJECT / record["topology"]).resolve()}
    offset = 0
    for piece in _iterload(paths, SOURCE_CHUNK_FRAMES):
        if offset <= wanted < offset + int(piece.n_frames):
            return np.array(piece.xyz[wanted - offset], dtype=float)
        offset += int(piece.n_frames)
    raise SystemExit(
        f"{SOURCES_DIR}/{paths['trajectory'].name} ended before frame {wanted} could be read.")


def resolve_ais_inputs(*, prepare=True):
    """The starting configurations, prepared if they are not already.

    Once prepared, the source trajectory is never opened again -- so a rerun works after the
    source has been archived or deleted, and what the run consumes is exactly what was archived.
    """
    record = read_prepared_sources()
    if record is not None:
        return record, "prepared inputs"
    if not prepare:
        return None, "source trajectory"
    ensemble = resolve_source_ensemble()
    kept, chunks = collect_frames(ensemble["paths"], ensemble["selected"])
    return write_prepared_sources(ensemble, kept, chunks), "source trajectory"


def _iterload(paths, chunk):
    """Delegates to the shared helper. `mdtraj.load` is not used and must not be reintroduced."""
    return source_ensemble._iterload(paths, chunk)


def survey_source(paths, *, chunk=SOURCE_CHUNK_FRAMES):
    """Delegates to the shared helper: frame count, atom count, box presence, nothing retained."""
    try:
        return source_ensemble.survey_source(paths, chunk=chunk)
    except source_ensemble.SourceError as failure:
        raise SystemExit(str(failure)) from None


def collect_frames(paths, wanted, *, chunk=SOURCE_CHUNK_FRAMES):
    """Delegates to the shared helper: stream again, keep only the selected frames."""
    try:
        return source_ensemble.collect_frames(paths, wanted, chunk=chunk)
    except source_ensemble.SourceError as failure:
        raise SystemExit(str(failure)) from None


def atom_identity(topology):
    """Delegates to the shared helper. Atom NAME alone is not identity."""
    return source_ensemble.atom_identity(topology)


ATOM_FIELDS = ("chain id", "chain index", "residue index", "residue id", "residue name",
               "atom name", "element")


def validate_topologies(paths):
    """Delegates to the shared helper: same atoms, same order, same connectivity."""
    try:
        return source_ensemble.validate_topologies(source_request(), paths)
    except source_ensemble.SourceError as failure:
        raise SystemExit(str(failure)) from None


def resolve_source_ensemble():
    """Delegates to the shared helper, then applies AIS's own tau_start requirement.

    The helper already refuses a source whose tau differs from the required one; AIS's required
    tau IS `path.tau_start`, so the check is the same one, stated in AIS's own words when it
    fails.
    """
    try:
        return source_ensemble.resolve_source_ensemble(source_request())
    except source_ensemble.SourceError as failure:
        raise SystemExit(str(failure)) from None


def check_ais_source(dynamics=True):
    """The AIS-specific preflight rows, appended to the shared table.

    Every one of these is a reason a run would have failed AFTER spawning workers and creating
    trajectory files, which is exactly what the preflight exists to move earlier. It never
    prepares anything: `--check` writes nothing, so a project whose inputs are not prepared yet is
    checked against the source trajectory instead.
    """
    rows = []
    try:
        record, _ = resolve_ais_inputs(prepare=False)
    except SystemExit as error:
        return [preflight.Result("AIS inputs", preflight.FAIL, str(error).splitlines()[0])]

    if record is not None:
        # Prepared already. The source trajectory is deliberately NOT opened: it may have been
        # archived or deleted, and a rerun must not depend on it still being there.
        source = record["source"]
        rows.append(preflight.Result(
            "AIS inputs", preflight.PASS,
            f"{record['n_paths']} prepared configuration(s) in {SOURCES_DIR}/"
            f"{record.get('trajectory_file', SOURCES_DCD)}, {record['n_atoms']} atoms; the source "
            f"trajectory is not needed"))
        rows.append(preflight.Result(
            "AIS source tau", preflight.PASS,
            f"tau = {source['tau']} from {source['tau_route']}, recorded when the inputs were "
            f"prepared, matches path.tau_start"))
        rows.append(preflight.Result(
            "AIS velocities", preflight.PASS,
            "not stored; drawn per path from a recorded seed at the common temperature"))
        rows.append(preflight.Result(
            "AIS selection", preflight.PASS,
            f"frames {[int(e['source_frame_index']) for e in record['paths']]} from "
            f"{source['eligible_frames']} eligible; closest pair "
            f"{record['selection'].get('minimum_time_gap_ps')} ps apart"))
        return rows

    try:
        ensemble = resolve_source_ensemble()
    except SystemExit as error:
        return [preflight.Result("AIS source", preflight.FAIL, str(error).splitlines()[0])]

    survey, timing = ensemble["survey"], ensemble["timing"]
    rows.append(preflight.Result(
        "AIS source", preflight.PASS,
        f"{ensemble['paths']['trajectory'].name}: {survey['n_frames']} frame(s), "
        f"{survey['n_atoms']} atoms, read with {survey['loader']} in {survey['chunks_read']} "
        f"chunk(s) of {survey['chunk_frames']}"))
    rows.append(preflight.Result(
        "AIS frame timing", preflight.PASS,
        f"{timing['route']}: {timing['first_frame_time_ps']} + k * "
        f"{timing['frame_interval_ps']} ps"))
    rows.append(preflight.Result(
        "AIS source tau", preflight.PASS,
        f"tau = {ensemble['tau']} from {ensemble['tau_route']}, matches path.tau_start"))
    rows.append(preflight.Result(
        "AIS selection", preflight.PASS,
        f"{len(ensemble['selected'])} path(s) from {len(ensemble['eligible'])} eligible frame(s) "
        f"in {method['source']['start_time_ps']}-{method['source']['end_time_ps']} ps inclusive; "
        f"frames {ensemble['selected']}"))
    rows.append(preflight.Result(
        "AIS inputs", preflight.SKIP if not dynamics else preflight.PASS,
        f"will be prepared into {SOURCES_DIR}/{SOURCES_DCD} before any path runs"
        + ("" if dynamics else "; --check prepares nothing")))
    seeds = {derive_seed(BASE_SEED, "AIS", i, kind)
             for i in range(len(ensemble["selected"])) for kind in ("integrator", "velocities")}
    expected = 2 * len(ensemble["selected"])
    rows.append(preflight.Result(
        "AIS seeds", preflight.PASS if len(seeds) == expected else preflight.FAIL,
        f"{len(seeds)} distinct seed(s) for {len(ensemble['selected'])} path(s)"))
    return rows


def build_plan():
    """Everything decided before any dynamics: which frames, which seeds, which device.

    Written to disk so each worker process reads the SAME plan the parent recorded, rather than
    re-deriving it and possibly disagreeing. Coordinates are never in the JSON: they live in the
    prepared inputs, and the plan carries only the frame index into them.
    """
    platform_name = resolve_platform()
    record, route = resolve_ais_inputs()
    source = dict(record["source"])
    devices, device_list = device_assignment(record["n_paths"])

    trajectories = []
    for entry in record["paths"]:
        index = int(entry["ais_trajectory_index"])
        plan_entry = {
            "ais_trajectory_index": index,
            "directory": trajectory_directory(index).name,
            "source_frame_index": int(entry["source_frame_index"]),
            "source_time_ps": float(entry["source_time_ps"]),
            "integrator_seed": int(entry["integrator_seed"]),
            "velocity_seed": int(entry["velocity_seed"]),
            "gpu_device": devices[index],
            # The coordinates live in the prepared inputs; the plan carries only the index.
            "dcd_frame_index": int(entry["dcd_frame_index"]),
        }
        if not implicit:
            plan_entry["box_vectors_nm"] = entry["box_vectors_nm"]
            plan_entry["box_volume_nm3"] = entry["box_volume_nm3"]
        trajectories.append(plan_entry)

    selection = record["selection"]
    source.update({
        "prepared_from": route,
        "prepared_inputs": f"{SOURCES_DIR}/{record.get('trajectory_file', SOURCES_DCD)}",
        "prepared_inputs_record": f"{SOURCES_DIR}/{SOURCES_RECORD}",
        # Resolved for the worker to open, relative for the record. The two are separated
        # below, where the plan's source block is copied into resolved_run.yaml.
        "topology": str((PROJECT / record["topology"]).resolve()),
        "topology_relative": record["topology"],
        "n_atoms": int(record["n_atoms"]),
        "window_ps": selection["window_ps"],
        "window_is_inclusive": True,
        "selected_frame_indices": [int(e["source_frame_index"]) for e in record["paths"]],
        "selection": selection["selection"],
        "with_replacement": selection["with_replacement"],
        "selection_seed": selection["selection_seed"],
        "minimum_frame_gap": selection.get("minimum_frame_gap"),
        "minimum_time_gap_ps": selection.get("minimum_time_gap_ps"),
        "velocities_stored": False,
    })
    return {
        "platform": platform_name,
        "devices": device_list,
        "sources_record": f"{SOURCES_DIR}/{SOURCES_RECORD}",
        "source": source,
        "trajectories": trajectories,
    }


def write_selected_frames(plan):
    """The deterministic selection, on disk BEFORE any dynamics runs."""
    with (HERE / "selected_initial_frames.csv").open("w", newline="") as table:
        writer = csv.DictWriter(table, fieldnames=[
            "ais_trajectory_index", "source_frame_index", "source_time_ps", "source_tau",
            "source_tau_route", "integrator_seed", "velocity_seed", "gpu_device", "directory",
            "source_trajectory", "selection", "selection_seed"])
        writer.writeheader()
        for entry in plan["trajectories"]:
            writer.writerow({
                "ais_trajectory_index": entry["ais_trajectory_index"],
                "source_frame_index": entry["source_frame_index"],
                "source_time_ps": entry["source_time_ps"],
                "source_tau": plan["source"]["tau"],
            "source_tau_route": plan["source"]["tau_route"],
                "integrator_seed": entry["integrator_seed"],
                "velocity_seed": entry["velocity_seed"],
                "gpu_device": "" if entry["gpu_device"] is None else entry["gpu_device"],
                "directory": entry["directory"],
                "source_trajectory": plan["source"]["trajectory_configured"],
                "selection": plan["source"]["selection"],
                "selection_seed": plan["source"]["selection_seed"],
            })


def environment_versions():
    versions = {"python": sys.version.split()[0]}
    for name in ("openmm", "mdtraj", "numpy", "yaml"):
        try:
            module = __import__(name)
            if name == "openmm":
                versions[name] = module.version.version
                versions["openmm_short_version"] = module.version.short_version
            else:
                versions[name] = str(getattr(module, "__version__", "unknown"))
        except Exception as error:
            versions[name] = f"unavailable ({type(error).__name__})"
    return versions


LIMITATIONS = [
    "forward path only: tau_start -> tau_end. The reverse path is not implemented.",
    "no mid-path restart. A path that is interrupted is rerun from its source frame; an "
    "incomplete trajectory directory is replaced, never appended to.",
    "fixed volume. No barostat is active during switching and no pressure-volume term is included "
    "in the work, even when the source ensemble was NPT.",
    "DCD carries no velocities, so each path draws fresh Maxwell-Boltzmann momenta at the common "
    "temperature using its own recorded seed.",
    "no free-energy estimator. The work columns are the input a Hummer-Szabo or Jarzynski analysis "
    "would consume; computing one is not part of this runtime.",
]


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--worker", type=int, default=None,
                        help="run exactly one AIS path in this process, by index")
    parser.add_argument("--check", action="store_true",
                        help="run the preflight and exit; no dynamics, nothing written")
    args = parser.parse_args(argv)

    if args.worker is None:
        # Before the plan is built and long before any worker process is spawned. The AIS-specific
        # source checks are appended to the shared ones so one table covers everything.
        preflight.require(
            HERE, PROJECT, INPUTS, CONFIG, stage=STAGE,
            label=f"AIS ({'check only' if args.check else 'switching paths'})",
            dynamics=not args.check,
            extra=[lambda: check_ais_source(dynamics=not args.check)])
        if args.check:
            print("[AIS] --check: preflight only. No dynamics ran, no worker was spawned, and "
                  "no trajectory was created.", flush=True)
            return 0

    if args.worker is not None:
        plan = json.loads((HERE / PLAN_NAME).read_text())
        run_one_path(args.worker, plan)
        return 0

    started = utc_now()
    plan = build_plan()
    (HERE / PLAN_NAME).write_text(json.dumps(plan), encoding="utf-8")
    write_selected_frames(plan)

    count = len(plan["trajectories"])
    devices = plan["devices"]
    concurrency = max(1, min(count, len(devices))) if devices else 1
    print(f"[AIS] {count} independent path(s), tau {PATH_DEFINITION['path']['tau_start']} -> "
          f"{PATH_DEFINITION['path']['tau_end']}, "
          f"{SCHEDULE['number_of_updates']} switching update(s) over "
          f"{SCHEDULE['total_steps']} steps, {SCHEDULE['number_of_observations']} observations",
          flush=True)
    print(f"[AIS] source {plan['source']['trajectory_configured']} at tau {plan['source']['tau']}, "
          f"{plan['source']['eligible_frames']} eligible frame(s) in "
          f"{plan['source']['window_ps']} ps (inclusive)", flush=True)
    print(f"[AIS] platform {plan['platform']}, device(s) {devices or 'none'}, "
          f"{concurrency} path(s) at a time; paths sharing a device run in turn", flush=True)

    # Isolated worker PROCESSES, not threads: one OpenMM Context per process, so a Context is never
    # shared across devices and a crash in one path cannot take the others with it.
    results, pending = {}, list(range(count))
    running = {}
    failures = []
    while pending or running:
        while pending and len(running) < concurrency:
            index = pending.pop(0)
            command = [sys.executable, str(HERE / "run.py"), "--worker", str(index)]
            running[index] = subprocess.Popen(command, cwd=str(HERE))
        finished = [index for index, process in running.items() if process.poll() is not None]
        if not finished:
            next(iter(running.values())).wait()
            continue
        for index in finished:
            code = running.pop(index).returncode
            directory = trajectory_directory(index)
            complete, why = path_is_complete(directory, index)
            if code == 0 and complete:
                results[index] = json.loads((directory / COMPLETION_NAME).read_text())
            else:
                failures.append({"ais_trajectory_index": index, "exit_code": code, "reason": why})

    completed = sorted(results)
    failed = sorted(entry["ais_trajectory_index"] for entry in failures)
    total_work = [results[i]["total_work_kj_mol"] for i in completed]

    record = {
        "format": RECORD_FORMAT,
        "record_kind": "ais_run",
        "started_utc": started,
        "finished_utc": utc_now(),
        "status": "completed" if not failed else "incomplete",
        "implementation": CONFIG.get("provenance"),
        "command": list(sys.argv),
        "environment": environment_versions(),
        "platform": plan["platform"],
        "gpu_devices": devices,
        "path": PATH_DEFINITION["path"],
        "schedule": {key: SCHEDULE[key] for key in
                     ("total_steps", "number_of_updates", "number_of_observations",
                      "updates_per_observation", "steps_per_observation",
                      "parameter_update_interval_steps", "timestep_fs")},
        "work_convention": PATH_DEFINITION["work_convention"],
        "ensemble": PATH_DEFINITION["ensemble"],
        "thermodynamics": {
            "temperature_kelvin": TEMPERATURE_K,
            "beta_kj_mol_inverse": BETA,
            "constant_along_path": True,
            "note": "Hamiltonian switching at constant temperature, not temperature annealing",
        },
        # Relative, so the record survives the tree being moved. The plan's absolute copy is
        # for opening the file during the run and is not part of the record.
        "source": dict(plan["source"],
                       topology=plan["source"].get("topology_relative",
                                                   plan["source"]["topology"]),
                       topology_relative=None),
        "trajectories": [
            {**{key: entry[key] for key in
                ("ais_trajectory_index", "directory", "source_frame_index", "source_time_ps",
                 "integrator_seed", "velocity_seed", "gpu_device")},
             "status": ("completed" if entry["ais_trajectory_index"] in results else "failed"),
             "total_work_kj_mol": results.get(entry["ais_trajectory_index"], {}).get(
                 "total_work_kj_mol"),
             "total_reduced_work": results.get(entry["ais_trajectory_index"], {}).get(
                 "total_reduced_work")}
            for entry in plan["trajectories"]],
        "completed_trajectory_indices": completed,
        "failed_trajectory_indices": failed,
        "pending_trajectory_indices": [],
        "failures": failures,
        "limitations": LIMITATIONS,
    }
    (HERE / "resolved_run.yaml").write_text(
        yaml.safe_dump(record, sort_keys=False, default_flow_style=False), encoding="utf-8")

    # The stage record `preflight.check_own_completion` reads. `resolved_run.yaml` above is the
    # FAIR account of the invocation; this is the scientific account of the request that ran, and
    # it is what a continuation is compared against. Written only now, after every path that was
    # going to finish has finished.
    #
    # Two fingerprints, as cMD and REST2 write: the full one identifies this exact request, the
    # invariant one excludes the extendable fields -- `number_of_paths` among them -- so running
    # more paths stays legitimate while changing the switch itself does not.
    if STAGE:
        stage_record = dict(STAGE)
        stage_record.update({
            "number_of_paths": len(completed),
            "stage_config_sha256": stage_config_sha256(STAGE),
            "stage_invariant_sha256": stage_invariant_sha256(STAGE),
        })
        (HERE / "resolved_stage.yaml").write_text(
            yaml.safe_dump(stage_record, sort_keys=False, default_flow_style=False),
            encoding="utf-8")

    provenance = {
        "format": "md-templates-ais-provenance/v1",
        "created_utc": utc_now(),
        "implementation": CONFIG.get("provenance"),
        "environment": environment_versions(),
        "parent_system": {
            "inputs_folder": CONFIG["paths"]["inputs_folder"],
            "input_hashes": {name: sha256_file(INPUTS / name)
                             for name in ("system.xml", "topology.pdb", "solute.yaml",
                                          "initial_state.xml", "resolved_sys.config.yaml")
                             if (INPUTS / name).is_file()},
            "forcefield": _forcefield_identity(),
        },
        "source_trajectory": plan["source"],
        "path": PATH_DEFINITION["path"],
        "schedule": SCHEDULE,
        "work_convention": PATH_DEFINITION["work_convention"],
        "ensemble": PATH_DEFINITION["ensemble"],
        "seeds": {"base": BASE_SEED,
                  "source_selection": plan["source"]["selection_seed"],
                  "per_trajectory": {entry["ais_trajectory_index"]:
                                     {"integrator": entry["integrator_seed"],
                                      "velocities": entry["velocity_seed"]}
                                     for entry in plan["trajectories"]}},
        "gpu_assignment": {entry["ais_trajectory_index"]: entry["gpu_device"]
                           for entry in plan["trajectories"]},
        "completed_trajectory_indices": completed,
        "failed_trajectory_indices": failed,
        "pending_trajectory_indices": [],
        "limitations": LIMITATIONS,
    }
    (HERE / "provenance.yaml").write_text(
        yaml.safe_dump(provenance, sort_keys=False, default_flow_style=False), encoding="utf-8")

    # The plan is scratch and goes. The prepared inputs STAY: they are what the paths started
    # from, and a result archived without them cannot say what it annealed away from.
    (HERE / PLAN_NAME).unlink(missing_ok=True)
    if total_work:
        print(f"[AIS] {len(completed)}/{count} path(s) complete; total work "
              f"{min(total_work):.3f} to {max(total_work):.3f} kJ/mol", flush=True)
    if failed:
        print(f"[AIS] FAILED path(s): {failed}. See resolved_run.yaml.", flush=True)
        return 1
    return 0


def _forcefield_identity():
    """What the System was parameterised with, copied from the prepared inputs."""
    record = INPUTS / "forcefield.json"
    if not record.is_file():
        return None
    try:
        data = json.loads(record.read_text())
    except Exception:
        return None
    return {key: data.get(key) for key in ("route", "solvation", "protein", "ligand", "water",
                                           "nonbonded", "constraints")}


if __name__ == "__main__":
    raise SystemExit(main())
