#!/usr/bin/env python
"""Conventional MD production. Generated by md-openmm; edit freely.

This stage does NOT minimise or equilibrate. It starts from the finalized state of the last common
equilibration stage -- the same state `REST2/equilibrate.py` starts from, so the two production
methods are siblings and neither has to run before the other.

    input  : ../<last common stage>/final_state.xml
    output : whole_system.dcd, solute.dcd, production.csv, production.chk, final_state.xml

Restarting: run it again. The checkpoint is loaded -- which restores the RNG state, so velocities
are NOT regenerated -- and the reporters append.

Every path is relative to this script, so moving `inputs/` and `MD/` together is enough.
"""
import os
import sys
from pathlib import Path

import yaml
from openmm import unit
from openmm.app import CheckpointReporter, DCDReporter, PDBFile, StateDataReporter

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
from md_stages import (PRODUCTION_BAROSTAT_FREQUENCY, active_barostat_count, build_stage_system,
                       count_barostats, derive_seed, make_simulation, require_parent_state,
                       resolve_platform, restraint_strength, set_barostat_frequency, set_restraint,
                       steps_for, write_final_state)

CONFIG = yaml.safe_load((HERE.parent / "md.config.yaml").read_text())
INPUTS = (HERE.parent / CONFIG["paths"]["inputs_folder"]).resolve()
SOLUTE = yaml.safe_load((INPUTS / "solute.yaml").read_text())
BRANCH = CONFIG["paths"]["common_final_state"]        # e.g. ../eq3_npt_free/final_state.xml
PARENT_STAGE = CONFIG["paths"]["common_final_stage"]

common = CONFIG["common"]
method = CONFIG["cMD"]
implicit = common.get("pressure_bar") is None

TEMPERATURE = float(common["temperature_kelvin"]) * unit.kelvin
TIMESTEP_FS = float(common["timestep_fs"])
FRICTION = float(common["friction_per_ps"]) / unit.picosecond
BASE_SEED = int(common["random_seed"]) if common.get("random_seed") is not None else 20260825
SOLUTE_INDICES = list(range(int(SOLUTE["n_solute_atoms"])))


def main():
    platform_name = resolve_platform(os.environ.get("MD_PLATFORM") or None)
    device = os.environ.get("MD_DEVICE")
    print(f"[cMD] platform {platform_name}"
          + (f", CUDA device {device}" if platform_name == "CUDA" and device else ""))

    seeds = {name: derive_seed(BASE_SEED, "cMD", name)
             for name in ("integrator", "velocities", "barostat")}
    system = build_stage_system(INPUTS, implicit=implicit, restrained=False,
                                barostat_active=not implicit,
                                pressure_bar=common.get("pressure_bar"), temperature=TEMPERATURE,
                                barostat_seed=seeds["barostat"], solute_indices=SOLUTE_INDICES)
    pdb = PDBFile(str(INPUTS / "topology.pdb"))
    simulation = make_simulation(pdb.topology, system, temperature=TEMPERATURE, friction=FRICTION,
                                 timestep=TIMESTEP_FS * unit.femtoseconds,
                                 seed=seeds["integrator"], platform_name=platform_name,
                                 device=device)
    print(f"[cMD] seeds: {seeds}")

    checkpoint = HERE / "production.chk"
    resuming = checkpoint.is_file()
    if resuming:
        # The barostat frequency lives in the System, not the checkpoint, so the production layout
        # is set before loading. loadCheckpoint then restores the integrator RNG state.
        if not implicit:
            set_barostat_frequency(simulation, PRODUCTION_BAROSTAT_FREQUENCY)
        simulation.loadCheckpoint(str(checkpoint))
        done = simulation.context.getStepCount()
        print(f"[cMD] resuming from production.chk at step {done:,}")
    else:
        simulation.context.setState(require_parent_state(
            (HERE / BRANCH).resolve(), stage_name=PARENT_STAGE, command=f"../{PARENT_STAGE}"))
        simulation.context.setStepCount(0)
        done = 0
        print(f"[cMD] started from ../{PARENT_STAGE}/final_state.xml")

    set_restraint(simulation, 0.0)                    # production is unrestrained
    active = active_barostat_count(simulation)
    print(f"[cMD] restraint {restraint_strength(simulation):g} kJ/mol/nm^2, "
          f"{active} active barostat(s), {count_barostats(system)} in the System")
    if implicit and count_barostats(system):
        raise SystemExit("implicit solvent must have no barostat")

    total = steps_for(float(method["duration_ns"]) * 1000.0, TIMESTEP_FS)
    remaining = total - done
    if remaining <= 0:
        print(f"[cMD] already complete: {done:,} of {total:,} steps")
        return 0

    whole_every = steps_for(float(method["whole_system_interval_ps"]), TIMESTEP_FS)
    solute_every = steps_for(float(method["solute_interval_ps"]), TIMESTEP_FS)
    checkpoint_every = steps_for(float(method["checkpoint_interval_ps"]), TIMESTEP_FS)

    whole = HERE / "whole_system.dcd"
    solute = HERE / "solute.dcd"
    table = HERE / "production.csv"
    simulation.reporters.append(DCDReporter(str(whole), whole_every,
                                            append=resuming and whole.is_file()))
    simulation.reporters.append(DCDReporter(str(solute), solute_every,
                                            append=resuming and solute.is_file(),
                                            atomSubset=SOLUTE_INDICES))
    simulation.reporters.append(CheckpointReporter(str(checkpoint), checkpoint_every))
    simulation.reporters.append(StateDataReporter(
        str(table), solute_every, step=True, time=True, potentialEnergy=True, temperature=True,
        volume=not implicit, speed=True, append=resuming and table.is_file()))
    simulation.reporters.append(StateDataReporter(
        sys.stdout, whole_every, step=True, time=True, potentialEnergy=True, temperature=True,
        speed=True))

    print(f"[cMD] {method['ensemble']}, {remaining:,} of {total:,} steps "
          f"({method['duration_ns']} ns at {TIMESTEP_FS} fs)")
    simulation.step(remaining)

    simulation.saveCheckpoint(str(checkpoint))
    write_final_state(simulation, HERE / "final_state.xml")
    print(f"[cMD] complete: {simulation.context.getStepCount():,} steps")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
