#!/usr/bin/env python
"""Conventional MD production, on one fixed rung of the REST2 ladder. Generated by md-openmm.

This stage does NOT minimise or equilibrate. It starts from the finalized state of the last common
equilibration stage -- the same state `REST2/equilibrate.py` starts from, so the two production
methods are siblings and neither has to run before the other.

`cMD.tau` selects the rung. tau = 0 is ordinary conventional MD: `build_scaled_system` returns the
System unmodified, so the trajectory is bit-for-bit the one this script produced before tau
existed. tau > 0 scales the solute Hamiltonian through the SAME `rest2_scaling` module the ladder
uses, giving a single autonomous walker whose Hamiltonian is identical to the REST2 rung at that
tau -- but with no replicas, no exchange, and no coupling to anything.

This is NOT high-temperature MD. The thermostat stays at `common.temperature_kelvin` and beta is
unchanged; only the solute Hamiltonian is scaled. An "effective solute temperature" is a way of
describing that scaling, not a second thermostat.

    input  : ../<last common stage>/final_state.xml
    output : whole_system.dcd, solute.dcd, production.csv, production.chk, final_state.xml

Restarting: run it again. The checkpoint is loaded -- which restores the RNG state, so velocities
are NOT regenerated -- and the reporters append.

Every path is relative to this script, so moving `inputs/` and `MD/` together is enough.
"""
import os
import sys
from pathlib import Path

import yaml
from openmm import unit
from openmm.app import CheckpointReporter, DCDReporter, PDBFile, StateDataReporter

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
sys.path.insert(0, str(HERE))
from md_stages import (PRODUCTION_BAROSTAT_FREQUENCY, active_barostat_count, build_stage_system,
                       count_barostats, derive_seed, make_simulation, require_parent_state,
                       resolve_platform, restraint_strength, set_barostat_frequency, set_restraint,
                       steps_for, trim_to_checkpoint, write_final_state,
                       write_yaml_atomic)
from rest2_scaling import build_scaled_system, scale_factor_for_tau

CONFIG = yaml.safe_load((HERE.parent / "md.config.yaml").read_text())
INPUTS = (HERE.parent / CONFIG["paths"]["inputs_folder"]).resolve()
SOLUTE = yaml.safe_load((INPUTS / "solute.yaml").read_text())
BRANCH = CONFIG["paths"]["common_final_state"]        # e.g. ../eq3_npt_free/final_state.xml
PARENT_STAGE = CONFIG["paths"]["common_final_stage"]

common = CONFIG["common"]
method = CONFIG["cMD"]
implicit = common.get("pressure_bar") is None

TEMPERATURE = float(common["temperature_kelvin"]) * unit.kelvin
TIMESTEP_FS = float(common["timestep_fs"])
FRICTION = float(common["friction_per_ps"]) / unit.picosecond
BASE_SEED = int(common["random_seed"]) if common.get("random_seed") is not None else 20260825
SOLUTE_INDICES = list(range(int(SOLUTE["n_solute_atoms"])))
TAU = float(method.get("tau", 0.0) or 0.0)
# Read from solute.yaml, which sys-gen wrote from the topology: the same list REST2 uses, so the
# two cannot disagree about which torsions are omega.
OMEGA_EXCLUDED = (SOLUTE["rest2"]["omega_excluded_bonds"]
                  if method.get("omega_exclusion", True) else [])


def main():
    platform_name = resolve_platform(os.environ.get("MD_PLATFORM") or None)
    device = os.environ.get("MD_DEVICE")
    print(f"[cMD] platform {platform_name}"
          + (f", CUDA device {device}" if platform_name == "CUDA" and device else ""))

    seeds = {name: derive_seed(BASE_SEED, "cMD", name)
             for name in ("integrator", "velocities", "barostat")}
    scale = None
    if TAU:
        # Bound the walker to the ladder's own implementation rather than a second copy of the
        # formula. At tau = 0 no scaler is installed at all, so the System is untouched.
        scale = (lambda base: build_scaled_system(base, SOLUTE_INDICES, TAU, OMEGA_EXCLUDED))
    system = build_stage_system(INPUTS, implicit=implicit, restrained=False,
                                barostat_active=not implicit,
                                pressure_bar=common.get("pressure_bar"), temperature=TEMPERATURE,
                                barostat_seed=seeds["barostat"], solute_indices=SOLUTE_INDICES,
                                scale_system=scale)
    if TAU:
        print(f"[cMD] fixed tau = {TAU:g}, s = {scale_factor_for_tau(TAU):.6f}, "
              f"sqrt(s) = {1.0 - TAU:.6f}, {len(OMEGA_EXCLUDED)} omega bond(s) unscaled")
        print(f"[cMD] thermostat stays at {TEMPERATURE}; this is Hamiltonian scaling, "
              "not high-temperature MD")
    else:
        print("[cMD] tau = 0: the unscaled physical Hamiltonian")
    pdb = PDBFile(str(INPUTS / "topology.pdb"))
    simulation = make_simulation(pdb.topology, system, temperature=TEMPERATURE, friction=FRICTION,
                                 timestep=TIMESTEP_FS * unit.femtoseconds,
                                 seed=seeds["integrator"], platform_name=platform_name,
                                 device=device)
    print(f"[cMD] seeds: {seeds}")

    total = steps_for(float(method["duration_ns"]) * 1000.0, TIMESTEP_FS)
    whole_every = steps_for(float(method["whole_system_interval_ps"]), TIMESTEP_FS)
    solute_every = steps_for(float(method["solute_interval_ps"]), TIMESTEP_FS)
    checkpoint_every = steps_for(float(method["checkpoint_interval_ps"]), TIMESTEP_FS)

    checkpoint = HERE / "production.chk"
    resuming = checkpoint.is_file()
    if resuming:
        # The barostat frequency lives in the System, not the checkpoint, so the production layout
        # is set before loading. loadCheckpoint then restores the integrator RNG state.
        if not implicit:
            set_barostat_frequency(simulation, PRODUCTION_BAROSTAT_FREQUENCY)
        simulation.loadCheckpoint(str(checkpoint))
        done = simulation.context.getStepCount()
        print(f"[cMD] resuming from production.chk at step {done:,}")
        # The checkpoint is the authority for where this stage is. Anything the reporters wrote
        # past it is an uncommitted tail from the interrupted invocation, and appending after it
        # would duplicate those frames and break the monotonic step column.
        kept = trim_to_checkpoint(HERE, done, whole_every=whole_every,
                                  solute_every=solute_every, table_every=solute_every)
        print(f"[cMD] trimmed to the checkpoint: "
              + ", ".join(f"{name} -> {n}" for name, n in kept.items()))
    else:
        simulation.context.setState(require_parent_state(
            (HERE / BRANCH).resolve(), stage_name=PARENT_STAGE, command=f"../{PARENT_STAGE}"))
        simulation.context.setStepCount(0)
        done = 0
        print(f"[cMD] started from ../{PARENT_STAGE}/final_state.xml")

    set_restraint(simulation, 0.0)                    # production is unrestrained
    active = active_barostat_count(simulation)
    print(f"[cMD] restraint {restraint_strength(simulation):g} kJ/mol/nm^2, "
          f"{active} active barostat(s), {count_barostats(system)} in the System")
    if implicit and count_barostats(system):
        raise SystemExit("implicit solvent must have no barostat")

    remaining = total - done
    if remaining <= 0:
        print(f"[cMD] already complete: {done:,} of {total:,} steps")
        return 0

    whole = HERE / "whole_system.dcd"
    solute = HERE / "solute.dcd"
    table = HERE / "production.csv"
    simulation.reporters.append(DCDReporter(str(whole), whole_every,
                                            append=resuming and whole.is_file()))
    simulation.reporters.append(DCDReporter(str(solute), solute_every,
                                            append=resuming and solute.is_file(),
                                            atomSubset=SOLUTE_INDICES))
    simulation.reporters.append(CheckpointReporter(str(checkpoint), checkpoint_every))
    simulation.reporters.append(StateDataReporter(
        str(table), solute_every, step=True, time=True, potentialEnergy=True, temperature=True,
        volume=not implicit, speed=True, append=resuming and table.is_file()))
    simulation.reporters.append(StateDataReporter(
        sys.stdout, whole_every, step=True, time=True, potentialEnergy=True, temperature=True,
        speed=True))

    print(f"[cMD] {method['ensemble']}, {remaining:,} of {total:,} steps "
          f"({method['duration_ns']} ns at {TIMESTEP_FS} fs)")
    simulation.step(remaining)

    simulation.saveCheckpoint(str(checkpoint))
    write_final_state(simulation, HERE / "final_state.xml")
    # What actually ran, beside the outputs it produced. tau is the source parameter; s and sqrt(s)
    # are labelled derived so nothing downstream can feed them back in as inputs.
    write_yaml_atomic(HERE / "resolved_stage.yaml", {
        "kind": "fixed_tau_md" if TAU else "conventional_md",
        "ensemble": method["ensemble"],
        "tau": TAU,
        "derived_scale_factor_s": scale_factor_for_tau(TAU),
        "derived_solute_environment_coupling_sqrt_s": 1.0 - TAU,
        "omega_exclusion": bool(method.get("omega_exclusion", True)) and bool(TAU),
        "omega_excluded_bonds": [list(map(int, b)) for b in OMEGA_EXCLUDED] if TAU else [],
        "temperature_kelvin": float(common["temperature_kelvin"]),
        "timestep_fs": TIMESTEP_FS,
        "duration_ns": float(method["duration_ns"]),
        "total_steps": int(simulation.context.getStepCount()),
        "seeds": seeds,
        "input_state": f"../{PARENT_STAGE}/final_state.xml",
        "output_state": "final_state.xml",
    })
    print(f"[cMD] complete: {simulation.context.getStepCount():,} steps")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
