#!/usr/bin/env python
"""Conventional MD. Generated by md-openmm; edit freely -- nothing regenerates this file.

Fresh run:

    restrained minimization -> restrained NVT -> restrained NPT -> unrestrained production

Under implicit solvent there is no box, so there is no barostat and no NPT stage; production is NVT.

Restarting: run it again. Equilibration is skipped, the checkpoint is loaded -- which restores the
RNG state, so velocities are NOT regenerated -- and the reporters append.

Every path is relative to this script, so moving `inputs/` and `MD/` together is enough.
"""
import os
import sys
from pathlib import Path

import yaml
from openmm import XmlSerializer, unit
from openmm.app import CheckpointReporter, DCDReporter, PDBFile, StateDataReporter

sys.path.insert(0, str(Path(__file__).resolve().parent))
from md_stages import (add_barostat, add_positional_restraint, count_barostats, derive_seed,
                       equilibrate, make_simulation, resolve_platform, resume_production,
                       steps_for)

HERE = Path(__file__).resolve().parent
CONFIG = yaml.safe_load((HERE.parent / "md.config.yaml").read_text())
INPUTS = (HERE.parent / CONFIG["paths"]["inputs_folder"]).resolve()
SOLUTE = yaml.safe_load((INPUTS / "solute.yaml").read_text())

common = CONFIG["common"]
method = CONFIG["cMD"]
implicit = common.get("pressure_bar") is None

TEMPERATURE = float(common["temperature_kelvin"]) * unit.kelvin
TIMESTEP_FS = float(common["timestep_fs"])
TIMESTEP = TIMESTEP_FS * unit.femtoseconds
FRICTION = float(common["friction_per_ps"]) / unit.picosecond
BASE_SEED = int(common["random_seed"]) if common.get("random_seed") is not None else 20260825
SOLUTE_INDICES = list(range(int(SOLUTE["n_solute_atoms"])))


def main():
    platform_name = resolve_platform(os.environ.get("MD_PLATFORM") or None)
    device = os.environ.get("MD_DEVICE")
    print(f"[cMD] platform {platform_name}"
          + (f", CUDA device {device}" if platform_name == "CUDA" and device else ""))
    pdb = PDBFile(str(INPUTS / "topology.pdb"))
    system = XmlSerializer.deserialize((INPUTS / "system.xml").read_text())
    initial = XmlSerializer.deserialize((INPUTS / "initial_state.xml").read_text())

    # The Force layout must be identical on a fresh run and a restart, or a checkpoint written by
    # one cannot be loaded by the other. Both branches build it here, before any state is loaded.
    add_positional_restraint(system, initial.getPositions(), SOLUTE_INDICES)
    if not implicit:
        add_barostat(system, common["pressure_bar"], TEMPERATURE,
                     derive_seed(BASE_SEED, "cMD", "barostat"), frequency=0)
    barostats = count_barostats(system)
    if implicit and barostats:
        raise SystemExit(f"implicit solvent must have no barostat; found {barostats}")

    integrator_seed = derive_seed(BASE_SEED, "cMD", "integrator")
    velocity_seed = derive_seed(BASE_SEED, "cMD", "velocities")
    simulation = make_simulation(pdb.topology, system, temperature=TEMPERATURE,
                                 friction=FRICTION, timestep=TIMESTEP, seed=integrator_seed,
                                 platform_name=platform_name, device=device)
    print(f"[cMD] seeds: integrator {integrator_seed}, velocities {velocity_seed}"
          + ("" if implicit else
             f", barostat {derive_seed(BASE_SEED, 'cMD', 'barostat')}"))

    checkpoint = HERE / "production.chk"
    resuming = checkpoint.is_file()
    if resuming:
        # loadCheckpoint restores the integrator RNG state too, so velocities are NOT regenerated.
        record = resume_production(simulation, checkpoint, implicit=implicit)
        done = record["resumed_at_step"]
        print(f"[cMD] resuming from {checkpoint.name} at step {done:,}; equilibration skipped, "
              f"{record['barostats_active_production']} active barostat(s)")
    else:
        simulation.context.setState(initial)
        record = equilibrate(simulation, config=CONFIG, implicit=implicit,
                             temperature=TEMPERATURE, timestep_fs=TIMESTEP_FS,
                             velocity_seed=velocity_seed,
                             log=lambda m: print(f"[cMD] {m}"), label="")
        (HERE / "equilibration.yaml").write_text(yaml.safe_dump(record, sort_keys=False))
        done = 0

    total = steps_for(float(method["duration_ns"]) * 1000.0, TIMESTEP_FS)
    remaining = total - done
    if remaining <= 0:
        print(f"[cMD] already complete: {done:,} of {total:,} steps")
        return 0

    whole_every = steps_for(float(method["whole_system_interval_ps"]), TIMESTEP_FS)
    solute_every = steps_for(float(method["solute_interval_ps"]), TIMESTEP_FS)
    checkpoint_every = steps_for(float(method["checkpoint_interval_ps"]), TIMESTEP_FS)

    simulation.reporters.append(DCDReporter(str(HERE / "whole_system.dcd"), whole_every,
                                            append=resuming))
    simulation.reporters.append(DCDReporter(str(HERE / "solute.dcd"), solute_every,
                                            append=resuming, atomSubset=SOLUTE_INDICES))
    simulation.reporters.append(CheckpointReporter(str(checkpoint), checkpoint_every))
    simulation.reporters.append(StateDataReporter(
        str(HERE / "production.csv"), solute_every, step=True, time=True,
        potentialEnergy=True, temperature=True, volume=not implicit, speed=True,
        append=resuming))
    simulation.reporters.append(StateDataReporter(
        sys.stdout, whole_every, step=True, time=True, potentialEnergy=True,
        temperature=True, speed=True))

    print(f"[cMD] {method['ensemble']}, {remaining:,} of {total:,} steps "
          f"({method['duration_ns']} ns at {TIMESTEP_FS} fs)")
    simulation.step(remaining)

    simulation.saveCheckpoint(str(checkpoint))
    final = simulation.context.getState(getPositions=True, getVelocities=True)
    (HERE / "final_state.xml").write_text(XmlSerializer.serialize(final))
    print(f"[cMD] complete: {simulation.context.getStepCount():,} steps")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
