#!/usr/bin/env bash
# Add REST2 EXCHANGE PRODUCTION segments to a run that already exists. Generated by md-openmm.
#
#   ./extend.sh        # one more segment
#   ./extend.sh 3      # three more
#
# This continues from each replica's production checkpoint under replica_NN/production/ and
# APPENDS to exchange_attempts.csv. It does not re-minimise, does not repeat the common
# equilibration, and does not repeat the per-tau equilibration: doing any of those would discard
# the trajectory this run has already produced.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

N="${1:-1}"
if [ ! -f exchange_attempts.csv ]; then
    echo "no exchange production to extend here. Run ./equilibrate.sh then ./run.sh first." >&2
    exit 1
fi
for (( i=1; i<=N; i++ )); do
    echo "== REST2 exchange production, extension segment $i/$N =="
    ./run.sh
done
