#!/usr/bin/env bash
# Add REST2 segments to a run that already exists. Generated by md-openmm.
#
#   ./extend.sh        # one more segment
#   ./extend.sh 3      # three more
#
# This continues from each replica's checkpoint and APPENDS to exchange_attempts.csv. It does not
# re-minimise: doing so would discard the trajectory this run has already produced.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

N="${1:-1}"
if [ ! -f exchange_attempts.csv ]; then
    echo "no run to extend here; use ./run.sh first." >&2
    exit 1
fi
for (( i=1; i<=N; i++ )); do
    echo "== REST2 extension segment $i/$N =="
    ./run.sh
done
