#!/usr/bin/env python
"""REST2 replica exchange. Generated by md-openmm; edit freely.

One replica per rung of a tau ladder. The solute Hamiltonian is scaled by `rest2_scaling.py` beside
this file; the environment is untouched.

Every replica is thermostatted at the SAME physical temperature and therefore shares one beta. The
rungs differ by Hamiltonian, not by thermostat, which is what makes this REST2 rather than parallel
tempering, and it is why the pV terms cancel in the NPT acceptance criterion.

Fresh run, per replica:

    restrained minimization -> restrained NVT -> restrained NPT -> unrestrained production

then `number_of_exchanges` rounds of

    propagate every replica for duration_per_segment_ps -> attempt neighbour exchanges

so one invocation advances each replica by `duration_per_segment_ps * number_of_exchanges`.

Restarting: run it again, or ./extend.sh N. Each replica keeps its own checkpoint, equilibration is
not repeated, and the exchange history is appended, never rewritten.
"""
import csv
import math
import os
import random
import sys
from pathlib import Path

import yaml
from openmm import XmlSerializer, unit
from openmm.app import CheckpointReporter, DCDReporter, PDBFile, StateDataReporter

sys.path.insert(0, str(Path(__file__).resolve().parent))
from md_stages import (add_barostat, add_positional_restraint, count_barostats, derive_seed,
                       device_groups, equilibrate, make_simulation, propagate_segment,
                       resolve_platform, resume_production, steps_for)
from rest2_scaling import (build_scaled_system, exchange_log_acceptance, exchange_pairs,
                           linear_tau_ladder, reduced_potential, scale_factor_for_tau)

HERE = Path(__file__).resolve().parent
CONFIG = yaml.safe_load((HERE.parent / "md.config.yaml").read_text())
INPUTS = (HERE.parent / CONFIG["paths"]["inputs_folder"]).resolve()
SOLUTE = yaml.safe_load((INPUTS / "solute.yaml").read_text())

common = CONFIG["common"]
method = CONFIG["REST2"]
implicit = common.get("pressure_bar") is None

TEMPERATURE = float(common["temperature_kelvin"]) * unit.kelvin
TIMESTEP_FS = float(common["timestep_fs"])
TIMESTEP = TIMESTEP_FS * unit.femtoseconds
FRICTION = float(common["friction_per_ps"]) / unit.picosecond
BASE_SEED = int(common["random_seed"]) if common.get("random_seed") is not None else 20260101
KB_KJ = 0.008314462618            # kJ/mol/K
BETA = 1.0 / (KB_KJ * float(common["temperature_kelvin"]))

N_REPLICAS = int(method["number_of_replicas"])
SOLUTE_INDICES = list(range(int(SOLUTE["n_solute_atoms"])))
EXCHANGE_LOG = HERE / "exchange_attempts.csv"


def required_steps(name):
    """An interval from the REST2 block, in steps. A missing one is named, not guessed."""
    if method.get(name) is None:
        raise SystemExit(
            f"REST2.{name} is missing from md.config.yaml. Regenerate the protocol with "
            f"`md-openmm sys-config` and reapply your edits, or add the key by hand.")
    return steps_for(float(method[name]), TIMESTEP_FS)


def visible_devices():
    """The CUDA devices this process may use, honouring CUDA_VISIBLE_DEVICES.

    No busy detection and no scheduler: at most min(n_replicas, n_visible) devices are used, and
    replicas are assigned round-robin so the mapping is reproducible.
    """
    raw = os.environ.get("CUDA_VISIBLE_DEVICES")
    if raw is not None:
        tokens = [t.strip() for t in raw.split(",") if t.strip()]
        return list(range(len(tokens)))            # logical indices, which is what OpenMM takes
    try:
        import subprocess
        out = subprocess.run(["nvidia-smi", "--query-gpu=index", "--format=csv,noheader"],
                             capture_output=True, text=True, timeout=15)
        if out.returncode == 0:
            return list(range(len([l for l in out.stdout.splitlines() if l.strip()])))
    except Exception:
        pass
    return []


def build_replica(replica, tau, base, topology, initial, device, platform_name):
    """One rung: the scaled system, the restraint, the barostat, and its own seeds."""
    system = build_scaled_system(base, SOLUTE_INDICES, tau,
                                 SOLUTE["rest2"]["omega_excluded_bonds"]
                                 if method.get("omega_exclusion") else [])
    # Built before any state is loaded, and identically on a fresh run and a restart: a checkpoint
    # written by one layout cannot be loaded into another.
    add_positional_restraint(system, initial.getPositions(), SOLUTE_INDICES)
    if not implicit:
        add_barostat(system, common["pressure_bar"], TEMPERATURE,
                     derive_seed(BASE_SEED, "REST2", replica, "barostat"), frequency=0)
    barostats = count_barostats(system)
    if implicit and barostats:
        raise SystemExit(f"implicit solvent must have no barostat; replica {replica} has "
                         f"{barostats}")

    seeds = {name: derive_seed(BASE_SEED, "REST2", replica, name)
             for name in ("integrator", "velocities", "barostat")}
    simulation = make_simulation(topology, system, temperature=TEMPERATURE, friction=FRICTION,
                                 timestep=TIMESTEP, seed=seeds["integrator"],
                                 platform_name=platform_name, device=device)
    return simulation, seeds


def attach_reporters(simulation, replica, *, resuming, whole_every, solute_every,
                     checkpoint_every):
    """Whole-system and solute-subset trajectories, a log, and a checkpoint, per replica.

    The solute DCD is an atom subset, so it is read against `inputs/solute.pdb` rather than the
    whole-system topology. Both are written from the same indices `sys-gen` recorded.
    """
    whole = HERE / f"replica_{replica:02d}_whole.dcd"
    solute = HERE / f"replica_{replica:02d}_solute.dcd"
    table = HERE / f"replica_{replica:02d}.csv"
    checkpoint = HERE / f"replica_{replica:02d}.chk"
    simulation.reporters.append(DCDReporter(str(whole), whole_every,
                                            append=resuming and whole.is_file()))
    simulation.reporters.append(DCDReporter(str(solute), solute_every,
                                            append=resuming and solute.is_file(),
                                            atomSubset=SOLUTE_INDICES))
    simulation.reporters.append(CheckpointReporter(str(checkpoint), checkpoint_every))
    simulation.reporters.append(StateDataReporter(
        str(table), solute_every, step=True, time=True, potentialEnergy=True, temperature=True,
        volume=not implicit, speed=True, append=resuming and table.is_file()))


def main():
    pdb = PDBFile(str(INPUTS / "topology.pdb"))
    base = XmlSerializer.deserialize((INPUTS / "system.xml").read_text())
    initial = XmlSerializer.deserialize((INPUTS / "initial_state.xml").read_text())
    excluded = SOLUTE["rest2"]["omega_excluded_bonds"] if method.get("omega_exclusion") else []

    taus = linear_tau_ladder(float(method["tau_min"]), float(method["tau_max"]), N_REPLICAS)
    platform_name = resolve_platform(os.environ.get("MD_PLATFORM") or None)
    # A non-CUDA platform uses no device, and saying otherwise would misreport which hardware
    # produced the trajectory.
    devices = visible_devices() if platform_name == "CUDA" else []
    if platform_name == "CUDA" and not devices:
        # The platform exists, so there is a device; only the enumeration failed.
        devices = [0]
    groups = device_groups(N_REPLICAS, devices)
    device_of = {replica: (devices[index] if devices else None)
                 for index, group in enumerate(groups) for replica in group}

    print(f"[remd] {N_REPLICAS} replicas, tau {taus[0]:.3f}..{taus[-1]:.3f}, "
          f"s = {[round(scale_factor_for_tau(t), 4) for t in taus]}")
    print(f"[remd] one temperature ({common['temperature_kelvin']} K) and one beta for every "
          f"replica; the rungs differ by Hamiltonian")
    print(f"[remd] {len(excluded)} omega bond(s) excluded from torsion scaling")
    if devices:
        shape = ("devices propagate concurrently, replicas sharing one device propagate in turn"
                 if len(groups) > 1 else "all replicas share it, so they propagate in turn")
        print(f"[remd] platform {platform_name}: {len(groups)} GPU(s) of {len(devices)} visible, "
              f"replicas per device {[list(g) for g in groups]}; {shape}")
    else:
        print(f"[remd] platform {platform_name}: no CUDA device, replicas propagate sequentially")

    resuming = EXCHANGE_LOG.is_file()
    if resuming:
        missing = [r for r in range(N_REPLICAS) if not (HERE / f"replica_{r:02d}.chk").is_file()]
        if missing:
            raise SystemExit(
                f"{EXCHANGE_LOG.name} records a run but replica checkpoint(s) {missing} are "
                "missing. Refusing to re-equilibrate into an existing history.")

    whole_every = required_steps("whole_system_interval_ps")
    solute_every = required_steps("solute_interval_ps")
    checkpoint_every = required_steps("checkpoint_interval_ps")

    simulations = []
    for replica, tau in enumerate(taus):
        simulation, seeds = build_replica(replica, tau, base, pdb.topology, initial,
                                          device_of.get(replica), platform_name)
        checkpoint = HERE / f"replica_{replica:02d}.chk"
        if checkpoint.is_file():
            record = resume_production(simulation, checkpoint, implicit=implicit)
            print(f"[remd] replica {replica}: resumed at step "
                  f"{record['resumed_at_step']:,}, equilibration skipped, "
                  f"{record['barostats_active_production']} active barostat(s)")
        else:
            simulation.context.setState(initial)
            record = equilibrate(
                simulation, config=CONFIG, implicit=implicit,
                temperature=TEMPERATURE, timestep_fs=TIMESTEP_FS,
                velocity_seed=seeds["velocities"], log=lambda m: print(f"[remd] {m}"),
                label=f"replica {replica}")
            (HERE / f"replica_{replica:02d}_equilibration.yaml").write_text(
                yaml.safe_dump({"tau": tau, "seeds": seeds, **record}, sort_keys=False))
        print(f"[remd] replica {replica}: tau {tau:.3f}, seeds {seeds}, "
              f"device {device_of.get(replica)}")
        attach_reporters(simulation, replica, resuming=checkpoint.is_file(),
                         whole_every=whole_every, solute_every=solute_every,
                         checkpoint_every=checkpoint_every)
        simulations.append(simulation)

    attempt_index = 0
    if resuming:
        with EXCHANGE_LOG.open() as handle:
            rows = list(csv.DictReader(handle))
        attempt_index = (int(rows[-1]["attempt_index"]) + 1) if rows else 0
        print(f"[remd] resuming: {attempt_index} exchange round(s) already recorded")
    else:
        with EXCHANGE_LOG.open("w", newline="") as handle:
            csv.writer(handle).writerow(
                ["attempt_index", "phase", "step", "time_ps", "replica_i", "replica_j",
                 "log_acceptance", "accepted"])

    # duration_per_segment_ps is the time BETWEEN consecutive exchange rounds, so the invocation
    # runs segment_steps * number_of_exchanges per replica. Dividing one segment among the rounds
    # instead -- which this script used to do -- ran the whole ladder for a single segment.
    segment_steps = steps_for(float(method["duration_per_segment_ps"]), TIMESTEP_FS)
    n_exchanges = int(method["number_of_exchanges"])
    if n_exchanges < 1:
        raise SystemExit(f"REST2.number_of_exchanges must be at least 1; got {n_exchanges}")
    total_ps = float(method["duration_per_segment_ps"]) * n_exchanges
    print(f"[remd] {n_exchanges} rounds x {segment_steps:,} steps "
          f"({method['duration_per_segment_ps']} ps) = {segment_steps * n_exchanges:,} steps "
          f"= {total_ps:g} ps per replica this invocation")

    rng = random.Random(derive_seed(BASE_SEED, "REST2", "exchange", attempt_index))
    accepted_total = 0
    attempted_total = 0
    for _ in range(n_exchanges):
        propagate_segment(groups, lambda replica: simulations[replica].step(segment_steps))

        phase = attempt_index % 2
        pairs = exchange_pairs(N_REPLICAS, phase)
        if not pairs:
            # A two-replica ladder has no pair on phase 1. Alternating regardless would exchange on
            # every other round only, and a run resumed on an odd index would keep landing there.
            phase = (phase + 1) % 2
            pairs = exchange_pairs(N_REPLICAS, phase)
        if not pairs:
            raise SystemExit(f"{N_REPLICAS} replicas offer no exchange pair in either phase")

        rows = []
        for i, j in pairs:
            state_i = simulations[i].context.getState(getEnergy=True)
            state_j = simulations[j].context.getState(getEnergy=True)
            energy_i = state_i.getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
            energy_j = state_j.getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
            volume_i = volume_j = None
            pressure = None if implicit else float(common["pressure_bar"])
            if not implicit:
                volume_i = state_i.getPeriodicBoxVolume().value_in_unit(unit.nanometer ** 3)
                volume_j = state_j.getPeriodicBoxVolume().value_in_unit(unit.nanometer ** 3)

            # Cross energies: evaluate replica i's CONFIGURATION in replica j's Hamiltonian.
            #
            # The box travels with the coordinates. Under NPT each replica has its own volume, so
            # putting i's positions into j's context while j's box is still in place evaluates a
            # configuration in a box it does not fit -- overlapping images, enormous energies, and
            # an acceptance that is always zero. A configuration is positions AND the cell they
            # are periodic in.
            full_i = simulations[i].context.getState(getPositions=True)
            full_j = simulations[j].context.getState(getPositions=True)
            positions_i, box_i = full_i.getPositions(), full_i.getPeriodicBoxVectors()
            positions_j, box_j = full_j.getPositions(), full_j.getPeriodicBoxVectors()

            simulations[j].context.setPeriodicBoxVectors(*box_i)
            simulations[j].context.setPositions(positions_i)
            energy_ji = simulations[j].context.getState(
                getEnergy=True).getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
            simulations[i].context.setPeriodicBoxVectors(*box_j)
            simulations[i].context.setPositions(positions_j)
            energy_ij = simulations[i].context.getState(
                getEnergy=True).getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)

            log_alpha = exchange_log_acceptance(
                reduced_potential(energy_i, BETA, pressure, volume_i),
                reduced_potential(energy_j, BETA, pressure, volume_j),
                reduced_potential(energy_ij, BETA, pressure, volume_j),
                reduced_potential(energy_ji, BETA, pressure, volume_i))
            accept = log_alpha >= 0.0 or rng.random() < math.exp(log_alpha)
            if not accept:
                simulations[i].context.setPeriodicBoxVectors(*box_i)
                simulations[i].context.setPositions(positions_i)
                simulations[j].context.setPeriodicBoxVectors(*box_j)
                simulations[j].context.setPositions(positions_j)
            accepted_total += int(accept)
            attempted_total += 1
            step = simulations[i].context.getStepCount()
            rows.append([attempt_index, phase, step,
                         round(step * TIMESTEP_FS / 1000.0, 6),
                         i, j, round(log_alpha, 6), int(accept)])
        with EXCHANGE_LOG.open("a", newline="") as handle:
            csv.writer(handle).writerows(rows)
        attempt_index += 1

    for replica, simulation in enumerate(simulations):
        simulation.saveCheckpoint(str(HERE / f"replica_{replica:02d}.chk"))

    # Counted, not derived: with an even replica count the alternating phases give a different
    # number of pairs per round.
    ratio = (accepted_total / attempted_total) if attempted_total else float("nan")
    print(f"[remd] segment complete: {n_exchanges} exchange rounds, "
          f"{segment_steps * n_exchanges:,} steps per replica, "
          f"{accepted_total}/{attempted_total} accepted ({ratio:.3f})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
