#!/usr/bin/env python
"""REST2 exchange production for the contract-managed `md-gen` route. NOT the production engine.

    THE PRODUCTION REST2 ENGINE IS OPENMMTOOLS.

`md-openmm setup --config <setup.yaml>` with `protocol: REST2` generates a ladder that runs on
`openmmtools.multistate.ReplicaExchangeSampler` with `MultiStateReporter` NetCDF storage, launched
by `openmm-rest2`. That is what new work should use: OpenMMTools owns the exchange decisions, the
reduced potentials, the storage, the restart and the walker-to-state mapping, and it supports MPI
multi-GPU execution, which this loop does not.

This custom loop remains ONLY because the older contract-managed `md-gen` route and the datasets
already generated through it depend on its on-disk layout -- per-replica directories, its own
`exchange_attempts.csv`, and the stage fingerprints the shared preflight checks. Removing it would
invalidate existing dataset provenance, which is a worse outcome than keeping a legacy path that
says plainly what it is.

It is kept in agreement with the OpenMMTools engine, not maintained as an alternative to it: both
compute acceptance with the SAME `rest2_scaling.exchange_log_acceptance` and pair replicas with the
SAME `rest2_scaling.exchange_pairs`, and `tests/test_openmmtools_rest2.py` asserts that the two
produce identical accept/reject sequences from identical inputs and seeds. Do not add a scientific
capability here that the OpenMMTools path does not have; add it there.

See `docs/openmmtools-rest2.md`.

Generated by md-openmm; edit freely.

This script does NOT minimise, equilibrate, or repeat any common preparation. Every replica starts
from its own completed per-tau equilibration, which `equilibrate.py` produced:

    input  : replica_NN/equilibration/final_state.xml   (one per replica, tau-specific)
    output : replica_NN/production/{replica.csv, whole_system.dcd, solute.dcd, production.chk,
                                    final_state.xml}, plus exchange_attempts.csv here

Every replica is thermostatted at the SAME physical temperature and therefore shares one beta. The
rungs differ by Hamiltonian, not by thermostat, which is why the pV terms cancel in the NPT
acceptance criterion.

One invocation runs `number_of_exchanges` rounds of

    propagate every replica for duration_per_segment_ps -> attempt neighbour exchanges

so each replica advances `duration_per_segment_ps * number_of_exchanges`. Per-tau equilibration is
not part of that total.

Restarting: run it again, or ./extend.sh N. Each replica keeps its own checkpoint under
`production/`, and the exchange history is appended, never rewritten.
"""
import csv
import math
import os
import random
import sys
from pathlib import Path

import yaml
from openmm import XmlSerializer, unit
from openmm.app import CheckpointReporter, DCDReporter, PDBFile, StateDataReporter

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
sys.path.insert(0, str(HERE))
import preflight
from md_stages import (sha256_file, RECORD_FORMAT, active_barostat_count,
                       stage_config_sha256, stage_invariant_sha256,
                       add_barostat, add_positional_restraint, append_jsonl, count_barostats,
                       derive_seed, device_groups, file_record, make_simulation,
                       next_invocation_index, project_identity, propagate_segment,
                       require_parent_state, resolve_platform, set_barostat_frequency,
                       set_restraint, steps_for, trajectory_record, trim_to_checkpoint, utc_now,
                       write_final_state, write_yaml_atomic)
from rest2_scaling import (build_scaled_system, exchange_log_acceptance, exchange_pairs,
                           linear_tau_ladder, reduced_potential, scale_factor_for_tau)

CONFIG = yaml.safe_load((HERE.parent / "md.config.yaml").read_text())

# The resolved production request this directory was generated for. The shared preflight needs
# it: without a stage dict `check_parent` and `check_own_completion` short-circuit, which is how
# production ran with neither. Absent only in a project generated before stage.yaml existed for
# production, and preflight says so rather than silently skipping.
STAGE = (yaml.safe_load((HERE / "stage.yaml").read_text())
         if (HERE / "stage.yaml").is_file() else None)

INPUTS = (HERE.parent / CONFIG["paths"]["inputs_folder"]).resolve()
SOLUTE = yaml.safe_load((INPUTS / "solute.yaml").read_text())

common = CONFIG["common"]
method = CONFIG["REST2"]
implicit = common.get("pressure_bar") is None

TEMPERATURE = float(common["temperature_kelvin"]) * unit.kelvin
TIMESTEP_FS = float(common["timestep_fs"])
FRICTION = float(common["friction_per_ps"]) / unit.picosecond
BASE_SEED = int(common["random_seed"]) if common.get("random_seed") is not None else 20260101
def _barostat_frequency_steps():
    """MonteCarloBarostat attempt interval, in steps, from md.config.yaml.

    Required under explicit solvent, with no fallback: this is the interval the recorded provenance
    names, so a script that supplied its own could integrate at an interval no record mentions.
    """
    if implicit:
        return None
    value = common.get("barostat_frequency_steps")
    if value is None:
        raise SystemExit(
            "md.config.yaml is missing common.barostat_frequency_steps, which explicit solvent "
            "needs to construct the MonteCarloBarostat. Regenerate the project with "
            "`md-openmm md-gen`, or add the key (25 is OpenMM's own default).")
    return int(value)


#: null under implicit solvent, where no barostat exists in the System at all.
BAROSTAT_FREQUENCY_STEPS = _barostat_frequency_steps()

KB_KJ = 0.008314462618            # kJ/mol/K
BETA = 1.0 / (KB_KJ * float(common["temperature_kelvin"]))

N_REPLICAS = int(method["number_of_replicas"])
SOLUTE_INDICES = list(range(int(SOLUTE["n_solute_atoms"])))
EXCHANGE_LOG = HERE / "exchange_attempts.csv"


def device_groups_devices():
    """The CUDA devices this invocation would spread its replicas over, for the preflight."""
    try:
        return visible_devices()
    except Exception:
        return None


def replica_dir(replica, phase):
    return HERE / f"replica_{replica:02d}" / phase


def required_steps(name):
    """An interval from the REST2 block, in steps. A missing one is named, not guessed."""
    if method.get(name) is None:
        raise SystemExit(
            f"REST2.{name} is missing from md.config.yaml. Regenerate the protocol with "
            f"`md-openmm sys-config` and reapply your edits, or add the key by hand.")
    return steps_for(float(method[name]), TIMESTEP_FS)


def visible_devices():
    """The CUDA devices this process may use, honouring CUDA_VISIBLE_DEVICES."""
    raw = os.environ.get("CUDA_VISIBLE_DEVICES")
    if raw is not None:
        tokens = [t.strip() for t in raw.split(",") if t.strip()]
        return list(range(len(tokens)))            # logical indices, which is what OpenMM takes
    try:
        import subprocess
        out = subprocess.run(["nvidia-smi", "--query-gpu=index", "--format=csv,noheader"],
                             capture_output=True, text=True, timeout=15)
        if out.returncode == 0:
            return list(range(len([l for l in out.stdout.splitlines() if l.strip()])))
    except Exception:
        pass
    return []


def build_replica(replica, tau, base, topology, initial_positions, device, platform_name):
    """The same rung `equilibrate.py` built, so its final state loads into this Context."""
    excluded = SOLUTE["rest2"]["omega_excluded_bonds"] if method.get("omega_exclusion") else []
    system = build_scaled_system(base, SOLUTE_INDICES, tau, excluded)
    add_positional_restraint(system, initial_positions, SOLUTE_INDICES)
    seeds = {name: derive_seed(BASE_SEED, "REST2", replica, name)
             for name in ("integrator", "velocities", "barostat")}
    if not implicit:
        add_barostat(system, common["pressure_bar"], TEMPERATURE, seeds["barostat"],
                     frequency=BAROSTAT_FREQUENCY_STEPS)
    barostats = count_barostats(system)
    if implicit and barostats:
        raise SystemExit(f"implicit solvent must have no barostat; replica {replica} has "
                         f"{barostats}")
    simulation = make_simulation(topology, system, temperature=TEMPERATURE, friction=FRICTION,
                                 timestep=TIMESTEP_FS * unit.femtoseconds,
                                 seed=seeds["integrator"], platform_name=platform_name,
                                 device=device)
    return simulation, seeds


def attach_reporters(simulation, replica, *, resuming, whole_every, solute_every,
                     checkpoint_every):
    """Trajectories, log and checkpoint, all inside this replica's production directory."""
    directory = replica_dir(replica, "production")
    directory.mkdir(parents=True, exist_ok=True)
    whole = directory / "whole_system.dcd"
    solute = directory / "solute.dcd"
    table = directory / "replica.csv"
    simulation.reporters.append(DCDReporter(str(whole), whole_every,
                                            append=resuming and whole.is_file()))
    simulation.reporters.append(DCDReporter(str(solute), solute_every,
                                            append=resuming and solute.is_file(),
                                            atomSubset=SOLUTE_INDICES))
    simulation.reporters.append(CheckpointReporter(str(directory / "production.chk"),
                                                   checkpoint_every))
    simulation.reporters.append(StateDataReporter(
        str(table), solute_every, step=True, time=True, potentialEnergy=True, temperature=True,
        volume=not implicit, speed=True, append=resuming and table.is_file()))


def _starting_artifact(path, *, role):
    """Exactly what a replica consumed: role, path relative to REST2/, size and SHA-256."""
    path = Path(path)
    if not path.is_file():
        return {"role": role, "path": None, "bytes": None, "sha256": None,
                "note": "the starting artifact was not present"}
    return {"role": role,
            "path": os.path.relpath(path.resolve(), HERE),
            "bytes": path.stat().st_size,
            "sha256": sha256_file(path)}


def main(argv=None):
    print("# NOTE: this is the legacy REST2 exchange loop of the contract-managed "
          "md-gen route.")
    print("#       The production REST2 engine is OpenMMTools; see docs/openmmtools-rest2.md.")
    check_only = "--check" in (sys.argv[1:] if argv is None else argv)
    preflight.require(HERE, HERE.parent, INPUTS, CONFIG, stage=STAGE,
                      label=f"REST2 ({'check only' if check_only else 'exchange production'})",
                      dynamics=not check_only,
                      devices=(device_groups_devices() if not check_only else None))
    if check_only:
        print("[remd] --check: preflight only. No dynamics ran and nothing was written.",
              flush=True)
        return 0

    started_utc = utc_now()
    invocations_path = HERE / "invocations.jsonl"
    invocation_index = next_invocation_index(invocations_path)
    pdb = PDBFile(str(INPUTS / "topology.pdb"))
    base = XmlSerializer.deserialize((INPUTS / "system.xml").read_text())
    initial_positions = XmlSerializer.deserialize(
        (INPUTS / "initial_state.xml").read_text()).getPositions()
    excluded = SOLUTE["rest2"]["omega_excluded_bonds"] if method.get("omega_exclusion") else []

    taus = linear_tau_ladder(float(method["tau_min"]), float(method["tau_max"]), N_REPLICAS)
    platform_name = resolve_platform(os.environ.get("MD_PLATFORM") or None)
    devices = visible_devices() if platform_name == "CUDA" else []
    if platform_name == "CUDA" and not devices:
        devices = [0]                    # the platform exists; only the enumeration failed
    groups = device_groups(N_REPLICAS, devices)
    device_of = {replica: (devices[index] if devices else None)
                 for index, group in enumerate(groups) for replica in group}

    print(f"[remd] {N_REPLICAS} replicas, tau {taus[0]:.3f}..{taus[-1]:.3f}, "
          f"s = {[round(scale_factor_for_tau(t), 4) for t in taus]}")
    print(f"[remd] one temperature ({common['temperature_kelvin']} K) and one beta for every "
          f"replica; the rungs differ by Hamiltonian")
    print(f"[remd] {len(excluded)} omega bond(s) excluded from torsion scaling")
    if devices:
        shape = ("devices propagate concurrently, replicas sharing one device propagate in turn"
                 if len(groups) > 1 else "all replicas share it, so they propagate in turn")
        print(f"[remd] platform {platform_name}: {len(groups)} GPU(s) of {len(devices)} visible, "
              f"replicas per device {[list(g) for g in groups]}; {shape}")
    else:
        print(f"[remd] platform {platform_name}: no CUDA device, replicas propagate sequentially")

    whole_every = required_steps("whole_system_interval_ps")
    solute_every = required_steps("solute_interval_ps")
    checkpoint_every = required_steps("checkpoint_interval_ps")

    simulations = []
    started_from = {}
    for replica, tau in enumerate(taus):
        simulation, seeds = build_replica(replica, tau, base, pdb.topology, initial_positions,
                                          device_of.get(replica), platform_name)
        checkpoint = replica_dir(replica, "production") / "production.chk"
        resuming = checkpoint.is_file()
        equilibrated = replica_dir(replica, "equilibration") / "final_state.xml"
        # Hashed before this invocation can overwrite it: on a resume the production checkpoint is
        # rewritten at completion, so a later hash would name what this run produced rather than
        # what it started from.
        started_from[replica] = _starting_artifact(
            checkpoint if resuming else equilibrated,
            role=("own_production_checkpoint" if resuming else "tau_equilibration_final_state"))
        if resuming:
            simulation.loadCheckpoint(str(checkpoint))
            done = simulation.context.getStepCount()
            print(f"[remd] replica {replica}: resumed production at step {done:,}")
            # Reporters fire far more often than the checkpoint, so an interrupted invocation
            # leaves frames past it. Appending after them would duplicate that interval in this
            # replica's trajectory while every file still looked healthy.
            kept = trim_to_checkpoint(replica_dir(replica, "production"), done,
                                      whole_every=whole_every, solute_every=solute_every,
                                      table_every=solute_every)
            print(f"[remd] replica {replica}: trimmed to the checkpoint: "
                  + ", ".join(f"{name} -> {n}" for name, n in kept.items()))
        else:
            # The per-tau equilibration this replica already ran. Not a shared state, and not a
            # checkpoint: each rung relaxed under its OWN Hamiltonian before production began.
            equilibrated = replica_dir(replica, "equilibration") / "final_state.xml"
            simulation.context.setState(require_parent_state(
                equilibrated, stage_name=f"REST2 replica {replica} equilibration",
                command="../REST2"))
            simulation.context.setStepCount(0)
            print(f"[remd] replica {replica}: started from "
                  f"replica_{replica:02d}/equilibration/final_state.xml")
        set_restraint(simulation, 0.0)
        print(f"[remd] replica {replica}: tau {tau:.3f}, seeds {seeds}, "
              f"device {device_of.get(replica)}, "
              f"{active_barostat_count(simulation)} active barostat(s)")
        attach_reporters(simulation, replica, resuming=resuming, whole_every=whole_every,
                         solute_every=solute_every, checkpoint_every=checkpoint_every)
        simulations.append(simulation)

    resuming_history = EXCHANGE_LOG.is_file()
    attempt_index = 0
    if resuming_history:
        with EXCHANGE_LOG.open() as handle:
            rows = list(csv.DictReader(handle))
        attempt_index = (int(rows[-1]["attempt_index"]) + 1) if rows else 0
        print(f"[remd] resuming: {attempt_index} exchange round(s) already recorded")
    else:
        with EXCHANGE_LOG.open("w", newline="") as handle:
            csv.writer(handle).writerow(
                ["attempt_index", "phase", "step", "time_ps", "replica_i", "replica_j",
                 "log_acceptance", "accepted"])

    # duration_per_segment_ps is the time BETWEEN exchange rounds, so this invocation runs
    # segment_steps * number_of_exchanges per replica.
    segment_steps = steps_for(float(method["duration_per_segment_ps"]), TIMESTEP_FS)
    n_exchanges = int(method["number_of_exchanges"])
    if n_exchanges < 1:
        raise SystemExit(f"REST2.number_of_exchanges must be at least 1; got {n_exchanges}")
    total_ps = float(method["duration_per_segment_ps"]) * n_exchanges
    print(f"[remd] {n_exchanges} rounds x {segment_steps:,} steps "
          f"({method['duration_per_segment_ps']} ps) = {segment_steps * n_exchanges:,} steps "
          f"= {total_ps:g} ps of production per replica this invocation")

    invocation_first_round = attempt_index
    started_steps = [int(s.context.getStepCount()) for s in simulations]
    rng = random.Random(derive_seed(BASE_SEED, "REST2", "exchange", attempt_index))
    accepted_total = 0
    attempted_total = 0
    for _ in range(n_exchanges):
        propagate_segment(groups, lambda replica: simulations[replica].step(segment_steps))

        phase = attempt_index % 2
        pairs = exchange_pairs(N_REPLICAS, phase)
        if not pairs:
            # A two-replica ladder has no pair on phase 1. Alternating regardless would exchange on
            # every other round only, and a run resumed on an odd index would keep landing there.
            phase = (phase + 1) % 2
            pairs = exchange_pairs(N_REPLICAS, phase)
        if not pairs:
            raise SystemExit(f"{N_REPLICAS} replicas offer no exchange pair in either phase")

        rows = []
        for i, j in pairs:
            state_i = simulations[i].context.getState(getEnergy=True)
            state_j = simulations[j].context.getState(getEnergy=True)
            energy_i = state_i.getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
            energy_j = state_j.getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
            volume_i = volume_j = None
            pressure = None if implicit else float(common["pressure_bar"])
            if not implicit:
                volume_i = state_i.getPeriodicBoxVolume().value_in_unit(unit.nanometer ** 3)
                volume_j = state_j.getPeriodicBoxVolume().value_in_unit(unit.nanometer ** 3)

            # Cross energies: evaluate replica i's CONFIGURATION in replica j's Hamiltonian.
            # The box travels with the coordinates -- a configuration is positions AND the cell
            # they are periodic in, and putting i's positions into j's box would evaluate a
            # configuration in a box it does not fit.
            full_i = simulations[i].context.getState(getPositions=True)
            full_j = simulations[j].context.getState(getPositions=True)
            positions_i, box_i = full_i.getPositions(), full_i.getPeriodicBoxVectors()
            positions_j, box_j = full_j.getPositions(), full_j.getPeriodicBoxVectors()

            simulations[j].context.setPeriodicBoxVectors(*box_i)
            simulations[j].context.setPositions(positions_i)
            energy_ji = simulations[j].context.getState(
                getEnergy=True).getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
            simulations[i].context.setPeriodicBoxVectors(*box_j)
            simulations[i].context.setPositions(positions_j)
            energy_ij = simulations[i].context.getState(
                getEnergy=True).getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)

            log_alpha = exchange_log_acceptance(
                reduced_potential(energy_i, BETA, pressure, volume_i),
                reduced_potential(energy_j, BETA, pressure, volume_j),
                reduced_potential(energy_ij, BETA, pressure, volume_j),
                reduced_potential(energy_ji, BETA, pressure, volume_i))
            accept = log_alpha >= 0.0 or rng.random() < math.exp(log_alpha)
            if not accept:
                simulations[i].context.setPeriodicBoxVectors(*box_i)
                simulations[i].context.setPositions(positions_i)
                simulations[j].context.setPeriodicBoxVectors(*box_j)
                simulations[j].context.setPositions(positions_j)
            accepted_total += int(accept)
            attempted_total += 1
            step = simulations[i].context.getStepCount()
            rows.append([attempt_index, phase, step,
                         round(step * TIMESTEP_FS / 1000.0, 6),
                         i, j, round(log_alpha, 6), int(accept)])
        with EXCHANGE_LOG.open("a", newline="") as handle:
            csv.writer(handle).writerows(rows)
        attempt_index += 1

    replica_records = []
    for replica, simulation in enumerate(simulations):
        directory = replica_dir(replica, "production")
        simulation.saveCheckpoint(str(directory / "production.chk"))
        write_final_state(simulation, directory / "final_state.xml")
        tau = taus[replica]
        replica_records.append({
            "replica": f"replica_{replica:02d}",
            "tau": tau,
            # tau is the source parameter; these two are labelled derived so nothing downstream
            # can feed them back in as inputs.
            "derived_scale_factor_s": scale_factor_for_tau(tau),
            "derived_solute_environment_coupling_sqrt_s": 1.0 - tau,
            "seeds": {name: derive_seed(BASE_SEED, "REST2", replica, name)
                      for name in ("integrator", "velocities", "barostat")},
            "cuda_device": device_of.get(replica),
            # Measured on this replica's Context, not copied from the configuration: each rung
            # constructs its own scaled System, so each one's barostat has to be checked.
            "barostats_in_system": count_barostats(simulation.context.getSystem()),
            "barostats_active": active_barostat_count(simulation),
            "barostat_frequency_steps": BAROSTAT_FREQUENCY_STEPS,
            "started_at_step": started_steps[replica],
            "ended_at_step": int(simulation.context.getStepCount()),
            "equilibration_final_state": f"replica_{replica:02d}/equilibration/final_state.xml",
            "started_from": started_from.get(replica),
            "outputs": {name: file_record(directory / name,
                                          digest=name in ("final_state.xml", "production.chk"))
                        for name in ("replica.csv", "production.chk", "final_state.xml")},
            "trajectories": {
                # As in cMD: the frame-to-time map is recorded where the interval is known, so an
                # AIS path seeded from one rung can place its source frame on a physical clock.
                "whole_system": trajectory_record(directory / "whole_system.dcd",
                                                  atom_scope="all_atoms",
                                                  reporter_interval_steps=whole_every,
                                                  timestep_fs=TIMESTEP_FS),
                "solute": trajectory_record(directory / "solute.dcd",
                                            atom_scope=f"solute:{len(SOLUTE_INDICES)}_atoms",
                                            reporter_interval_steps=solute_every,
                                            timestep_fs=TIMESTEP_FS)},
        })

    lifetime_rounds = attempt_index
    record = {
        "format": RECORD_FORMAT,
        "record_kind": "rest2_run",
        "invocation_index": invocation_index,
        "started_utc": started_utc,
        "finished_utc": utc_now(),
        "status": "completed",
        "implementation": project_identity(CONFIG),
        "command": list(sys.argv),
        "ensemble": method["ensemble"],
        "implicit_solvent": implicit,
        # One physical temperature and one beta for the whole ladder; the rungs differ by
        # Hamiltonian, which is why the pV terms cancel in the NPT criterion.
        "thermodynamics": {
            "temperature_kelvin": float(common["temperature_kelvin"]),
            "pressure_bar": common.get("pressure_bar"),
            "beta_kj_mol_inverse": BETA,
            "hamiltonian_scaling": "solute-solute (1-tau)^2, solute-environment (1-tau)",
            "common_beta_across_replicas": True,
            "positions_and_box_vectors_exchanged_together": True,
        },
        # The integrator and pressure-coupling settings this invocation ran with, recorded where
        # they were used rather than left to be read back out of md.config.yaml.
        "integrator": {
            "kind": "LangevinMiddleIntegrator",
            "temperature_kelvin": float(common["temperature_kelvin"]),
            "friction_per_ps": float(common["friction_per_ps"]),
            "timestep_fs": TIMESTEP_FS,
        },
        "pressure_coupling": None if implicit else {
            "barostat": "MonteCarloBarostat",
            "pressure_bar": float(common["pressure_bar"]),
            "frequency_steps": BAROSTAT_FREQUENCY_STEPS,
            "interval_ps": round(BAROSTAT_FREQUENCY_STEPS * TIMESTEP_FS / 1000.0, 6),
        },
        "exchange": {
            "rounds_this_invocation": n_exchanges,
            "attempts_this_invocation": attempted_total,
            "accepted_this_invocation": accepted_total,
            "first_round_index": invocation_first_round,
            "last_round_index": lifetime_rounds - 1,
            "lifetime_rounds": lifetime_rounds,
            "starting_phase": invocation_first_round % 2,
            "rng_provenance": "random.Random(derive_seed(base_seed, 'REST2', 'exchange', "
                              "first_round_index)) -- reconstructed from the resumed round index",
            "history": "exchange_attempts.csv",
        },
        "segment": {
            "duration_per_segment_ps": float(method["duration_per_segment_ps"]),
            "steps_per_segment": segment_steps,
            "steps_per_replica_this_invocation": segment_steps * n_exchanges,
        },
        "platform": platform_name,
        "replicas": replica_records,
    }
    write_yaml_atomic(HERE / "resolved_run.yaml", record)
    append_jsonl(invocations_path, record)

    # The stage record `preflight.check_own_completion` reads. Without it, a COMPLETED REST2
    # production is invisible to its own preflight: the check looks for `resolved_stage.yaml`,
    # finds nothing, and reports "absent; this stage has not run" for a stage that has. Rerunning
    # then starts production again from the per-tau equilibration states and overwrites a finished
    # trajectory -- which is the accident the whole shared preflight exists to prevent.
    #
    # `resolved_run.yaml` above is the FAIR runtime account of the invocation. This is the
    # scientific account of the request that ran, and it is what a continuation is checked
    # against. cMD has written both since the contract-gate fixes; REST2 wrote only the first.
    write_yaml_atomic(HERE / "resolved_stage.yaml", {
        "kind": "rest2_exchange",
        "ensemble": method["ensemble"],
        "tau_min": float(method["tau_min"]),
        "tau_max": float(method["tau_max"]),
        "number_of_replicas": int(method["number_of_replicas"]),
        "taus": [float(r["tau"]) for r in replica_records],
        "derived_scale_factors_s": [scale_factor_for_tau(float(r["tau"]))
                                    for r in replica_records],
        "temperature_kelvin": float(common["temperature_kelvin"]),
        "timestep_fs": TIMESTEP_FS,
        "duration_per_segment_ps": float(method["duration_per_segment_ps"]),
        "number_of_exchanges": lifetime_rounds,
        "total_steps": segment_steps * lifetime_rounds,
        "input_state": "replica_XX/equilibration/final_state.xml",
        "output_state": "replica_XX/production/final_state.xml",
        # Two fingerprints, answering different questions -- the same split cmd_run.py records.
        # The full one identifies the EXACT request that produced these outputs. The invariant one
        # excludes the extendable fields, `number_of_exchanges` among them, so asking for more
        # exchange rounds stays legitimate while a changed timestep, ensemble or ladder must stop
        # the run before a Context exists.
        "stage_config_sha256": (stage_config_sha256(STAGE) if STAGE else None),
        "stage_invariant_sha256": (stage_invariant_sha256(STAGE) if STAGE else None),
    })

    ratio = (accepted_total / attempted_total) if attempted_total else float("nan")
    print(f"[remd] segment complete: {n_exchanges} exchange rounds, "
          f"{segment_steps * n_exchanges:,} steps per replica, "
          f"{accepted_total}/{attempted_total} accepted ({ratio:.3f})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
