#!/usr/bin/env python
"""REST2 replica exchange. Generated by md-openmm; edit freely.

One replica per rung of a tau ladder. The solute Hamiltonian is scaled by `rest2_scaling.py`
beside this file; the environment is untouched, so every replica samples the same physical system
at a different effective solute temperature.

Exchanges are attempted between alternating nearest neighbours. Under NPT the reduced potential
carries the pV term explicitly, because two replicas share a pressure but NOT a beta, so it does
not cancel.

Restarting: run it again, or ./extend.sh N. Each replica keeps its own checkpoint and the exchange
history is appended, never rewritten.
"""
import csv
import math
import os
import random
import sys
from pathlib import Path

import yaml
from openmm import LangevinMiddleIntegrator, MonteCarloBarostat, Platform, XmlSerializer, unit
from openmm.app import PDBFile, Simulation

sys.path.insert(0, str(Path(__file__).resolve().parent))
from rest2_scaling import (build_scaled_system, exchange_log_acceptance, exchange_pairs,
                           linear_tau_ladder, reduced_potential, scale_factor_for_tau)

HERE = Path(__file__).resolve().parent
CONFIG = yaml.safe_load((HERE.parent / "md.config.yaml").read_text())
INPUTS = (HERE.parent / CONFIG["paths"]["inputs_folder"]).resolve()
SOLUTE = yaml.safe_load((INPUTS / "solute.yaml").read_text())

common = CONFIG["common"]
method = CONFIG["REST2"]
implicit = common.get("pressure_bar") is None

TEMPERATURE = float(common["temperature_kelvin"]) * unit.kelvin
TIMESTEP = float(common["timestep_fs"]) * unit.femtoseconds
FRICTION = float(common["friction_per_ps"]) / unit.picosecond
SEED = int(common["random_seed"]) if common.get("random_seed") is not None else 20260101
KB_KJ = 0.008314462618            # kJ/mol/K
BETA = 1.0 / (KB_KJ * float(common["temperature_kelvin"]))

N_REPLICAS = int(method["number_of_replicas"])
EXCHANGE_LOG = HERE / "exchange_attempts.csv"


def steps_for(picoseconds):
    exact = picoseconds * 1000.0 / float(common["timestep_fs"])
    if abs(exact - round(exact)) > 1e-9:
        raise SystemExit(f"{picoseconds} ps is not a whole number of "
                         f"{common['timestep_fs']} fs steps ({exact})")
    return int(round(exact))


def visible_devices():
    """The CUDA devices this process may use, honouring CUDA_VISIBLE_DEVICES.

    No busy detection and no scheduler: at most min(n_replicas, n_visible) devices are used, and
    replicas are assigned round-robin so the mapping is reproducible.
    """
    raw = os.environ.get("CUDA_VISIBLE_DEVICES")
    if raw is not None:
        tokens = [t.strip() for t in raw.split(",") if t.strip()]
        return list(range(len(tokens)))            # logical indices, which is what OpenMM takes
    try:
        import subprocess
        out = subprocess.run(["nvidia-smi", "--query-gpu=index", "--format=csv,noheader"],
                             capture_output=True, text=True, timeout=15)
        if out.returncode == 0:
            return list(range(len([l for l in out.stdout.splitlines() if l.strip()])))
    except Exception:
        pass
    return []


def device_for_replica(replica, devices):
    if not devices:
        return None
    return devices[replica % len(devices)]


def make_simulation(system, topology, device):
    integrator = LangevinMiddleIntegrator(TEMPERATURE, FRICTION, TIMESTEP)
    integrator.setRandomNumberSeed((SEED + 7919 * 1) % (2 ** 31 - 1))
    platform_name = os.environ.get("MD_PLATFORM") or ("CUDA" if device is not None else None)
    if platform_name == "CUDA":
        platform = Platform.getPlatformByName("CUDA")
        properties = {"Precision": "mixed", "DeviceIndex": str(device)}
        return Simulation(topology, system, integrator, platform, properties)
    if platform_name:
        return Simulation(topology, system, integrator, Platform.getPlatformByName(platform_name))
    return Simulation(topology, system, integrator)


def main():
    pdb = PDBFile(str(INPUTS / "topology.pdb"))
    base = XmlSerializer.deserialize((INPUTS / "system.xml").read_text())
    solute_indices = list(range(int(SOLUTE["n_solute_atoms"])))
    excluded = SOLUTE["rest2"]["omega_excluded_bonds"] if method.get("omega_exclusion") else []

    taus = linear_tau_ladder(float(method["tau_min"]), float(method["tau_max"]), N_REPLICAS)
    forced = os.environ.get("MD_PLATFORM")
    # A forced non-CUDA platform means no device is used, and saying otherwise would misreport
    # which hardware produced the trajectory.
    devices = [] if (forced and forced != "CUDA") else visible_devices()
    n_used = min(N_REPLICAS, len(devices)) if devices else 0
    print(f"[remd] {N_REPLICAS} replicas, tau {taus[0]:.3f}..{taus[-1]:.3f}, "
          f"s = {[round(scale_factor_for_tau(t), 4) for t in taus]}")
    print(f"[remd] {len(excluded)} omega bond(s) excluded from torsion scaling")
    if n_used:
        print(f"[remd] using {n_used} GPU(s) of {len(devices)} visible"
              + (" (replicas share devices round-robin)" if N_REPLICAS > n_used else ""))
    else:
        print(f"[remd] platform {forced or 'default'}; no CUDA device selected")

    simulations = []
    for replica, tau in enumerate(taus):
        system = build_scaled_system(base, solute_indices, tau, excluded)
        if not implicit:
            barostat = MonteCarloBarostat(float(common["pressure_bar"]) * unit.bar,
                                          TEMPERATURE, 25)
            barostat.setRandomNumberSeed((SEED + 104729 * (replica + 1)) % (2 ** 31 - 1))
            system.addForce(barostat)
        device = device_for_replica(replica, devices[:n_used]) if n_used else None
        simulation = make_simulation(system, pdb.topology, device)
        checkpoint = HERE / f"replica_{replica:02d}.chk"
        if checkpoint.is_file():
            simulation.loadCheckpoint(str(checkpoint))
        else:
            state = XmlSerializer.deserialize((INPUTS / "initial_state.xml").read_text())
            simulation.context.setState(state)
            simulation.minimizeEnergy(maxIterations=int(CONFIG["minimization"]["max_iterations"]))
            simulation.context.setVelocitiesToTemperature(TEMPERATURE, SEED + replica)
        simulations.append(simulation)

    resuming = EXCHANGE_LOG.is_file()
    attempt_index = 0
    if resuming:
        with EXCHANGE_LOG.open() as handle:
            rows = list(csv.DictReader(handle))
        attempt_index = (int(rows[-1]["attempt_index"]) + 1) if rows else 0
        print(f"[remd] resuming: {attempt_index} exchange attempt(s) already recorded")
    else:
        with EXCHANGE_LOG.open("w", newline="") as handle:
            csv.writer(handle).writerow(
                ["attempt_index", "phase", "step", "time_ps", "replica_i", "replica_j",
                 "log_acceptance", "accepted"])

    segment_steps = steps_for(float(method["duration_per_segment_ps"]))
    n_exchanges = int(method["number_of_exchanges"])
    if segment_steps % n_exchanges:
        raise SystemExit(f"{segment_steps} steps does not divide into {n_exchanges} exchanges")
    per_exchange = segment_steps // n_exchanges

    rng = random.Random(SEED + attempt_index)
    accepted_total = 0
    attempted_total = 0
    for exchange in range(n_exchanges):
        for simulation in simulations:
            simulation.step(per_exchange)
        phase = (attempt_index) % 2
        pairs = exchange_pairs(N_REPLICAS, phase)
        if not pairs:
            # Alternating nearest-neighbour phases: with an even replica count one phase has no
            # pair to offer, and with exactly 2 replicas that is every other round. The dynamics
            # still advance -- only the exchange is skipped -- but say so rather than leaving a
            # silent gap in the history.
            print(f"[remd] attempt {attempt_index}: phase {phase} offers no pair for "
                  f"{N_REPLICAS} replicas; dynamics advanced, no exchange attempted")
        rows = []
        for i, j in pairs:
            state_i = simulations[i].context.getState(getEnergy=True)
            state_j = simulations[j].context.getState(getEnergy=True)
            energy_i = state_i.getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
            energy_j = state_j.getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
            volume_i = volume_j = None
            pressure = None if implicit else float(common["pressure_bar"])
            if not implicit:
                volume_i = state_i.getPeriodicBoxVolume().value_in_unit(unit.nanometer ** 3)
                volume_j = state_j.getPeriodicBoxVolume().value_in_unit(unit.nanometer ** 3)

            # Cross energies: evaluate replica i's CONFIGURATION in replica j's Hamiltonian.
            #
            # The box travels with the coordinates. Under NPT each replica has its own volume, so
            # putting i's positions into j's context while j's box is still in place evaluates a
            # configuration in a box it does not fit -- overlapping images, enormous energies, and
            # an acceptance that is always zero. A configuration is positions AND the cell they
            # are periodic in.
            full_i = simulations[i].context.getState(getPositions=True)
            full_j = simulations[j].context.getState(getPositions=True)
            positions_i, box_i = full_i.getPositions(), full_i.getPeriodicBoxVectors()
            positions_j, box_j = full_j.getPositions(), full_j.getPeriodicBoxVectors()

            simulations[j].context.setPeriodicBoxVectors(*box_i)
            simulations[j].context.setPositions(positions_i)
            energy_ji = simulations[j].context.getState(
                getEnergy=True).getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
            simulations[i].context.setPeriodicBoxVectors(*box_j)
            simulations[i].context.setPositions(positions_j)
            energy_ij = simulations[i].context.getState(
                getEnergy=True).getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)

            log_alpha = exchange_log_acceptance(
                reduced_potential(energy_i, BETA, pressure, volume_i),
                reduced_potential(energy_j, BETA, pressure, volume_j),
                reduced_potential(energy_ij, BETA, pressure, volume_j),
                reduced_potential(energy_ji, BETA, pressure, volume_i))
            accept = log_alpha >= 0.0 or rng.random() < math.exp(log_alpha)
            if not accept:
                simulations[i].context.setPeriodicBoxVectors(*box_i)
                simulations[i].context.setPositions(positions_i)
                simulations[j].context.setPeriodicBoxVectors(*box_j)
                simulations[j].context.setPositions(positions_j)
            accepted_total += int(accept)
            attempted_total += 1
            step = simulations[i].context.getStepCount()
            rows.append([attempt_index, phase, step,
                         round(step * float(common["timestep_fs"]) / 1000.0, 6),
                         i, j, round(log_alpha, 6), int(accept)])
        with EXCHANGE_LOG.open("a", newline="") as handle:
            csv.writer(handle).writerows(rows)
        attempt_index += 1

    for replica, simulation in enumerate(simulations):
        simulation.saveCheckpoint(str(HERE / f"replica_{replica:02d}.chk"))

    # Counted, not derived: with an even replica count the alternating phases give a different
    # number of pairs per round, and a 2-replica ladder has no pair at all on phase 1.
    ratio = (accepted_total / attempted_total) if attempted_total else float("nan")
    print(f"[remd] segment complete: {n_exchanges} exchange rounds, "
          f"{accepted_total}/{attempted_total} accepted ({ratio:.3f})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
