#!/usr/bin/env python
"""REST2 per-tau equilibration. Generated by md-openmm; edit freely.

Replicas on different GPUs equilibrate concurrently; replicas sharing one GPU take turns. That is
the same device policy exchange production uses, from the same helper.

Every replica starts from the SAME finalized common equilibration state -- the one `cMD/run.py`
also starts from -- then applies its own tau-scaled Hamiltonian and relaxes under it. That
relaxation is what this script does, and it is NOT exchange production: no exchange is attempted
here and none of these steps count towards `duration_per_segment_ps * number_of_exchanges`.

    input  : ../<last common stage>/final_state.xml   (the same file for every replica)
    output : replica_NN/equilibration/{stage.log, stage.csv, checkpoint.chk, final_state.xml,
                                       final.pdb, resolved_stage.yaml}

Run it once before `run.py`. Running it again resumes any replica that has not finished and skips
those that have.
"""
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml
from openmm import unit
from openmm.app import CheckpointReporter, PDBFile, StateDataReporter

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
sys.path.insert(0, str(HERE))
from md_stages import (active_barostat_count, add_barostat, add_positional_restraint,
                       count_barostats, derive_seed, device_groups, make_simulation,
                       propagate_segment, require_parent_state, resolve_platform,
                       restraint_strength, set_restraint, steps_for, write_final_pdb,
                       write_final_state)
from rest2_scaling import build_scaled_system, linear_tau_ladder, scale_factor_for_tau

CONFIG = yaml.safe_load((HERE.parent / "md.config.yaml").read_text())
INPUTS = (HERE.parent / CONFIG["paths"]["inputs_folder"]).resolve()
SOLUTE = yaml.safe_load((INPUTS / "solute.yaml").read_text())
BRANCH = CONFIG["paths"]["common_final_state"]
PARENT_STAGE = CONFIG["paths"]["common_final_stage"]

common = CONFIG["common"]
method = CONFIG["REST2"]
implicit = common.get("pressure_bar") is None

TEMPERATURE = float(common["temperature_kelvin"]) * unit.kelvin
TIMESTEP_FS = float(common["timestep_fs"])
FRICTION = float(common["friction_per_ps"]) / unit.picosecond
BASE_SEED = int(common["random_seed"]) if common.get("random_seed") is not None else 20260101
def _barostat_frequency_steps():
    """MonteCarloBarostat attempt interval, in steps, from md.config.yaml.

    Required under explicit solvent, with no fallback: this is the interval the recorded provenance
    names, so a script that supplied its own could integrate at an interval no record mentions.
    """
    if implicit:
        return None
    value = common.get("barostat_frequency_steps")
    if value is None:
        raise SystemExit(
            "md.config.yaml is missing common.barostat_frequency_steps, which explicit solvent "
            "needs to construct the MonteCarloBarostat. Regenerate the project with "
            "`md-openmm md-gen`, or add the key (25 is OpenMM's own default).")
    return int(value)


#: null under implicit solvent, where no barostat exists in the System at all.
BAROSTAT_FREQUENCY_STEPS = _barostat_frequency_steps()

N_REPLICAS = int(method["number_of_replicas"])
SOLUTE_INDICES = list(range(int(SOLUTE["n_solute_atoms"])))


def replica_seeds(replica):
    return {name: derive_seed(BASE_SEED, "REST2", replica, name)
            for name in ("integrator", "velocities", "barostat")}


def build_replica_system(replica, tau, initial_positions):
    """The rung's scaled Hamiltonian, with the same Force layout every REST2 script builds."""
    excluded = SOLUTE["rest2"]["omega_excluded_bonds"] if method.get("omega_exclusion") else []
    system = build_scaled_system(
        XmlSerializerLoad(INPUTS / "system.xml"), SOLUTE_INDICES, tau, excluded)
    add_positional_restraint(system, initial_positions, SOLUTE_INDICES)
    if not implicit:
        add_barostat(system, common["pressure_bar"], TEMPERATURE,
                     replica_seeds(replica)["barostat"],
                     frequency=BAROSTAT_FREQUENCY_STEPS)
    barostats = count_barostats(system)
    if implicit and barostats:
        raise SystemExit(f"implicit solvent must have no barostat; replica {replica} has "
                         f"{barostats}")
    return system


def XmlSerializerLoad(path):
    from openmm import XmlSerializer

    return XmlSerializer.deserialize(Path(path).read_text(encoding="utf-8"))


def visible_devices():
    """The CUDA devices this process may use, honouring CUDA_VISIBLE_DEVICES."""
    raw = os.environ.get("CUDA_VISIBLE_DEVICES")
    if raw is not None:
        tokens = [t.strip() for t in raw.split(",") if t.strip()]
        return list(range(len(tokens)))
    try:
        import subprocess
        out = subprocess.run(["nvidia-smi", "--query-gpu=index", "--format=csv,noheader"],
                             capture_output=True, text=True, timeout=15)
        if out.returncode == 0:
            return list(range(len([l for l in out.stdout.splitlines() if l.strip()])))
    except Exception:
        pass
    return []


def main():
    platform_name = resolve_platform(os.environ.get("MD_PLATFORM") or None)
    taus = linear_tau_ladder(float(method["tau_min"]), float(method["tau_max"]), N_REPLICAS)
    steps = steps_for(float(method["equilibration_duration_ps"]), TIMESTEP_FS)

    devices = visible_devices() if platform_name == "CUDA" else []
    if platform_name == "CUDA" and not devices:
        devices = [0]
    groups = device_groups(N_REPLICAS, devices)
    device_of = {replica: (devices[index] if devices else None)
                 for index, group in enumerate(groups) for replica in group}

    print(f"[remd-eq] platform {platform_name}; {N_REPLICAS} replicas, "
          f"tau {taus[0]:.3f}..{taus[-1]:.3f}")
    print(f"[remd-eq] {method['equilibration_duration_ps']} ps per replica = {steps:,} steps. "
          f"This is NOT exchange production and is not counted in it.")
    print(f"[remd-eq] every replica starts from {BRANCH}")
    if devices:
        # The same rule production uses: one rung per device, and rungs that share a device take
        # turns. Equilibrating them one after another wasted every GPU but one.
        shape = ("devices run concurrently, replicas sharing one device take turns"
                 if len(groups) > 1 else "all replicas share it, so they take turns")
        print(f"[remd-eq] {len(groups)} GPU(s) of {len(devices)} visible, replicas per device "
              f"{[list(g) for g in groups]}; {shape}")
    else:
        print(f"[remd-eq] no CUDA device; replicas equilibrate sequentially")

    branch_state = require_parent_state((HERE / BRANCH).resolve(), stage_name=PARENT_STAGE,
                                        command=f"../{PARENT_STAGE}")
    initial_positions = XmlSerializerLoad(INPUTS / "initial_state.xml").getPositions()
    pdb = PDBFile(str(INPUTS / "topology.pdb"))

    def equilibrate_replica(replica):
        tau = taus[replica]
        directory = HERE / f"replica_{replica:02d}" / "equilibration"
        directory.mkdir(parents=True, exist_ok=True)
        final = directory / "final_state.xml"
        if final.is_file():
            print(f"[remd-eq] replica {replica}: already equilibrated, skipping", flush=True)
            return

        seeds = replica_seeds(replica)
        system = build_replica_system(replica, tau, initial_positions)
        simulation = make_simulation(pdb.topology, system, temperature=TEMPERATURE,
                                     friction=FRICTION, timestep=TIMESTEP_FS * unit.femtoseconds,
                                     seed=seeds["integrator"], platform_name=platform_name,
                                     device=device_of.get(replica))
        checkpoint = directory / "checkpoint.chk"
        done = 0
        if checkpoint.is_file():
            simulation.loadCheckpoint(str(checkpoint))
            done = simulation.context.getStepCount()
            print(f"[remd-eq] replica {replica}: resuming at step {done:,}", flush=True)
        else:
            simulation.context.setState(branch_state)
            simulation.context.setStepCount(0)
            simulation.context.setVelocitiesToTemperature(TEMPERATURE, seeds["velocities"])
        set_restraint(simulation, 0.0)     # the common stages already released the solute

        report_every = max(1, steps // 10)
        simulation.reporters.append(CheckpointReporter(str(checkpoint), report_every))
        simulation.reporters.append(StateDataReporter(
            str(directory / "stage.csv"), report_every, step=True, time=True,
            potentialEnergy=True, temperature=True, volume=not implicit, append=done > 0))

        active = active_barostat_count(simulation)
        print(f"[remd-eq] replica {replica}: tau {tau:.3f}, s = {scale_factor_for_tau(tau):.4f}, "
              f"device {device_of.get(replica)}, seeds {seeds}, {active} active barostat(s), "
              f"{steps - done:,} steps to run", flush=True)
        if steps - done > 0:
            simulation.step(steps - done)
        simulation.saveCheckpoint(str(checkpoint))

        write_final_state(simulation, final)
        write_final_pdb(simulation, directory / "final.pdb", implicit=implicit)
        resolved = {
            "stage": f"replica_{replica:02d}_equilibration",
            "kind": "rest2_tau_equilibration",
            "ensemble": method["ensemble"],
            "implicit_solvent": implicit,
            "tau": tau,
            "scale_factor_s": scale_factor_for_tau(tau),
            "duration_ps": float(method["equilibration_duration_ps"]),
            "steps": steps,
            "restraint_k_kcal_mol_a2": 0.0,
            "restraint_kj_mol_nm2": restraint_strength(simulation),
            "temperature_kelvin": float(common["temperature_kelvin"]),
            "pressure_bar": common.get("pressure_bar"),
            "timestep_fs": TIMESTEP_FS,
            "integrator_seed": seeds["integrator"],
            "velocity_seed": seeds["velocities"],
            "barostat_seed": seeds["barostat"],
            "barostats_in_system": count_barostats(system),
            "barostats_active": active,
            "input_state": BRANCH,
            "device": device_of.get(replica),
            "output_state": "final_state.xml",
            "platform": platform_name,
            "template_commit": (CONFIG.get("provenance") or {}).get("template_commit"),
            "finished_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        }
        (directory / "resolved_stage.yaml").write_text(
            yaml.safe_dump(resolved, sort_keys=False), encoding="utf-8")
        (directory / "stage.log").write_text(
            f"replica {replica} tau {tau} equilibrated for {steps} steps on device "
            f"{device_of.get(replica)}\n", encoding="utf-8")
        del simulation

    propagate_segment(groups, equilibrate_replica)
    print(f"[remd-eq] all {N_REPLICAS} replicas equilibrated. Now: ./run.sh")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
