#!/usr/bin/env bash
# Run this method. Generated by md-openmm.
#
#   ./run.sh                 # use the configured OpenMM environment
#   MD_PLATFORM=CPU ./run.sh # force a platform
#   MD_DEVICE=0 ./run.sh     # cMD only: pin one CUDA device
#
# Every path below is relative to this script, so moving the project is enough.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

PYTHON="__PYTHON__"
if [ ! -x "$PYTHON" ]; then
    # The recorded interpreter is gone -- fall back to whatever python has OpenMM.
    PYTHON="$(command -v python3 || command -v python)"
fi
export CUDA_DEVICE_ORDER="${CUDA_DEVICE_ORDER:-PCI_BUS_ID}"

echo "== __METHOD__ =="
"$PYTHON" run.py "$@" 2>&1 | tee -a run.log
