#!/usr/bin/env bash
# Run this method. Generated by md-openmm.
#
#   ./run.sh                          # CUDA, which is the default and the only silent one
#   MD_DEVICE=0 ./run.sh              # cMD only: pin one CUDA device
#   CUDA_VISIBLE_DEVICES=0,1 ./run.sh # REST2: the devices the replicas are spread over
#   MD_PLATFORM=CPU ./run.sh          # anything but CUDA has to be asked for by name
#
# There is no quiet CPU fallback. A run that lands on the CPU because the GPU was invisible to
# this process looks healthy and takes hundreds of times longer, so it fails instead.
#
# Every path below is relative to this script, so moving the project is enough.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

PYTHON="__PYTHON__"
if [ ! -x "$PYTHON" ]; then
    # The recorded interpreter is gone -- fall back to whatever python has OpenMM.
    PYTHON="$(command -v python3 || command -v python)"
fi
export CUDA_DEVICE_ORDER="${CUDA_DEVICE_ORDER:-PCI_BUS_ID}"

echo "== __METHOD__ =="
"$PYTHON" run.py "$@" 2>&1 | tee -a run.log
