#!/usr/bin/env bash
# Convenience wrapper. Generated by md-openmm.
#
# It runs the common stages in order and then the configured production methods. The individual
# stage scripts are the authoritative operations -- this file only calls them in sequence, and
# stopping it and running a stage by hand is always a supported thing to do:
#
#   cd minimization && ./run.sh
#   cd eq1_nvt_1kcal && ./run.sh
#   ...
#   cd REST2 && ./equilibrate.sh && ./run.sh
#
# A stage that has already finished still re-runs here; each stage decides for itself whether to
# resume from its checkpoint. Pass MD_PLATFORM through as usual: MD_PLATFORM=CPU ./run_all.sh
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

for stage in __COMMON_STAGES__; do
    echo "== common stage: $stage =="
    ( cd "$stage" && ./run.sh )
done

__PRODUCTION__
echo "== done =="
