#!/usr/bin/env python
"""One common equilibration stage. Generated by md-openmm; edit freely.

What this stage is, how long it runs, how strongly it restrains the solute and which file it reads
are all in `stage.yaml` beside this script. Reading that file is the whole configuration story --
there is no schema layer and no run database.

    input  : the finalized state of the parent stage (never a checkpoint -- see below)
    output : stage.log, stage.csv, checkpoint.chk, final_state.xml, final.pdb, resolved_stage.yaml

`checkpoint.chk` resumes THIS stage in the same OpenMM environment. `final_state.xml` is the
handoff to the next one, and is written only when the stage completes: a downstream stage that
consumed a checkpoint would be starting from a partially finished parent while every file on disk
still looked normal.

Every path is relative to this script, so moving `inputs/` and `MD/` together is enough.
"""
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml
from openmm import unit
from openmm.app import CheckpointReporter, PDBFile, StateDataReporter

HERE = Path(__file__).resolve().parent


def _project_root(start):
    """The `MD/` directory, found rather than assumed.

    Stages are not all at the same depth -- the equilibration ones live under `eq/` -- so counting
    `..` here would be a second statement of the layout that can disagree with the first.
    """
    for candidate in [start, *start.parents]:
        if (candidate / "md.config.yaml").is_file():
            return candidate
    raise SystemExit(f"no md.config.yaml above {start}; this script must live inside a project "
                     f"written by `md-openmm md-gen`.")


PROJECT = _project_root(HERE)
sys.path.insert(0, str(PROJECT))
from md_stages import (PRODUCTION_BAROSTAT_FREQUENCY, active_barostat_count, build_stage_system,
                       count_barostats, make_simulation, require_parent_state, resolve_platform,
                       restraint_strength, set_restraint, steps_for, write_final_pdb,
                       write_final_state)

STAGE = yaml.safe_load((HERE / "stage.yaml").read_text())
CONFIG = yaml.safe_load((PROJECT / "md.config.yaml").read_text())
INPUTS = (PROJECT / CONFIG["paths"]["inputs_folder"]).resolve()
SOLUTE = yaml.safe_load((INPUTS / "solute.yaml").read_text())

IMPLICIT = bool(STAGE["implicit"])
SOLUTE_INDICES = list(range(int(SOLUTE["n_solute_atoms"])))
TEMPERATURE = float(STAGE["temperature_kelvin"]) * unit.kelvin
TIMESTEP_FS = float(STAGE["timestep_fs"])

#: Which stages hold the solute, and which run a barostat. The stage kind is the single switch;
#: nothing here is inferred from a directory name.
RESTRAINED = {"minimization", "nvt_restrained", "npt_restrained"}
BAROSTAT_ACTIVE = {"npt_restrained", "npt_free"}


def main():
    kind = STAGE["kind"]
    log_lines = []

    # A finished stage is not re-run by accident. Its final_state.xml is what every downstream
    # stage has already consumed, so silently redoing it would move the ground under a chain that
    # has already been built on it -- and the trajectories downstream would no longer follow from
    # the state their directories claim.
    finished = HERE / STAGE["output_state"]
    if finished.is_file() and not os.environ.get("MD_REDO"):
        print(f"[{STAGE['name']}] already complete: {finished.name} exists and downstream stages "
              f"may already have used it.\n"
              f"  Nothing was run. To deliberately redo this stage and everything after it:\n"
              f"      MD_REDO=1 ./run.sh", flush=True)
        return 0

    def log(message):
        line = f"[{STAGE['name']}] {message}"
        print(line, flush=True)
        log_lines.append(line)

    platform_name = resolve_platform(os.environ.get("MD_PLATFORM") or None)
    device = os.environ.get("MD_DEVICE")
    log(f"platform {platform_name}" + (f", CUDA device {device}" if device else ""))

    barostat_active = kind in BAROSTAT_ACTIVE
    system = build_stage_system(
        INPUTS, implicit=IMPLICIT, restrained=kind in RESTRAINED,
        barostat_active=barostat_active, pressure_bar=STAGE.get("system_pressure_bar"),
        temperature=TEMPERATURE, barostat_seed=int(STAGE["barostat_seed"]),
        solute_indices=SOLUTE_INDICES)

    pdb = PDBFile(str(INPUTS / "topology.pdb"))
    simulation = make_simulation(pdb.topology, system, temperature=TEMPERATURE,
                                 friction=float(STAGE["friction_per_ps"]) / unit.picosecond,
                                 timestep=TIMESTEP_FS * unit.femtoseconds,
                                 seed=int(STAGE["integrator_seed"]),
                                 platform_name=platform_name, device=device)

    # Two different starting points, and the difference is the step counter.
    #
    #   own checkpoint  -> this stage was interrupted. Its step count is how far IT has come, and
    #                      resetting it would run the whole stage again on top of itself.
    #   parent state    -> this stage has not started. The parent's counter belongs to the parent,
    #                      so the count starts at zero here.
    checkpoint = HERE / "checkpoint.chk"
    resuming = checkpoint.is_file()
    if resuming:
        simulation.loadCheckpoint(str(checkpoint))
        done = simulation.context.getStepCount()
        log(f"resuming this stage from checkpoint.chk at step {done:,}")
    else:
        parent_state = require_parent_state(
            (HERE / STAGE["input_state"]).resolve(),
            stage_name=STAGE.get("parent") or "sys-gen",
            command=STAGE.get("parent_path") or "..")
        simulation.context.setState(parent_state)
        simulation.context.setStepCount(0)
        done = 0
        log(f"started from {STAGE['input_state']}")

    # The State carries whatever restraint the parent left set. This stage states its own.
    set_restraint(simulation, float(STAGE["restraint_k_kcal_mol_a2"]))
    log(f"restraint {STAGE['restraint_k_kcal_mol_a2']} kcal/mol/A^2 "
        f"({restraint_strength(simulation):g} kJ/mol/nm^2) on {len(SOLUTE_INDICES)} solute atoms")
    log(f"{active_barostat_count(simulation)} active barostat(s), "
        f"{count_barostats(system)} in the System")

    if kind == "minimization":
        steps = 0
        iterations = int(STAGE["max_iterations"])
        # Minimisation produces the same artifacts as every other stage. A stage whose directory
        # is missing half the files is one nobody can inspect the same way as its neighbours.
        table = StateDataReporter(str(HERE / "stage.csv"), 1, step=True, time=True,
                                  potentialEnergy=True, temperature=True, volume=not IMPLICIT)
        table.report(simulation, simulation.context.getState(
            getEnergy=True, getPositions=True, getVelocities=True))
        log(f"minimising, max {iterations} iterations")
        simulation.minimizeEnergy(maxIterations=iterations)
        simulation.context.setVelocitiesToTemperature(TEMPERATURE, int(STAGE["velocity_seed"]))
        table.report(simulation, simulation.context.getState(
            getEnergy=True, getPositions=True, getVelocities=True))
        del table
        simulation.saveCheckpoint(str(checkpoint))
    else:
        steps = steps_for(float(STAGE["duration_ps"]), TIMESTEP_FS)
        if STAGE.get("assign_velocities") and not resuming:
            simulation.context.setVelocitiesToTemperature(TEMPERATURE, int(STAGE["velocity_seed"]))
        report_every = max(1, steps // 10)
        simulation.reporters.append(CheckpointReporter(str(checkpoint), report_every))
        simulation.reporters.append(StateDataReporter(
            str(HERE / "stage.csv"), report_every, step=True, time=True, potentialEnergy=True,
            temperature=True, volume=not IMPLICIT, append=resuming and done > 0))
        log(f"{STAGE['ensemble']}, {steps - done:,} of {steps:,} steps "
            f"({STAGE['duration_ps']} ps at {TIMESTEP_FS} fs)")
        if steps - done > 0:
            simulation.step(steps - done)
        simulation.saveCheckpoint(str(checkpoint))

    active = active_barostat_count(simulation)
    log(f"complete; restraint {restraint_strength(simulation):g} kJ/mol/nm^2, "
        f"{active} active barostat(s)")

    write_final_state(simulation, HERE / "final_state.xml")
    write_final_pdb(simulation, HERE / "final.pdb", implicit=IMPLICIT)

    resolved = {
        "stage": STAGE["name"],
        "kind": kind,
        "ensemble": STAGE["ensemble"],
        "implicit_solvent": IMPLICIT,
        "max_iterations": STAGE.get("max_iterations"),
        "duration_ps": STAGE.get("duration_ps"),
        "steps": steps,
        "restraint_k_kcal_mol_a2": float(STAGE["restraint_k_kcal_mol_a2"]),
        "restraint_kj_mol_nm2": restraint_strength(simulation),
        "temperature_kelvin": float(STAGE["temperature_kelvin"]),
        "pressure_bar": STAGE.get("pressure_bar"),
        "timestep_fs": TIMESTEP_FS,
        "integrator_seed": int(STAGE["integrator_seed"]),
        "velocity_seed": int(STAGE["velocity_seed"]),
        "barostat_seed": int(STAGE["barostat_seed"]),
        "barostats_in_system": count_barostats(system),
        "barostats_active": active,
        "input_state": STAGE["input_state"],
        "output_state": STAGE["output_state"],
        "platform": platform_name,
        "template_commit": STAGE.get("template_commit"),
        "finished_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }
    (HERE / "resolved_stage.yaml").write_text(yaml.safe_dump(resolved, sort_keys=False),
                                              encoding="utf-8")
    (HERE / "stage.log").write_text("\n".join(log_lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
