#!/usr/bin/env python
"""One common equilibration stage. Generated by md-openmm; edit freely.

What this stage is, how long it runs, how strongly it restrains the solute and which file it reads
are all in `stage.yaml` beside this script. Reading that file is the whole configuration story --
there is no schema layer and no run database.

    input  : the finalized state of the parent stage (never a checkpoint -- see below)
    output : stage.log, stage.csv, checkpoint.chk, final_state.xml, final.pdb, resolved_stage.yaml

`checkpoint.chk` resumes THIS stage in the same OpenMM environment. `final_state.xml` is the
handoff to the next one, and is written only when the stage completes: a downstream stage that
consumed a checkpoint would be starting from a partially finished parent while every file on disk
still looked normal.

Every path is relative to this script, so moving `inputs/` and `MD/` together is enough.
"""
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml
from openmm import unit
from openmm.app import CheckpointReporter, PDBFile, StateDataReporter

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
from md_stages import (PRODUCTION_BAROSTAT_FREQUENCY, active_barostat_count, build_stage_system,
                       count_barostats, make_simulation, require_parent_state, resolve_platform,
                       restraint_strength, set_restraint, steps_for, write_final_pdb,
                       write_final_state)

STAGE = yaml.safe_load((HERE / "stage.yaml").read_text())
CONFIG = yaml.safe_load((HERE.parent / "md.config.yaml").read_text())
INPUTS = (HERE.parent / CONFIG["paths"]["inputs_folder"]).resolve()
SOLUTE = yaml.safe_load((INPUTS / "solute.yaml").read_text())

IMPLICIT = bool(STAGE["implicit"])
SOLUTE_INDICES = list(range(int(SOLUTE["n_solute_atoms"])))
TEMPERATURE = float(STAGE["temperature_kelvin"]) * unit.kelvin
TIMESTEP_FS = float(STAGE["timestep_fs"])

#: Which stages hold the solute, and which run a barostat. The stage kind is the single switch;
#: nothing here is inferred from a directory name.
RESTRAINED = {"minimization", "nvt_restrained", "npt_restrained"}
BAROSTAT_ACTIVE = {"npt_restrained", "npt_free"}


def main():
    kind = STAGE["kind"]
    log_lines = []

    def log(message):
        line = f"[{STAGE['name']}] {message}"
        print(line, flush=True)
        log_lines.append(line)

    platform_name = resolve_platform(os.environ.get("MD_PLATFORM") or None)
    device = os.environ.get("MD_DEVICE")
    log(f"platform {platform_name}" + (f", CUDA device {device}" if device else ""))

    barostat_active = kind in BAROSTAT_ACTIVE
    system = build_stage_system(
        INPUTS, implicit=IMPLICIT, restrained=kind in RESTRAINED,
        barostat_active=barostat_active, pressure_bar=STAGE.get("system_pressure_bar"),
        temperature=TEMPERATURE, barostat_seed=int(STAGE["barostat_seed"]),
        solute_indices=SOLUTE_INDICES)

    pdb = PDBFile(str(INPUTS / "topology.pdb"))
    simulation = make_simulation(pdb.topology, system, temperature=TEMPERATURE,
                                 friction=float(STAGE["friction_per_ps"]) / unit.picosecond,
                                 timestep=TIMESTEP_FS * unit.femtoseconds,
                                 seed=int(STAGE["integrator_seed"]),
                                 platform_name=platform_name, device=device)

    # The parent's finalized state. For the first stage that is the built system's initial state,
    # which sys-gen wrote and which always exists.
    parent_state = require_parent_state(
        (HERE / STAGE["input_state"]).resolve(),
        stage_name=STAGE.get("parent") or "sys-gen",
        command=STAGE.get("parent") or "..")
    simulation.context.setState(parent_state)

    # The State carries whatever restraint the parent left set. This stage states its own.
    set_restraint(simulation, float(STAGE["restraint_k_kcal_mol_a2"]))
    log(f"restraint {STAGE['restraint_k_kcal_mol_a2']} kcal/mol/A^2 "
        f"({restraint_strength(simulation):g} kJ/mol/nm^2) on {len(SOLUTE_INDICES)} solute atoms")
    log(f"{active_barostat_count(simulation)} active barostat(s), "
        f"{count_barostats(system)} in the System")

    if kind == "minimization":
        iterations = int(STAGE["max_iterations"])
        log(f"minimising, max {iterations} iterations")
        simulation.minimizeEnergy(maxIterations=iterations)
        simulation.context.setVelocitiesToTemperature(TEMPERATURE, int(STAGE["velocity_seed"]))
        steps = 0
    else:
        steps = steps_for(float(STAGE["duration_ps"]), TIMESTEP_FS)
        if STAGE.get("assign_velocities"):
            simulation.context.setVelocitiesToTemperature(TEMPERATURE, int(STAGE["velocity_seed"]))
        checkpoint = HERE / "checkpoint.chk"
        done = 0
        if checkpoint.is_file():
            simulation.loadCheckpoint(str(checkpoint))
            done = simulation.context.getStepCount()
            log(f"resuming this stage from checkpoint.chk at step {done:,}")
        report_every = max(1, steps // 10)
        simulation.reporters.append(CheckpointReporter(str(checkpoint), report_every))
        simulation.reporters.append(StateDataReporter(
            str(HERE / "stage.csv"), report_every, step=True, time=True, potentialEnergy=True,
            temperature=True, volume=not IMPLICIT, append=checkpoint.is_file() and done > 0))
        log(f"{STAGE['ensemble']}, {steps - done:,} of {steps:,} steps "
            f"({STAGE['duration_ps']} ps at {TIMESTEP_FS} fs)")
        if steps - done > 0:
            simulation.step(steps - done)
        simulation.saveCheckpoint(str(checkpoint))

    active = active_barostat_count(simulation)
    log(f"complete; restraint {restraint_strength(simulation):g} kJ/mol/nm^2, "
        f"{active} active barostat(s)")

    write_final_state(simulation, HERE / "final_state.xml")
    write_final_pdb(simulation, HERE / "final.pdb", implicit=IMPLICIT)

    resolved = {
        "stage": STAGE["name"],
        "kind": kind,
        "ensemble": STAGE["ensemble"],
        "implicit_solvent": IMPLICIT,
        "max_iterations": STAGE.get("max_iterations"),
        "duration_ps": STAGE.get("duration_ps"),
        "steps": steps,
        "restraint_k_kcal_mol_a2": float(STAGE["restraint_k_kcal_mol_a2"]),
        "restraint_kj_mol_nm2": restraint_strength(simulation),
        "temperature_kelvin": float(STAGE["temperature_kelvin"]),
        "pressure_bar": STAGE.get("pressure_bar"),
        "timestep_fs": TIMESTEP_FS,
        "integrator_seed": int(STAGE["integrator_seed"]),
        "velocity_seed": int(STAGE["velocity_seed"]),
        "barostat_seed": int(STAGE["barostat_seed"]),
        "barostats_in_system": count_barostats(system),
        "barostats_active": active,
        "input_state": STAGE["input_state"],
        "output_state": STAGE["output_state"],
        "platform": platform_name,
        "template_commit": STAGE.get("template_commit"),
        "finished_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }
    (HERE / "resolved_stage.yaml").write_text(yaml.safe_dump(resolved, sort_keys=False),
                                              encoding="utf-8")
    (HERE / "stage.log").write_text("\n".join(log_lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
